/**
 * Bancos de palabras del juego del Impostor.
 * Cada entrada: { w: "palabra secreta", p: "pista para el impostor" }
 * La pista es deliberadamente vaga: orienta sin regalar la palabra.
 */
const PACKS = {
  divertidas: {
    id: 'divertidas',
    name: 'Divertidas',
    emoji: '🎉',
    adult: false,
    desc: 'Cosas, situaciones y absurdos del día a día.',
    words: [
      { w: 'Resaca', p: 'Consecuencia' },
      { w: 'Karaoke', p: 'Micrófono' },
      { w: 'Siesta', p: 'Descanso' },
      { w: 'Suegra', p: 'Familia política' },
      { w: 'Gimnasio', p: 'Propósito de año nuevo' },
      { w: 'Selfie', p: 'Cámara frontal' },
      { w: 'Wifi', p: 'Invisible pero vital' },
      { w: 'Reggaetón', p: 'Suena en la fiesta' },
      { w: 'Barbacoa', p: 'Humo y carne' },
      { w: 'Grupo de WhatsApp', p: 'Notificaciones' },
      { w: 'Despertador', p: 'Odiado por la mañana' },
      { w: 'Papel higiénico', p: 'Se acaba siempre' },
      { w: 'Photocall', p: 'Posturitas' },
      { w: 'Cuñado', p: 'Opina de todo' },
      { w: 'Buffet libre', p: 'Sin límite' },
      { w: 'Tinder', p: 'Se desliza' },
      { w: 'Chandal', p: 'Comodidad' },
      { w: 'Nochevieja', p: 'Cuenta atrás' },
      { w: 'Pelo en la sopa', p: 'Desagradable' },
      { w: 'Autobús', p: 'Transporte' },
      { w: 'Peluquería', p: 'Cambio de look' },
      { w: 'Dentista', p: 'Nadie quiere ir' },
      { w: 'Uñas postizas', p: 'Estética' },
      { w: 'Chuleta en el examen', p: 'Trampa' },
      { w: 'Piso compartido', p: 'Convivencia' },
      { w: 'Hora punta', p: 'Aglomeración' },
      { w: 'Lunes', p: 'Rutina' },
      { w: 'Pesadilla', p: 'Dormido' },
      { w: 'Vecino ruidoso', p: 'Molestia' },
      { w: 'Ronquidos', p: 'Nocturno' },
      { w: 'Bótox', p: 'Retoque' },
      { w: 'Concierto', p: 'Multitud' },
      { w: 'Camping', p: 'Aire libre' },
      { w: 'Playa nudista', p: 'Costa' },
      { w: 'Discoteca', p: 'Noche' },
      { w: 'Chupito', p: 'Rápido y fuerte' },
      { w: 'Kebab de madrugada', p: 'Después de salir' },
      { w: 'Bar de barrio', p: 'Local' },
      { w: 'Tatuaje del que te arrepientes', p: 'Permanente' },
      { w: 'Piercing', p: 'Perforación' },
      { w: 'Netflix', p: 'Sofá' },
      { w: 'Spoiler', p: 'Arruina algo' },
      { w: 'Fiesta sorpresa', p: 'Inesperado' },
      { w: 'Boda', p: 'Celebración' },
      { w: 'Divorcio', p: 'Final de algo' },
      { w: 'Herencia', p: 'Dinero familiar' },
      { w: 'Lotería', p: 'Suerte' },
      { w: 'Multa de tráfico', p: 'Sanción' },
      { w: 'Radar', p: 'Carretera' },
      { w: 'ITV', p: 'Revisión' },
      { w: 'Gato', p: 'Mascota' },
      { w: 'Perro salchicha', p: 'Animal' },
      { w: 'Zoo', p: 'Animales' },
      { w: 'Mosquito', p: 'Verano molesto' },
      { w: 'Cucaracha', p: 'Insecto' },
      { w: 'Piscina de bola', p: 'Infantil' },
      { w: 'Cumpleaños infantil', p: 'Niños' },
      { w: 'Payaso', p: 'Circo' },
      { w: 'Ratoncito Pérez', p: 'Mito infantil' },
      { w: 'Papá Noel', p: 'Diciembre' },
      { w: 'Halloween', p: 'Disfraces' },
      { w: 'Vermut', p: 'Aperitivo' },
      { w: 'Tortilla de patatas', p: 'Plato típico' },
      { w: 'Piña en la pizza', p: 'Polémico' },
      { w: 'Sushi', p: 'Comida' },
      { w: 'Café con leche', p: 'Bebida' },
      { w: 'Ensalada', p: 'Sano' },
      { w: 'Bocadillo de calamares', p: 'Comida callejera' },
      { w: 'Helado derretido', p: 'Verano' },
      { w: 'Chocolate', p: 'Dulce' },
      { w: 'Ajo', p: 'Aliento' },
      { w: 'Picante', p: 'Sabor' },
      { w: 'Microondas', p: 'Cocina' },
      { w: 'Aspiradora', p: 'Limpieza' },
      { w: 'Calcetín perdido', p: 'Desaparece' },
      { w: 'Lavavajillas', p: 'Electrodoméstico' },
      { w: 'Espejo', p: 'Refleja' },
      { w: 'Báscula', p: 'Números incómodos' },
      { w: 'Ascensor', p: 'Silencio incómodo' },
      { w: 'Gimnasio a las 7am', p: 'Madrugar' },
      { w: 'Videollamada', p: 'Pantalla' },
      { w: 'Reunión que podría ser un email', p: 'Trabajo' },
      { w: 'Jefe', p: 'Trabajo' },
      { w: 'Nómina', p: 'Mensual' },
      { w: 'Hacienda', p: 'Impuestos' },
      { w: 'Vacaciones', p: 'Descanso' },
      { w: 'Maleta perdida', p: 'Aeropuerto' },
      { w: 'Turista', p: 'Viaje' },
      { w: 'Crucero', p: 'Barco' },
      { w: 'Mareo', p: 'Movimiento' },
      { w: 'Karma', p: 'Consecuencia' },
      { w: 'Horóscopo', p: 'Predicción' },
      { w: 'Fantasma', p: 'Sobrenatural' },
      { w: 'Ouija', p: 'Ritual' },
      { w: 'Gimnasio de barrio', p: 'Deporte' },
      { w: 'Fútbol', p: 'Deporte' },
      { w: 'Padel', p: 'Deporte de moda' },
      { w: 'Maratón', p: 'Resistencia' },
      { w: 'Bicicleta estática', p: 'Ejercicio' },
      { w: 'Yoga', p: 'Relajación' },
      { w: 'Meditación', p: 'Mente' },
      { w: 'Terapia', p: 'Hablar de ti' },
      { w: 'Ansiedad del domingo', p: 'Fin de semana' },
      { w: 'Audio de 8 minutos', p: 'Mensajería' },
      { w: 'Visto sin contestar', p: 'Mensajería' },
      { w: 'Stalkear un perfil', p: 'Redes sociales' },
      { w: 'Influencer', p: 'Redes sociales' },
      { w: 'Filtro de belleza', p: 'Foto' },
      { w: 'Story borrada', p: 'Arrepentimiento' },
      { w: 'Batería al 1%', p: 'Urgencia' },
      { w: 'Cargador que no es tuyo', p: 'Prestado' },
      { w: 'Contraseña olvidada', p: 'Acceso' },
      { w: 'Cita a ciegas', p: 'Desconocido' }
    ]
  },

  picante: {
    id: 'picante',
    name: 'Picante',
    emoji: '🌶️',
    adult: true,
    desc: 'Subidita de tono. Para grupos con confianza (+18).',
    words: [
      { w: 'Beso francés', p: 'Contacto' },
      { w: 'Morreo en la disco', p: 'Noche' },
      { w: 'Ex tóxico', p: 'Pasado' },
      { w: 'Sexting', p: 'Mensajes' },
      { w: 'Nudes', p: 'Fotos' },
      { w: 'Amigos con derechos', p: 'Relación rara' },
      { w: 'Cuernos', p: 'Traición' },
      { w: 'Triángulo amoroso', p: 'Complicado' },
      { w: 'Lío de una noche', p: 'Efímero' },
      { w: 'Despedida de soltero', p: 'Fiesta' },
      { w: 'Stripper', p: 'Espectáculo' },
      { w: 'Table dance', p: 'Baile' },
      { w: 'Perreo', p: 'Baile' },
      { w: 'Twerking', p: 'Movimiento' },
      { w: 'Strip poker', p: 'Juego' },
      { w: 'Verdad o reto', p: 'Juego' },
      { w: 'Botella (el juego)', p: 'Juego de fiesta' },
      { w: 'Motel', p: 'Alojamiento' },
      { w: 'Jacuzzi', p: 'Agua caliente' },
      { w: 'Sauna', p: 'Calor' },
      { w: 'Ducha juntos', p: 'Baño' },
      { w: 'Ropa interior', p: 'Prenda' },
      { w: 'Tanga', p: 'Prenda' },
      { w: 'Encaje', p: 'Tejido' },
      { w: 'Lencería', p: 'Prenda' },
      { w: 'Escote', p: 'Vestimenta' },
      { w: 'Topless', p: 'Playa' },
      { w: 'Nudismo', p: 'Sin ropa' },
      { w: 'Marca de bronceado', p: 'Piel' },
      { w: 'Aceite de masaje', p: 'Producto' },
      { w: 'Masaje de pareja', p: 'Contacto' },
      { w: 'Chupetón', p: 'Marca' },
      { w: 'Mordisco', p: 'Boca' },
      { w: 'Susurro al oído', p: 'Cerca' },
      { w: 'Mirada intensa', p: 'No verbal' },
      { w: 'Flirteo', p: 'Coqueteo' },
      { w: 'Piropo', p: 'Comentario' },
      { w: 'Indirecta', p: 'Mensaje oculto' },
      { w: 'Doble sentido', p: 'Ambigüedad' },
      { w: 'Preservativo', p: 'Protección' },
      { w: 'Test de embarazo', p: 'Resultado' },
      { w: 'Luna de miel', p: 'Viaje' },
      { w: 'Primera cita', p: 'Encuentro' },
      { w: 'Ghosting', p: 'Desaparecer' },
      { w: 'Ligar en la barra', p: 'Bar' },
      { w: 'Número de teléfono en una servilleta', p: 'Contacto' },
      { w: 'Bailar pegados', p: 'Cercanía' },
      { w: 'Beso de tres', p: 'Grupo' },
      { w: 'Escapada de fin de semana', p: 'Viaje corto' },
      { w: 'Cita clandestina', p: 'Secreto' },
      { w: 'Amante', p: 'Secreto' },
      { w: 'Disfraz de enfermera', p: 'Disfraz' },
      { w: 'Uniforme', p: 'Vestimenta' },
      { w: 'Tacones', p: 'Calzado' },
      { w: 'Perfume caro', p: 'Olor' },
      { w: 'Cita por videollamada', p: 'Distancia' },
      { w: 'Relación abierta', p: 'Acuerdo' },
      { w: 'Celos', p: 'Emoción' },
      { w: 'Chat borrado', p: 'Evidencia' },
      { w: 'Segundo móvil', p: 'Sospechoso' },
      { w: 'Pintalabios en la camisa', p: 'Prueba' },
      { w: 'Vecina del quinto', p: 'Vecindario' },
      { w: 'Monitor de gimnasio', p: 'Profesión' },
      { w: 'Socorrista', p: 'Profesión' },
      { w: 'Jefe atractivo', p: 'Trabajo' },
      { w: 'Fiesta en la piscina', p: 'Verano' },
      { w: 'Barra libre', p: 'Alcohol' },
      { w: 'Tequila', p: 'Bebida' },
      { w: 'Última copa', p: 'Final de noche' },
      { w: 'Taxi a las 6am', p: 'Madrugada' },
      { w: 'Walk of shame', p: 'Mañana siguiente' },
      { w: 'Cama deshecha', p: 'Habitación' },
      { w: 'No recordar la noche', p: 'Memoria' },
      { w: 'Llamada borracha al ex', p: 'Arrepentimiento' },
      { w: 'Tatuaje en sitio íntimo', p: 'Cuerpo' },
      { w: 'Depilación', p: 'Cuidado personal' },
      { w: 'Poste de pole dance', p: 'Baile' },
      { w: 'Antifaz', p: 'Accesorio' },
      { w: 'Esposas de juguete', p: 'Accesorio' },
      { w: 'Plumas', p: 'Cosquillas' },
      { w: 'Velas', p: 'Ambiente' },
      { w: 'Playlist romántica', p: 'Música' },
      { w: 'Cena a la luz de las velas', p: 'Cita' }
    ]
  },

  pop: {
    id: 'pop',
    name: 'Famosos y Pop',
    emoji: '⭐',
    adult: false,
    desc: 'Personajes, pelis y cultura popular.',
    words: [
      { w: 'Shakira', p: 'Música' },
      { w: 'Bad Bunny', p: 'Música' },
      { w: 'Rosalía', p: 'Música' },
      { w: 'Taylor Swift', p: 'Música' },
      { w: 'Beyoncé', p: 'Música' },
      { w: 'Elvis', p: 'Música clásica' },
      { w: 'Michael Jackson', p: 'Baile' },
      { w: 'Messi', p: 'Deporte' },
      { w: 'Cristiano Ronaldo', p: 'Deporte' },
      { w: 'Rafa Nadal', p: 'Deporte' },
      { w: 'Elon Musk', p: 'Empresario' },
      { w: 'Batman', p: 'Superhéroe' },
      { w: 'Spider-Man', p: 'Superhéroe' },
      { w: 'Darth Vader', p: 'Villano' },
      { w: 'Joker', p: 'Villano' },
      { w: 'Harry Potter', p: 'Magia' },
      { w: 'Shrek', p: 'Animación' },
      { w: 'Bob Esponja', p: 'Dibujos' },
      { w: 'Homer Simpson', p: 'Dibujos' },
      { w: 'Los Vengadores', p: 'Grupo' },
      { w: 'Titanic', p: 'Película' },
      { w: 'Juego de Tronos', p: 'Serie' },
      { w: 'La Casa de Papel', p: 'Serie' },
      { w: 'Stranger Things', p: 'Serie' },
      { w: 'Barbie', p: 'Icono' },
      { w: 'Mario Bros', p: 'Videojuego' },
      { w: 'Fortnite', p: 'Videojuego' },
      { w: 'Pokémon', p: 'Videojuego' },
      { w: 'Minecraft', p: 'Videojuego' },
      { w: 'Eurovisión', p: 'Concurso' },
      { w: 'Gran Hermano', p: 'Reality' },
      { w: 'MasterChef', p: 'Concurso' },
      { w: 'Oscar', p: 'Premio' },
      { w: 'Alfombra roja', p: 'Evento' },
      { w: 'Paparazzi', p: 'Prensa' },
      { w: 'Reality de citas', p: 'Televisión' },
      { w: 'Mona Lisa', p: 'Arte' },
      { w: 'Picasso', p: 'Arte' },
      { w: 'Frida Kahlo', p: 'Arte' },
      { w: 'Cleopatra', p: 'Historia' },
      { w: 'Napoleón', p: 'Historia' },
      { w: 'Einstein', p: 'Ciencia' },
      { w: 'Guardia Civil', p: 'Uniforme' },
      { w: 'Torre Eiffel', p: 'Monumento' },
      { w: 'Times Square', p: 'Lugar' },
      { w: 'Las Vegas', p: 'Ciudad' },
      { w: 'Ibiza', p: 'Isla' },
      { w: 'Nueva York', p: 'Ciudad' },
      { w: 'Tokio', p: 'Ciudad' },
      { w: 'Machu Picchu', p: 'Destino' }
    ]
  },

  clasicas: {
    id: 'clasicas',
    name: 'Clásicas',
    emoji: '🧩',
    adult: false,
    desc: 'Palabras limpias y fáciles. Ideal para calentar o jugar con niños.',
    words: [
      { w: 'Playa', p: 'Lugar' },
      { w: 'Montaña', p: 'Naturaleza' },
      { w: 'Hospital', p: 'Edificio' },
      { w: 'Colegio', p: 'Edificio' },
      { w: 'Supermercado', p: 'Compras' },
      { w: 'Biblioteca', p: 'Silencio' },
      { w: 'Cine', p: 'Ocio' },
      { w: 'Restaurante', p: 'Comida' },
      { w: 'Aeropuerto', p: 'Viaje' },
      { w: 'Estación de tren', p: 'Transporte' },
      { w: 'Bombero', p: 'Profesión' },
      { w: 'Médico', p: 'Profesión' },
      { w: 'Profesor', p: 'Profesión' },
      { w: 'Cocinero', p: 'Profesión' },
      { w: 'Astronauta', p: 'Profesión' },
      { w: 'Panadero', p: 'Profesión' },
      { w: 'Guitarra', p: 'Instrumento' },
      { w: 'Piano', p: 'Instrumento' },
      { w: 'Batería', p: 'Instrumento' },
      { w: 'Bicicleta', p: 'Vehículo' },
      { w: 'Avión', p: 'Vehículo' },
      { w: 'Submarino', p: 'Vehículo' },
      { w: 'Paraguas', p: 'Objeto' },
      { w: 'Reloj', p: 'Objeto' },
      { w: 'Gafas', p: 'Objeto' },
      { w: 'Almohada', p: 'Dormir' },
      { w: 'Nevera', p: 'Cocina' },
      { w: 'Tijeras', p: 'Herramienta' },
      { w: 'Martillo', p: 'Herramienta' },
      { w: 'Llave', p: 'Abrir' },
      { w: 'Manzana', p: 'Fruta' },
      { w: 'Sandía', p: 'Fruta' },
      { w: 'Zanahoria', p: 'Verdura' },
      { w: 'Queso', p: 'Alimento' },
      { w: 'Pan', p: 'Alimento' },
      { w: 'Leche', p: 'Bebida' },
      { w: 'León', p: 'Animal' },
      { w: 'Elefante', p: 'Animal' },
      { w: 'Pingüino', p: 'Animal' },
      { w: 'Tiburón', p: 'Animal' },
      { w: 'Mariposa', p: 'Animal' },
      { w: 'Nieve', p: 'Clima' },
      { w: 'Tormenta', p: 'Clima' },
      { w: 'Arcoíris', p: 'Cielo' },
      { w: 'Luna', p: 'Cielo' },
      { w: 'Volcán', p: 'Naturaleza' },
      { w: 'Desierto', p: 'Naturaleza' },
      { w: 'Río', p: 'Agua' },
      { w: 'Bosque', p: 'Naturaleza' },
      { w: 'Castillo', p: 'Construcción' }
    ]
  }
};
