/**
 * Bancos de palabras del juego del Impostor.
 * Cada entrada: { w: "palabra secreta", p: "pista para el impostor" }
 *
 * Reglas del banco:
 *  - Palabras reales, de una o dos palabras como máximo. Nada de frases.
 *  - Cosas concretas y conocidas: si no se puede describir con una palabra
 *    suelta, no entra.
 *  - La pista es una categoría vaga: orienta al impostor sin regalar nada.
 */
const PACKS = {
  divertidas: {
    id: 'divertidas',
    name: 'Divertidas',
    emoji: '🎉',
    adult: false,
    desc: 'Cosas del día a día con retranca.',
    words: [
      { w: 'Resaca', p: 'Consecuencia' },
      { w: 'Karaoke', p: 'Micrófono' },
      { w: 'Siesta', p: 'Descanso' },
      { w: 'Suegra', p: 'Familia' },
      { w: 'Cuñado', p: 'Familia' },
      { w: 'Gimnasio', p: 'Ejercicio' },
      { w: 'Selfie', p: 'Foto' },
      { w: 'Wifi', p: 'Conexión' },
      { w: 'Reggaetón', p: 'Música' },
      { w: 'Barbacoa', p: 'Comida' },
      { w: 'Despertador', p: 'Mañana' },
      { w: 'Tinder', p: 'Aplicación' },
      { w: 'Chándal', p: 'Ropa' },
      { w: 'Nochevieja', p: 'Fiesta' },
      { w: 'Autobús', p: 'Transporte' },
      { w: 'Peluquería', p: 'Local' },
      { w: 'Dentista', p: 'Profesión' },
      { w: 'Lunes', p: 'Semana' },
      { w: 'Pesadilla', p: 'Sueño' },
      { w: 'Ronquidos', p: 'Noche' },
      { w: 'Insomnio', p: 'Noche' },
      { w: 'Bótox', p: 'Estética' },
      { w: 'Manicura', p: 'Estética' },
      { w: 'Bronceado', p: 'Sol' },
      { w: 'Concierto', p: 'Música' },
      { w: 'Camping', p: 'Vacaciones' },
      { w: 'Discoteca', p: 'Noche' },
      { w: 'Botellón', p: 'Fiesta' },
      { w: 'Chupito', p: 'Bebida' },
      { w: 'Cerveza', p: 'Bebida' },
      { w: 'Vermut', p: 'Bebida' },
      { w: 'Café', p: 'Bebida' },
      { w: 'Kebab', p: 'Comida' },
      { w: 'Paella', p: 'Comida' },
      { w: 'Tortilla', p: 'Comida' },
      { w: 'Sushi', p: 'Comida' },
      { w: 'Ensalada', p: 'Comida' },
      { w: 'Churros', p: 'Desayuno' },
      { w: 'Helado', p: 'Postre' },
      { w: 'Chocolate', p: 'Dulce' },
      { w: 'Piña', p: 'Fruta' },
      { w: 'Ajo', p: 'Condimento' },
      { w: 'Tatuaje', p: 'Piel' },
      { w: 'Piercing', p: 'Piel' },
      { w: 'Netflix', p: 'Ocio' },
      { w: 'Spoiler', p: 'Serie' },
      { w: 'Boda', p: 'Celebración' },
      { w: 'Divorcio', p: 'Pareja' },
      { w: 'Herencia', p: 'Dinero' },
      { w: 'Lotería', p: 'Suerte' },
      { w: 'Multa', p: 'Sanción' },
      { w: 'Radar', p: 'Carretera' },
      { w: 'Atasco', p: 'Tráfico' },
      { w: 'Aparcamiento', p: 'Coche' },
      { w: 'Taxi', p: 'Transporte' },
      { w: 'Metro', p: 'Transporte' },
      { w: 'Gato', p: 'Mascota' },
      { w: 'Zoo', p: 'Animales' },
      { w: 'Mosquito', p: 'Insecto' },
      { w: 'Cucaracha', p: 'Insecto' },
      { w: 'Payaso', p: 'Circo' },
      { w: 'Halloween', p: 'Fiesta' },
      { w: 'Fantasma', p: 'Miedo' },
      { w: 'Ouija', p: 'Ritual' },
      { w: 'Horóscopo', p: 'Predicción' },
      { w: 'Microondas', p: 'Cocina' },
      { w: 'Aspiradora', p: 'Limpieza' },
      { w: 'Calcetín', p: 'Ropa' },
      { w: 'Espejo', p: 'Objeto' },
      { w: 'Báscula', p: 'Peso' },
      { w: 'Ascensor', p: 'Edificio' },
      { w: 'Mudanza', p: 'Casa' },
      { w: 'Vecino', p: 'Edificio' },
      { w: 'Videollamada', p: 'Pantalla' },
      { w: 'Cargador', p: 'Móvil' },
      { w: 'Contraseña', p: 'Acceso' },
      { w: 'Influencer', p: 'Redes' },
      { w: 'Jefe', p: 'Trabajo' },
      { w: 'Nómina', p: 'Dinero' },
      { w: 'Hacienda', p: 'Impuestos' },
      { w: 'Propina', p: 'Restaurante' },
      { w: 'Camarero', p: 'Profesión' },
      { w: 'Barbero', p: 'Profesión' },
      { w: 'Vacaciones', p: 'Descanso' },
      { w: 'Maleta', p: 'Viaje' },
      { w: 'Turista', p: 'Viaje' },
      { w: 'Crucero', p: 'Barco' },
      { w: 'Mareo', p: 'Malestar' },
      { w: 'Sombrilla', p: 'Verano' },
      { w: 'Piscina', p: 'Verano' },
      { w: 'Chiringuito', p: 'Verano' },
      { w: 'Fútbol', p: 'Deporte' },
      { w: 'Pádel', p: 'Deporte' },
      { w: 'Maratón', p: 'Deporte' },
      { w: 'Yoga', p: 'Relajación' },
      { w: 'Terapia', p: 'Salud' },
      { w: 'Alergia', p: 'Salud' },
      { w: 'Estornudo', p: 'Reflejo' },
      { w: 'Hipo', p: 'Reflejo' },
      { w: 'Cosquillas', p: 'Risa' }
    ]
  },

  picante: {
    id: 'picante',
    name: 'Picante',
    emoji: '🌶️',
    adult: true,
    desc: 'Sin filtros. Para grupos con confianza (+18).',
    words: [
      { w: 'Sexo oral', p: 'Práctica' },
      { w: 'Orgasmo', p: 'Clímax' },
      { w: 'Preservativo', p: 'Protección' },
      { w: 'Masturbación', p: 'Solitario' },
      { w: 'Vibrador', p: 'Juguete' },
      { w: 'Consolador', p: 'Juguete' },
      { w: 'Kamasutra', p: 'Libro' },
      { w: 'Trío', p: 'Grupo' },
      { w: 'Orgía', p: 'Grupo' },
      { w: 'Striptease', p: 'Espectáculo' },
      { w: 'Pole dance', p: 'Baile' },
      { w: 'Perreo', p: 'Baile' },
      { w: 'Twerking', p: 'Baile' },
      { w: 'Lencería', p: 'Ropa' },
      { w: 'Tanga', p: 'Ropa' },
      { w: 'Liguero', p: 'Ropa' },
      { w: 'Corsé', p: 'Ropa' },
      { w: 'Sujetador', p: 'Ropa' },
      { w: 'Braguitas', p: 'Ropa' },
      { w: 'Calzoncillos', p: 'Ropa' },
      { w: 'Encaje', p: 'Tejido' },
      { w: 'Látex', p: 'Material' },
      { w: 'Cuero', p: 'Material' },
      { w: 'Tacones', p: 'Calzado' },
      { w: 'Antifaz', p: 'Accesorio' },
      { w: 'Esposas', p: 'Accesorio' },
      { w: 'Látigo', p: 'Accesorio' },
      { w: 'Plumas', p: 'Accesorio' },
      { w: 'Escote', p: 'Cuerpo' },
      { w: 'Culo', p: 'Cuerpo' },
      { w: 'Tetas', p: 'Cuerpo' },
      { w: 'Pezón', p: 'Cuerpo' },
      { w: 'Muslos', p: 'Cuerpo' },
      { w: 'Cintura', p: 'Cuerpo' },
      { w: 'Lengua', p: 'Cuerpo' },
      { w: 'Labios', p: 'Cuerpo' },
      { w: 'Desnudo', p: 'Cuerpo' },
      { w: 'Topless', p: 'Playa' },
      { w: 'Nudismo', p: 'Sin ropa' },
      { w: 'Beso francés', p: 'Beso' },
      { w: 'Morreo', p: 'Beso' },
      { w: 'Chupetón', p: 'Marca' },
      { w: 'Mordisco', p: 'Boca' },
      { w: 'Gemido', p: 'Sonido' },
      { w: 'Jadeo', p: 'Sonido' },
      { w: 'Susurro', p: 'Sonido' },
      { w: 'Caricia', p: 'Contacto' },
      { w: 'Masaje', p: 'Contacto' },
      { w: 'Roce', p: 'Contacto' },
      { w: 'Aceite', p: 'Producto' },
      { w: 'Lubricante', p: 'Producto' },
      { w: 'Perfume', p: 'Olor' },
      { w: 'Sexting', p: 'Mensajes' },
      { w: 'Nudes', p: 'Fotos' },
      { w: 'Webcam', p: 'Pantalla' },
      { w: 'OnlyFans', p: 'Plataforma' },
      { w: 'Porno', p: 'Contenido' },
      { w: 'Fetiche', p: 'Gusto' },
      { w: 'Fantasía', p: 'Imaginación' },
      { w: 'Morbo', p: 'Deseo' },
      { w: 'Lujuria', p: 'Pecado' },
      { w: 'Tentación', p: 'Deseo' },
      { w: 'Coqueteo', p: 'Ligar' },
      { w: 'Piropo', p: 'Comentario' },
      { w: 'Indirecta', p: 'Mensaje' },
      { w: 'Ligue', p: 'Encuentro' },
      { w: 'Rollo', p: 'Relación' },
      { w: 'Amante', p: 'Secreto' },
      { w: 'Infidelidad', p: 'Traición' },
      { w: 'Cuernos', p: 'Traición' },
      { w: 'Celos', p: 'Emoción' },
      { w: 'Ghosting', p: 'Desaparecer' },
      { w: 'Poliamor', p: 'Relación' },
      { w: 'Swinger', p: 'Pareja' },
      { w: 'Sumiso', p: 'Rol' },
      { w: 'Dominante', p: 'Rol' },
      { w: 'Misionero', p: 'Postura' },
      { w: 'Postura', p: 'Sexo' },
      { w: 'Motel', p: 'Alojamiento' },
      { w: 'Jacuzzi', p: 'Agua' },
      { w: 'Sauna', p: 'Calor' },
      { w: 'Ducha', p: 'Baño' },
      { w: 'Sábanas', p: 'Cama' },
      { w: 'Cama', p: 'Mueble' },
      { w: 'Sofá', p: 'Mueble' },
      { w: 'Velas', p: 'Ambiente' },
      { w: 'Champán', p: 'Bebida' },
      { w: 'Tequila', p: 'Bebida' },
      { w: 'Afrodisíaco', p: 'Efecto' },
      { w: 'Nata', p: 'Comida' },
      { w: 'Miel', p: 'Dulce' },
      { w: 'Despedida', p: 'Fiesta' },
      { w: 'Stripper', p: 'Profesión' },
      { w: 'Burdel', p: 'Lugar' },
      { w: 'Sex shop', p: 'Tienda' },
      { w: 'Virginidad', p: 'Primera vez' },
      { w: 'Cita ciega', p: 'Desconocido' },
      { w: 'Strip poker', p: 'Juego' },
      { w: 'Botella', p: 'Juego' },
      { w: 'Reto', p: 'Juego' }
    ]
  },

  pop: {
    id: 'pop',
    name: 'Famosos y Pop',
    emoji: '⭐',
    adult: false,
    desc: 'Personajes, pelis, series y videojuegos.',
    words: [
      { w: 'Shakira', p: 'Música' },
      { w: 'Bad Bunny', p: 'Música' },
      { w: 'Rosalía', p: 'Música' },
      { w: 'Taylor Swift', p: 'Música' },
      { w: 'Beyoncé', p: 'Música' },
      { w: 'Rihanna', p: 'Música' },
      { w: 'Dua Lipa', p: 'Música' },
      { w: 'Madonna', p: 'Música' },
      { w: 'Elvis', p: 'Música' },
      { w: 'Michael Jackson', p: 'Baile' },
      { w: 'Freddie Mercury', p: 'Rock' },
      { w: 'Bob Marley', p: 'Reggae' },
      { w: 'Eminem', p: 'Rap' },
      { w: 'Messi', p: 'Fútbol' },
      { w: 'Cristiano', p: 'Fútbol' },
      { w: 'Ronaldinho', p: 'Fútbol' },
      { w: 'Nadal', p: 'Tenis' },
      { w: 'Alcaraz', p: 'Tenis' },
      { w: 'Jordan', p: 'Baloncesto' },
      { w: 'LeBron', p: 'Baloncesto' },
      { w: 'Elon Musk', p: 'Empresario' },
      { w: 'Bill Gates', p: 'Empresario' },
      { w: 'Steve Jobs', p: 'Empresario' },
      { w: 'Batman', p: 'Superhéroe' },
      { w: 'Superman', p: 'Superhéroe' },
      { w: 'Spiderman', p: 'Superhéroe' },
      { w: 'Hulk', p: 'Superhéroe' },
      { w: 'Thor', p: 'Superhéroe' },
      { w: 'Iron Man', p: 'Superhéroe' },
      { w: 'Joker', p: 'Villano' },
      { w: 'Thanos', p: 'Villano' },
      { w: 'Darth Vader', p: 'Villano' },
      { w: 'Voldemort', p: 'Villano' },
      { w: 'Yoda', p: 'Star Wars' },
      { w: 'Chewbacca', p: 'Star Wars' },
      { w: 'Harry Potter', p: 'Magia' },
      { w: 'Hermione', p: 'Magia' },
      { w: 'Gandalf', p: 'Fantasía' },
      { w: 'Frodo', p: 'Fantasía' },
      { w: 'Shrek', p: 'Animación' },
      { w: 'Fiona', p: 'Animación' },
      { w: 'Bob Esponja', p: 'Dibujos' },
      { w: 'Patricio', p: 'Dibujos' },
      { w: 'Homer', p: 'Dibujos' },
      { w: 'Bart', p: 'Dibujos' },
      { w: 'Pikachu', p: 'Videojuego' },
      { w: 'Mario', p: 'Videojuego' },
      { w: 'Luigi', p: 'Videojuego' },
      { w: 'Sonic', p: 'Videojuego' },
      { w: 'Zelda', p: 'Videojuego' },
      { w: 'Minecraft', p: 'Videojuego' },
      { w: 'Fortnite', p: 'Videojuego' },
      { w: 'Tetris', p: 'Videojuego' },
      { w: 'Pacman', p: 'Videojuego' },
      { w: 'Roblox', p: 'Videojuego' },
      { w: 'Titanic', p: 'Película' },
      { w: 'Avatar', p: 'Película' },
      { w: 'Matrix', p: 'Película' },
      { w: 'Terminator', p: 'Película' },
      { w: 'Gladiator', p: 'Película' },
      { w: 'Rocky', p: 'Película' },
      { w: 'Rambo', p: 'Película' },
      { w: 'Godzilla', p: 'Monstruo' },
      { w: 'King Kong', p: 'Monstruo' },
      { w: 'Jurassic Park', p: 'Película' },
      { w: 'Star Wars', p: 'Saga' },
      { w: 'Marvel', p: 'Cómics' },
      { w: 'Disney', p: 'Estudio' },
      { w: 'Pixar', p: 'Estudio' },
      { w: 'Frozen', p: 'Animación' },
      { w: 'Elsa', p: 'Animación' },
      { w: 'Aladdín', p: 'Animación' },
      { w: 'Simba', p: 'Animación' },
      { w: 'Mufasa', p: 'Animación' },
      { w: 'Dumbo', p: 'Animación' },
      { w: 'Bambi', p: 'Animación' },
      { w: 'Barbie', p: 'Juguete' },
      { w: 'Ken', p: 'Juguete' },
      { w: 'Khaleesi', p: 'Serie' },
      { w: 'Jon Nieve', p: 'Serie' },
      { w: 'Stranger Things', p: 'Serie' },
      { w: 'Squid Game', p: 'Serie' },
      { w: 'Breaking Bad', p: 'Serie' },
      { w: 'Los Simpson', p: 'Serie' },
      { w: 'Friends', p: 'Serie' },
      { w: 'Eurovisión', p: 'Concurso' },
      { w: 'Óscar', p: 'Premio' },
      { w: 'Grammy', p: 'Premio' },
      { w: 'Cannes', p: 'Festival' },
      { w: 'Paparazzi', p: 'Prensa' },
      { w: 'Alfombra roja', p: 'Evento' },
      { w: 'Hollywood', p: 'Cine' },
      { w: 'Mona Lisa', p: 'Arte' },
      { w: 'Picasso', p: 'Arte' },
      { w: 'Van Gogh', p: 'Arte' },
      { w: 'Dalí', p: 'Arte' },
      { w: 'Frida Kahlo', p: 'Arte' },
      { w: 'Cleopatra', p: 'Historia' },
      { w: 'Napoleón', p: 'Historia' },
      { w: 'Einstein', p: 'Ciencia' }
    ]
  },

  clasicas: {
    id: 'clasicas',
    name: 'Clásicas',
    emoji: '🧩',
    adult: false,
    desc: 'Fáciles y para todos los públicos.',
    words: [
      { w: 'Playa', p: 'Lugar' },
      { w: 'Montaña', p: 'Naturaleza' },
      { w: 'Volcán', p: 'Naturaleza' },
      { w: 'Hospital', p: 'Edificio' },
      { w: 'Colegio', p: 'Edificio' },
      { w: 'Biblioteca', p: 'Edificio' },
      { w: 'Museo', p: 'Edificio' },
      { w: 'Iglesia', p: 'Edificio' },
      { w: 'Castillo', p: 'Edificio' },
      { w: 'Supermercado', p: 'Compras' },
      { w: 'Cine', p: 'Ocio' },
      { w: 'Restaurante', p: 'Comida' },
      { w: 'Aeropuerto', p: 'Viaje' },
      { w: 'Estación', p: 'Transporte' },
      { w: 'Puente', p: 'Construcción' },
      { w: 'Faro', p: 'Costa' },
      { w: 'Molino', p: 'Construcción' },
      { w: 'Bombero', p: 'Profesión' },
      { w: 'Médico', p: 'Profesión' },
      { w: 'Profesor', p: 'Profesión' },
      { w: 'Cocinero', p: 'Profesión' },
      { w: 'Astronauta', p: 'Profesión' },
      { w: 'Panadero', p: 'Profesión' },
      { w: 'Policía', p: 'Profesión' },
      { w: 'Cartero', p: 'Profesión' },
      { w: 'Granjero', p: 'Profesión' },
      { w: 'Piloto', p: 'Profesión' },
      { w: 'Guitarra', p: 'Instrumento' },
      { w: 'Piano', p: 'Instrumento' },
      { w: 'Violín', p: 'Instrumento' },
      { w: 'Trompeta', p: 'Instrumento' },
      { w: 'Tambor', p: 'Instrumento' },
      { w: 'Bicicleta', p: 'Vehículo' },
      { w: 'Avión', p: 'Vehículo' },
      { w: 'Submarino', p: 'Vehículo' },
      { w: 'Helicóptero', p: 'Vehículo' },
      { w: 'Tren', p: 'Vehículo' },
      { w: 'Barco', p: 'Vehículo' },
      { w: 'Moto', p: 'Vehículo' },
      { w: 'Camión', p: 'Vehículo' },
      { w: 'Tractor', p: 'Vehículo' },
      { w: 'Cohete', p: 'Espacio' },
      { w: 'Paraguas', p: 'Objeto' },
      { w: 'Reloj', p: 'Objeto' },
      { w: 'Gafas', p: 'Objeto' },
      { w: 'Llave', p: 'Objeto' },
      { w: 'Escalera', p: 'Objeto' },
      { w: 'Linterna', p: 'Luz' },
      { w: 'Almohada', p: 'Dormir' },
      { w: 'Nevera', p: 'Cocina' },
      { w: 'Tijeras', p: 'Herramienta' },
      { w: 'Martillo', p: 'Herramienta' },
      { w: 'Cuchara', p: 'Cubierto' },
      { w: 'Tenedor', p: 'Cubierto' },
      { w: 'Cuchillo', p: 'Cubierto' },
      { w: 'Plato', p: 'Vajilla' },
      { w: 'Vaso', p: 'Vajilla' },
      { w: 'Manzana', p: 'Fruta' },
      { w: 'Sandía', p: 'Fruta' },
      { w: 'Plátano', p: 'Fruta' },
      { w: 'Naranja', p: 'Fruta' },
      { w: 'Fresa', p: 'Fruta' },
      { w: 'Uva', p: 'Fruta' },
      { w: 'Zanahoria', p: 'Verdura' },
      { w: 'Patata', p: 'Verdura' },
      { w: 'Tomate', p: 'Verdura' },
      { w: 'Cebolla', p: 'Verdura' },
      { w: 'Lechuga', p: 'Verdura' },
      { w: 'Queso', p: 'Alimento' },
      { w: 'Pan', p: 'Alimento' },
      { w: 'Huevo', p: 'Alimento' },
      { w: 'Arroz', p: 'Alimento' },
      { w: 'Mantequilla', p: 'Alimento' },
      { w: 'Azúcar', p: 'Alimento' },
      { w: 'Sal', p: 'Condimento' },
      { w: 'Pimienta', p: 'Condimento' },
      { w: 'Leche', p: 'Bebida' },
      { w: 'León', p: 'Animal' },
      { w: 'Elefante', p: 'Animal' },
      { w: 'Jirafa', p: 'Animal' },
      { w: 'Pingüino', p: 'Animal' },
      { w: 'Tiburón', p: 'Animal' },
      { w: 'Delfín', p: 'Animal' },
      { w: 'Cocodrilo', p: 'Animal' },
      { w: 'Serpiente', p: 'Animal' },
      { w: 'Caballo', p: 'Animal' },
      { w: 'Vaca', p: 'Animal' },
      { w: 'Oveja', p: 'Animal' },
      { w: 'Cerdo', p: 'Animal' },
      { w: 'Águila', p: 'Ave' },
      { w: 'Gallina', p: 'Ave' },
      { w: 'Mariposa', p: 'Insecto' },
      { w: 'Abeja', p: 'Insecto' },
      { w: 'Hormiga', p: 'Insecto' },
      { w: 'Araña', p: 'Insecto' },
      { w: 'Nieve', p: 'Clima' },
      { w: 'Tormenta', p: 'Clima' },
      { w: 'Arcoíris', p: 'Cielo' },
      { w: 'Luna', p: 'Cielo' },
      { w: 'Sol', p: 'Cielo' }
    ]
  }
};
