/**
 * Banco de cartas del Tabú.
 * Cada carta: { w: "palabra a adivinar", t: ["cinco", "palabras", "prohibidas"] }
 *
 * Reglas del banco:
 *  - Siempre 5 palabras prohibidas: las cinco que todo el mundo diría primero.
 *  - Las prohibidas nunca repiten la palabra de la carta (sus derivados ya
 *    están prohibidos por las reglas del juego, no hace falta listarlos).
 *  - Cosas conocidas por cualquiera. Si hace falta ser experto, no entra.
 */
const PACKS = {
  cotidiano: {
    id: 'cotidiano',
    name: 'Día a día',
    emoji: '🏠',
    desc: 'Casa, trabajo y cosas de todos los días.',
    cards: [
      { w: 'Despertador', t: ['Reloj', 'Sonar', 'Mañana', 'Levantarse', 'Alarma'] },
      { w: 'Ducha', t: ['Agua', 'Jabón', 'Baño', 'Mojarse', 'Gel'] },
      { w: 'Cepillo de dientes', t: ['Boca', 'Pasta', 'Lavar', 'Higiene', 'Muelas'] },
      { w: 'Café', t: ['Bebida', 'Taza', 'Máquina', 'Desayuno', 'Negro'] },
      { w: 'Desayuno', t: ['Mañana', 'Tostada', 'Café', 'Primera', 'Comida'] },
      { w: 'Ascensor', t: ['Subir', 'Botón', 'Planta', 'Edificio', 'Escaleras'] },
      { w: 'Paraguas', t: ['Lluvia', 'Abrir', 'Mojarse', 'Mango', 'Viento'] },
      { w: 'Llaves', t: ['Puerta', 'Abrir', 'Cerradura', 'Bolsillo', 'Perder'] },
      { w: 'Cartera', t: ['Dinero', 'Bolsillo', 'Tarjetas', 'Cuero', 'Perder'] },
      { w: 'Sofá', t: ['Sentarse', 'Salón', 'Cómodo', 'Tele', 'Cojines'] },
      { w: 'Almohada', t: ['Cama', 'Dormir', 'Cabeza', 'Blanda', 'Funda'] },
      { w: 'Nevera', t: ['Frío', 'Cocina', 'Comida', 'Puerta', 'Conservar'] },
      { w: 'Lavadora', t: ['Ropa', 'Lavar', 'Agua', 'Centrifugado', 'Detergente'] },
      { w: 'Microondas', t: ['Calentar', 'Cocina', 'Minutos', 'Comida', 'Pitido'] },
      { w: 'Aspiradora', t: ['Limpiar', 'Polvo', 'Suelo', 'Ruido', 'Enchufe'] },
      { w: 'Escoba', t: ['Barrer', 'Suelo', 'Palo', 'Cerdas', 'Bruja'] },
      { w: 'Basura', t: ['Bolsa', 'Tirar', 'Cubo', 'Olor', 'Contenedor'] },
      { w: 'Vecino', t: ['Puerta', 'Al lado', 'Piso', 'Ruido', 'Comunidad'] },
      { w: 'Suegra', t: ['Madre', 'Pareja', 'Familia', 'Política', 'Chiste'] },
      { w: 'Cumpleaños', t: ['Tarta', 'Velas', 'Regalo', 'Años', 'Felicidades'] },
      { w: 'Boda', t: ['Novios', 'Iglesia', 'Vestido', 'Anillo', 'Banquete'] },
      { w: 'Divorcio', t: ['Separación', 'Abogado', 'Matrimonio', 'Papeles', 'Ruptura'] },
      { w: 'Siesta', t: ['Dormir', 'Tarde', 'Sofá', 'Corta', 'Descansar'] },
      { w: 'Resaca', t: ['Alcohol', 'Cabeza', 'Dolor', 'Fiesta', 'Mañana'] },
      { w: 'Atasco', t: ['Coche', 'Tráfico', 'Parado', 'Hora punta', 'Claxon'] },
      { w: 'Semáforo', t: ['Rojo', 'Verde', 'Calle', 'Parar', 'Coches'] },
      { w: 'Autobús', t: ['Parada', 'Público', 'Conductor', 'Billete', 'Transporte'] },
      { w: 'Metro', t: ['Subterráneo', 'Andén', 'Vagón', 'Ciudad', 'Billete'] },
      { w: 'Gasolinera', t: ['Coche', 'Repostar', 'Surtidor', 'Combustible', 'Litros'] },
      { w: 'Supermercado', t: ['Compra', 'Carro', 'Caja', 'Productos', 'Pasillos'] },
      { w: 'Cola', t: ['Fila', 'Esperar', 'Gente', 'Turno', 'Caja'] },
      { w: 'Farmacia', t: ['Medicinas', 'Receta', 'Cruz', 'Verde', 'Botica'] },
      { w: 'Peluquería', t: ['Pelo', 'Cortar', 'Tijeras', 'Espejo', 'Cita'] },
      { w: 'Dentista', t: ['Dientes', 'Muela', 'Consulta', 'Torno', 'Miedo'] },
      { w: 'Médico', t: ['Consulta', 'Bata', 'Enfermo', 'Receta', 'Hospital'] },
      { w: 'Hospital', t: ['Enfermo', 'Urgencias', 'Camas', 'Médicos', 'Ingresar'] },
      { w: 'Vacuna', t: ['Pinchazo', 'Brazo', 'Jeringuilla', 'Inmunidad', 'Enfermedad'] },
      { w: 'Fiebre', t: ['Temperatura', 'Termómetro', 'Enfermo', 'Grados', 'Frente'] },
      { w: 'Estornudo', t: ['Nariz', 'Achús', 'Alergia', 'Salud', 'Sonido'] },
      { w: 'Ronquido', t: ['Dormir', 'Ruido', 'Nariz', 'Noche', 'Pareja'] },
      { w: 'Pesadilla', t: ['Sueño', 'Dormir', 'Miedo', 'Noche', 'Despertar'] },
      { w: 'Lunes', t: ['Semana', 'Día', 'Trabajo', 'Empezar', 'Domingo'] },
      { w: 'Vacaciones', t: ['Verano', 'Trabajo', 'Descanso', 'Viaje', 'Días libres'] },
      { w: 'Sueldo', t: ['Dinero', 'Trabajo', 'Mes', 'Nómina', 'Cobrar'] },
      { w: 'Jefe', t: ['Trabajo', 'Mandar', 'Oficina', 'Empleados', 'Despedir'] },
      { w: 'Reunión', t: ['Trabajo', 'Sala', 'Hablar', 'Oficina', 'Aburrida'] },
      { w: 'Currículum', t: ['Trabajo', 'Papel', 'Experiencia', 'Entrevista', 'Enviar'] },
      { w: 'Entrevista', t: ['Preguntas', 'Trabajo', 'Nervios', 'Candidato', 'Cita'] },
      { w: 'Oficina', t: ['Trabajo', 'Mesa', 'Ordenador', 'Jefe', 'Despacho'] },
      { w: 'Impuestos', t: ['Hacienda', 'Pagar', 'Estado', 'Declaración', 'Dinero'] },
      { w: 'Multa', t: ['Pagar', 'Policía', 'Infracción', 'Papel', 'Coche'] },
      { w: 'Hipoteca', t: ['Banco', 'Casa', 'Préstamo', 'Años', 'Pagar'] },
      { w: 'Alquiler', t: ['Piso', 'Mensual', 'Casero', 'Pagar', 'Contrato'] },
      { w: 'Mudanza', t: ['Cajas', 'Casa', 'Camión', 'Cambiar', 'Muebles'] },
      { w: 'Escalera', t: ['Subir', 'Peldaños', 'Bajar', 'Piso', 'Barandilla'] },
      { w: 'Espejo', t: ['Reflejo', 'Verse', 'Baño', 'Cristal', 'Imagen'] },
      { w: 'Toalla', t: ['Secarse', 'Baño', 'Playa', 'Tela', 'Mojado'] },
      { w: 'Cortina', t: ['Ventana', 'Tela', 'Correr', 'Luz', 'Colgar'] },
      { w: 'Alfombra', t: ['Suelo', 'Pisar', 'Salón', 'Tela', 'Polvo'] },
      { w: 'Bombilla', t: ['Luz', 'Enchufar', 'Fundida', 'Techo', 'Encender'] },
      { w: 'Enchufe', t: ['Corriente', 'Pared', 'Cable', 'Electricidad', 'Conectar'] },
      { w: 'Manta', t: ['Cama', 'Calor', 'Taparse', 'Sofá', 'Invierno'] },
      { w: 'Pijama', t: ['Dormir', 'Ropa', 'Cama', 'Noche', 'Cómodo'] },
      { w: 'Calcetines', t: ['Pies', 'Zapatos', 'Par', 'Ropa', 'Agujero'] },
      { w: 'Gafas', t: ['Ver', 'Ojos', 'Cristales', 'Montura', 'Vista'] },
      { w: 'Reloj', t: ['Hora', 'Muñeca', 'Tiempo', 'Agujas', 'Pulsera'] },
      { w: 'Bufanda', t: ['Cuello', 'Frío', 'Invierno', 'Lana', 'Abrigar'] },
      { w: 'Chándal', t: ['Ropa', 'Deporte', 'Cómodo', 'Chaqueta', 'Pantalón'] },
      { w: 'Bañador', t: ['Playa', 'Piscina', 'Verano', 'Ropa', 'Nadar'] },
      { w: 'Maquillaje', t: ['Cara', 'Pintar', 'Base', 'Espejo', 'Belleza'] },
      { w: 'Perfume', t: ['Oler', 'Frasco', 'Aroma', 'Echarse', 'Colonia'] },
      { w: 'Barba', t: ['Cara', 'Pelo', 'Afeitar', 'Hombre', 'Mentón'] },
      { w: 'Tatuaje', t: ['Piel', 'Tinta', 'Aguja', 'Dibujo', 'Permanente'] },
      { w: 'Cicatriz', t: ['Piel', 'Herida', 'Marca', 'Curar', 'Señal'] },
      { w: 'Cosquillas', t: ['Reír', 'Tocar', 'Pies', 'Aguantar', 'Sensación'] },
      { w: 'Bostezo', t: ['Sueño', 'Boca', 'Abrir', 'Cansancio', 'Contagio'] },
      { w: 'Hipo', t: ['Sonido', 'Susto', 'Beber', 'Diafragma', 'Parar'] },
      { w: 'Propina', t: ['Camarero', 'Dinero', 'Dejar', 'Mesa', 'Servicio'] },
      { w: 'Recibo', t: ['Papel', 'Compra', 'Ticket', 'Pagar', 'Guardar'] },
      { w: 'Contraseña', t: ['Secreta', 'Olvidar', 'Cuenta', 'Letras', 'Entrar'] }
    ]
  },

  comida: {
    id: 'comida',
    name: 'Comida y bebida',
    emoji: '🍔',
    desc: 'Platos, ingredientes y cosas de beber.',
    cards: [
      { w: 'Paella', t: ['Arroz', 'Valencia', 'Domingo', 'Azafrán', 'Sartén'] },
      { w: 'Tortilla de patatas', t: ['Huevo', 'Cebolla', 'Sartén', 'Vuelta', 'Pincho'] },
      { w: 'Gazpacho', t: ['Tomate', 'Frío', 'Verano', 'Beber', 'Sopa'] },
      { w: 'Jamón', t: ['Cerdo', 'Pata', 'Cortar', 'Ibérico', 'Loncha'] },
      { w: 'Chorizo', t: ['Embutido', 'Cerdo', 'Rojo', 'Pimentón', 'Bocadillo'] },
      { w: 'Queso', t: ['Leche', 'Curado', 'Ratón', 'Amarillo', 'Loncha'] },
      { w: 'Aceite de oliva', t: ['Verde', 'Botella', 'Freír', 'Ensalada', 'Aceituna'] },
      { w: 'Pan', t: ['Barra', 'Harina', 'Horno', 'Miga', 'Duro'] },
      { w: 'Bocadillo', t: ['Pan', 'Relleno', 'Merienda', 'Jamón', 'Morder'] },
      { w: 'Churros', t: ['Chocolate', 'Freír', 'Desayuno', 'Azúcar', 'Feria'] },
      { w: 'Croqueta', t: ['Bechamel', 'Freír', 'Rebozada', 'Tapa', 'Abuela'] },
      { w: 'Empanada', t: ['Masa', 'Relleno', 'Gallega', 'Atún', 'Horno'] },
      { w: 'Sushi', t: ['Japón', 'Arroz', 'Pescado', 'Crudo', 'Palillos'] },
      { w: 'Pizza', t: ['Italia', 'Queso', 'Redonda', 'Porción', 'Horno'] },
      { w: 'Hamburguesa', t: ['Carne', 'Pan', 'Queso', 'Rápida', 'Kétchup'] },
      { w: 'Kebab', t: ['Carne', 'Turco', 'Pan', 'Salsa', 'Madrugada'] },
      { w: 'Espagueti', t: ['Pasta', 'Largo', 'Tomate', 'Italia', 'Tenedor'] },
      { w: 'Lasaña', t: ['Pasta', 'Capas', 'Horno', 'Bechamel', 'Italia'] },
      { w: 'Arroz', t: ['Blanco', 'Grano', 'Paella', 'China', 'Hervir'] },
      { w: 'Sopa', t: ['Caliente', 'Cuchara', 'Plato', 'Caldo', 'Fideos'] },
      { w: 'Ensalada', t: ['Lechuga', 'Tomate', 'Verde', 'Dieta', 'Aliñar'] },
      { w: 'Lentejas', t: ['Legumbre', 'Cuchara', 'Puchero', 'Hierro', 'Abuela'] },
      { w: 'Garbanzos', t: ['Legumbre', 'Cocido', 'Hummus', 'Redondos', 'Puchero'] },
      { w: 'Huevo frito', t: ['Yema', 'Sartén', 'Aceite', 'Puntilla', 'Patatas'] },
      { w: 'Bacon', t: ['Cerdo', 'Tiras', 'Desayuno', 'Crujiente', 'Sartén'] },
      { w: 'Pollo asado', t: ['Horno', 'Ave', 'Domingo', 'Muslo', 'Piel'] },
      { w: 'Chuletón', t: ['Carne', 'Vaca', 'Parrilla', 'Hueso', 'Punto'] },
      { w: 'Pescado', t: ['Mar', 'Espinas', 'Escamas', 'Freír', 'Lonja'] },
      { w: 'Salmón', t: ['Rosa', 'Pescado', 'Ahumado', 'Noruega', 'Río'] },
      { w: 'Marisco', t: ['Mar', 'Navidad', 'Caro', 'Gambas', 'Concha'] },
      { w: 'Gambas', t: ['Ajillo', 'Pelar', 'Rosa', 'Mar', 'Cola'] },
      { w: 'Pulpo', t: ['Gallega', 'Tentáculos', 'Ventosas', 'Pimentón', 'Mar'] },
      { w: 'Calamares', t: ['Rabas', 'Anillas', 'Bocadillo', 'Freír', 'Tinta'] },
      { w: 'Anchoa', t: ['Salada', 'Lata', 'Pequeña', 'Pescado', 'Aperitivo'] },
      { w: 'Aceituna', t: ['Verde', 'Hueso', 'Aperitivo', 'Rellena', 'Olivo'] },
      { w: 'Patatas fritas', t: ['Bolsa', 'Bastones', 'Aceite', 'Sal', 'Crujiente'] },
      { w: 'Palomitas', t: ['Cine', 'Maíz', 'Explotar', 'Cubo', 'Sal'] },
      { w: 'Chicle', t: ['Masticar', 'Boca', 'Globo', 'Menta', 'Pegajoso'] },
      { w: 'Chocolate', t: ['Cacao', 'Tableta', 'Dulce', 'Negro', 'Onza'] },
      { w: 'Helado', t: ['Frío', 'Verano', 'Cucurucho', 'Bolas', 'Derretir'] },
      { w: 'Tarta', t: ['Cumpleaños', 'Velas', 'Porción', 'Nata', 'Horno'] },
      { w: 'Flan', t: ['Caramelo', 'Huevo', 'Postre', 'Temblar', 'Molde'] },
      { w: 'Natillas', t: ['Postre', 'Galleta', 'Canela', 'Cuchara', 'Vainilla'] },
      { w: 'Yogur', t: ['Leche', 'Postre', 'Tarrina', 'Fresa', 'Caducidad'] },
      { w: 'Miel', t: ['Abeja', 'Dulce', 'Pegajosa', 'Tarro', 'Oso'] },
      { w: 'Mermelada', t: ['Fruta', 'Tostada', 'Tarro', 'Dulce', 'Untar'] },
      { w: 'Mantequilla', t: ['Leche', 'Tostada', 'Untar', 'Pastilla', 'Grasa'] },
      { w: 'Sal', t: ['Blanca', 'Sabor', 'Mar', 'Grano', 'Soso'] },
      { w: 'Azúcar', t: ['Dulce', 'Blanco', 'Café', 'Cucharada', 'Terrón'] },
      { w: 'Pimienta', t: ['Negra', 'Molinillo', 'Picante', 'Sal', 'Especia'] },
      { w: 'Kétchup', t: ['Tomate', 'Rojo', 'Salsa', 'Bote', 'Patatas'] },
      { w: 'Mayonesa', t: ['Blanca', 'Salsa', 'Huevo', 'Aceite', 'Ensaladilla'] },
      { w: 'Café con leche', t: ['Bar', 'Taza', 'Desayuno', 'Cafeína', 'Caliente'] },
      { w: 'Zumo de naranja', t: ['Exprimir', 'Fruta', 'Vitamina', 'Desayuno', 'Vaso'] },
      { w: 'Cerveza', t: ['Caña', 'Bar', 'Espuma', 'Rubia', 'Fría'] },
      { w: 'Vino tinto', t: ['Uva', 'Copa', 'Botella', 'Rioja', 'Alcohol'] },
      { w: 'Sangría', t: ['Vino', 'Fruta', 'Jarra', 'Verano', 'Turistas'] },
      { w: 'Champán', t: ['Burbujas', 'Brindis', 'Corcho', 'Nochevieja', 'Copa'] },
      { w: 'Batido', t: ['Leche', 'Fresa', 'Vaso', 'Pajita', 'Espeso'] },
      { w: 'Agua con gas', t: ['Burbujas', 'Botella', 'Beber', 'Sed', 'Sin sabor'] }
    ]
  },
  pop: {
    id: 'pop',
    name: 'Cine, música y famosos',
    emoji: '🎬',
    desc: 'Pelis, series, canciones y caras conocidas.',
    cards: [
      { w: 'Titanic', t: ['Barco', 'Iceberg', 'Rose', 'Hundir', 'DiCaprio'] },
      { w: 'Star Wars', t: ['Galaxia', 'Espada láser', 'Vader', 'Fuerza', 'Jedi'] },
      { w: 'Harry Potter', t: ['Magia', 'Hogwarts', 'Gafas', 'Varita', 'Cicatriz'] },
      { w: 'El Señor de los Anillos', t: ['Anillo', 'Hobbit', 'Frodo', 'Tolkien', 'Mordor'] },
      { w: 'Jurassic Park', t: ['Dinosaurios', 'Parque', 'Isla', 'ADN', 'Spielberg'] },
      { w: 'El Rey León', t: ['Simba', 'Disney', 'Sabana', 'Melena', 'Hakuna matata'] },
      { w: 'Frozen', t: ['Elsa', 'Hielo', 'Disney', 'Hermanas', 'Muñeco'] },
      { w: 'Toy Story', t: ['Juguetes', 'Woody', 'Buzz', 'Pixar', 'Vaquero'] },
      { w: 'Shrek', t: ['Ogro', 'Verde', 'Burro', 'Pantano', 'Fiona'] },
      { w: 'Los Simpson', t: ['Amarillos', 'Homer', 'Springfield', 'Dibujos', 'Bart'] },
      { w: 'Friends', t: ['Serie', 'Sofá', 'Cafetería', 'Seis', 'Nueva York'] },
      { w: 'Juego de Tronos', t: ['Trono', 'Dragones', 'Invierno', 'Poniente', 'Serie'] },
      { w: 'Stranger Things', t: ['Netflix', 'Ochenta', 'Niños', 'Monstruo', 'Bicicletas'] },
      { w: 'La Casa de Papel', t: ['Atraco', 'Máscara', 'Rojo', 'Profesor', 'Ciudades'] },
      { w: 'Breaking Bad', t: ['Profesor', 'Química', 'Droga', 'Caravana', 'Calvo'] },
      { w: 'Netflix', t: ['Series', 'Plataforma', 'Suscripción', 'Rojo', 'Ver'] },
      { w: 'Óscar', t: ['Premio', 'Estatuilla', 'Cine', 'Hollywood', 'Gala'] },
      { w: 'Alfombra roja', t: ['Famosos', 'Premios', 'Fotos', 'Vestidos', 'Desfilar'] },
      { w: 'Paparazzi', t: ['Fotos', 'Famosos', 'Perseguir', 'Revista', 'Cámara'] },
      { w: 'Selfie', t: ['Foto', 'Móvil', 'Uno mismo', 'Palo', 'Instagram'] },
      { w: 'Instagram', t: ['Fotos', 'Red social', 'Filtros', 'Seguidores', 'Stories'] },
      { w: 'TikTok', t: ['Vídeos', 'Bailes', 'App', 'Cortos', 'Jóvenes'] },
      { w: 'Reguetón', t: ['Música', 'Perreo', 'Latino', 'Discoteca', 'Ritmo'] },
      { w: 'Flamenco', t: ['Baile', 'Guitarra', 'Andalucía', 'Palmas', 'Bata de cola'] },
      { w: 'Rock', t: ['Guitarra', 'Música', 'Batería', 'Concierto', 'Melena'] },
      { w: 'Rap', t: ['Rima', 'Música', 'Hablar', 'Calle', 'Batalla'] },
      { w: 'Karaoke', t: ['Cantar', 'Micrófono', 'Letra', 'Pantalla', 'Desafinar'] },
      { w: 'Concierto', t: ['Música', 'Directo', 'Escenario', 'Entradas', 'Público'] },
      { w: 'Festival', t: ['Verano', 'Música', 'Pulsera', 'Camping', 'Escenarios'] },
      { w: 'Eurovisión', t: ['Canción', 'Países', 'Puntos', 'Mayo', 'Televisión'] },
      { w: 'Beyoncé', t: ['Cantante', 'Estados Unidos', 'Destiny', 'Jay-Z', 'Diva'] },
      { w: 'Michael Jackson', t: ['Pop', 'Guante', 'Moonwalk', 'Thriller', 'Rey'] },
      { w: 'Elvis', t: ['Rock', 'Tupé', 'Memphis', 'Cadera', 'Presley'] },
      { w: 'Los Beatles', t: ['Liverpool', 'Cuatro', 'Lennon', 'Paso de cebra', 'Banda'] },
      { w: 'Freddie Mercury', t: ['Queen', 'Bigote', 'Cantante', 'Bohemian', 'Wembley'] },
      { w: 'Rosalía', t: ['Cantante', 'Catalana', 'Flamenco', 'Motomami', 'Uñas'] },
      { w: 'Bad Bunny', t: ['Reguetón', 'Puerto Rico', 'Conejo', 'Gafas', 'Cantante'] },
      { w: 'Shakira', t: ['Colombia', 'Caderas', 'Cantante', 'Rubia', 'Loba'] },
      { w: 'Madonna', t: ['Cantante', 'Pop', 'Rubia', 'Ochenta', 'Reina'] },
      { w: 'Lady Gaga', t: ['Cantante', 'Extravagante', 'Poker Face', 'Carne', 'Pop'] },
      { w: 'Messi', t: ['Fútbol', 'Argentina', 'Barcelona', 'Pulga', 'Balón de Oro'] },
      { w: 'Cristiano Ronaldo', t: ['Fútbol', 'Portugal', 'Madrid', 'Siuu', 'Abdominales'] },
      { w: 'Rafa Nadal', t: ['Tenis', 'Mallorca', 'Roland Garros', 'Zurdo', 'Raqueta'] },
      { w: 'Superman', t: ['Capa', 'Volar', 'Kriptonita', 'Azul', 'Cabina'] },
      { w: 'Batman', t: ['Murciélago', 'Gotham', 'Negro', 'Millonario', 'Cueva'] },
      { w: 'Spiderman', t: ['Araña', 'Telaraña', 'Trepar', 'Máscara', 'Rojo'] },
      { w: 'Iron Man', t: ['Armadura', 'Stark', 'Hierro', 'Marvel', 'Millonario'] },
      { w: 'Godzilla', t: ['Monstruo', 'Japón', 'Gigante', 'Ciudad', 'Lagarto'] },
      { w: 'King Kong', t: ['Gorila', 'Gigante', 'Rascacielos', 'Isla', 'Trepar'] },
      { w: 'Drácula', t: ['Vampiro', 'Sangre', 'Colmillos', 'Capa', 'Transilvania'] },
      { w: 'Frankenstein', t: ['Monstruo', 'Tornillos', 'Doctor', 'Rayo', 'Verde'] },
      { w: 'Zombi', t: ['Muerto', 'Andar', 'Cerebro', 'Apocalipsis', 'Contagio'] },
      { w: 'Extraterrestre', t: ['Espacio', 'Ovni', 'Verde', 'Marte', 'Antenas'] },
      { w: 'Pirata', t: ['Barco', 'Parche', 'Tesoro', 'Loro', 'Garfio'] },
      { w: 'Vaquero', t: ['Sombrero', 'Caballo', 'Oeste', 'Revólver', 'Lazo'] },
      { w: 'Superhéroe', t: ['Capa', 'Poderes', 'Salvar', 'Cómic', 'Máscara'] },
      { w: 'Videojuego', t: ['Consola', 'Mando', 'Pantalla', 'Niveles', 'Jugar'] },
      { w: 'Mario Bros', t: ['Fontanero', 'Bigote', 'Nintendo', 'Setas', 'Rojo'] },
      { w: 'Payaso', t: ['Circo', 'Nariz', 'Reír', 'Maquillaje', 'Zapatos'] },
      { w: 'Mago', t: ['Truco', 'Chistera', 'Conejo', 'Varita', 'Cartas'] }
    ]
  },

  natura: {
    id: 'natura',
    name: 'Animales y naturaleza',
    emoji: '🐾',
    desc: 'Bichos, plantas y paisajes.',
    cards: [
      { w: 'Perro', t: ['Ladrar', 'Mascota', 'Hueso', 'Correa', 'Fiel'] },
      { w: 'Gato', t: ['Maullar', 'Mascota', 'Ratón', 'Bigotes', 'Arañar'] },
      { w: 'Elefante', t: ['Trompa', 'Grande', 'Orejas', 'Colmillos', 'África'] },
      { w: 'Jirafa', t: ['Cuello', 'Alta', 'Manchas', 'Sabana', 'Hojas'] },
      { w: 'León', t: ['Melena', 'Rey', 'Rugido', 'Selva', 'Sabana'] },
      { w: 'Tigre', t: ['Rayas', 'Naranja', 'Felino', 'Asia', 'Cazador'] },
      { w: 'Oso', t: ['Miel', 'Invierno', 'Bosque', 'Peludo', 'Hibernar'] },
      { w: 'Lobo', t: ['Aullar', 'Manada', 'Luna', 'Caperucita', 'Bosque'] },
      { w: 'Zorro', t: ['Astuto', 'Rojo', 'Cola', 'Bosque', 'Gallinero'] },
      { w: 'Conejo', t: ['Orejas', 'Zanahoria', 'Saltar', 'Madriguera', 'Pascua'] },
      { w: 'Ratón', t: ['Queso', 'Pequeño', 'Cola', 'Trampa', 'Gato'] },
      { w: 'Ardilla', t: ['Nueces', 'Árbol', 'Cola', 'Saltar', 'Parque'] },
      { w: 'Caballo', t: ['Montar', 'Galope', 'Silla', 'Herradura', 'Relinchar'] },
      { w: 'Vaca', t: ['Leche', 'Muu', 'Establo', 'Manchas', 'Hierba'] },
      { w: 'Cerdo', t: ['Barro', 'Rosa', 'Granja', 'Jamón', 'Gruñir'] },
      { w: 'Oveja', t: ['Lana', 'Rebaño', 'Pastor', 'Contar', 'Balar'] },
      { w: 'Cabra', t: ['Montaña', 'Cuernos', 'Queso', 'Barba', 'Trepar'] },
      { w: 'Gallina', t: ['Huevos', 'Corral', 'Plumas', 'Cacarear', 'Pollo'] },
      { w: 'Pato', t: ['Estanque', 'Cuac', 'Nadar', 'Pico', 'Plumas'] },
      { w: 'Pingüino', t: ['Frío', 'Hielo', 'Blanco y negro', 'Nadar', 'Antártida'] },
      { w: 'Águila', t: ['Volar', 'Rapaz', 'Garras', 'Vista', 'Montaña'] },
      { w: 'Búho', t: ['Noche', 'Ojos', 'Árbol', 'Sabio', 'Ulular'] },
      { w: 'Loro', t: ['Hablar', 'Colores', 'Jaula', 'Pirata', 'Repetir'] },
      { w: 'Cigüeña', t: ['Nido', 'Campanario', 'Bebés', 'Pico', 'Patas'] },
      { w: 'Murciélago', t: ['Noche', 'Cueva', 'Volar', 'Cabeza abajo', 'Batman'] },
      { w: 'Serpiente', t: ['Reptar', 'Veneno', 'Lengua', 'Cascabel', 'Escamas'] },
      { w: 'Cocodrilo', t: ['Río', 'Dientes', 'Reptil', 'Lágrimas', 'Mandíbula'] },
      { w: 'Tortuga', t: ['Caparazón', 'Lenta', 'Liebre', 'Reptil', 'Playa'] },
      { w: 'Rana', t: ['Croar', 'Charca', 'Verde', 'Saltar', 'Príncipe'] },
      { w: 'Camaleón', t: ['Color', 'Cambiar', 'Lengua', 'Ojos', 'Rama'] },
      { w: 'Tiburón', t: ['Dientes', 'Mar', 'Aleta', 'Miedo', 'Sangre'] },
      { w: 'Ballena', t: ['Mar', 'Grande', 'Chorro', 'Azul', 'Plancton'] },
      { w: 'Delfín', t: ['Mar', 'Listo', 'Saltar', 'Sonido', 'Acuario'] },
      { w: 'Medusa', t: ['Mar', 'Picar', 'Transparente', 'Tentáculos', 'Playa'] },
      { w: 'Cangrejo', t: ['Pinzas', 'Playa', 'Lado', 'Caparazón', 'Marisco'] },
      { w: 'Caracol', t: ['Lento', 'Concha', 'Baba', 'Lluvia', 'Antenas'] },
      { w: 'Abeja', t: ['Miel', 'Picar', 'Colmena', 'Zumbar', 'Flores'] },
      { w: 'Hormiga', t: ['Pequeña', 'Fila', 'Hormiguero', 'Trabajadora', 'Azúcar'] },
      { w: 'Mariposa', t: ['Alas', 'Oruga', 'Colores', 'Flores', 'Volar'] },
      { w: 'Araña', t: ['Telaraña', 'Ocho', 'Patas', 'Miedo', 'Rincón'] },
      { w: 'Mosquito', t: ['Picar', 'Zumbido', 'Verano', 'Sangre', 'Noche'] },
      { w: 'Mono', t: ['Plátano', 'Árbol', 'Cola', 'Imitar', 'Selva'] },
      { w: 'Camello', t: ['Joroba', 'Desierto', 'Agua', 'Caravana', 'Arena'] },
      { w: 'Canguro', t: ['Australia', 'Bolsa', 'Saltar', 'Cría', 'Cola'] },
      { w: 'Koala', t: ['Australia', 'Eucalipto', 'Dormir', 'Árbol', 'Peluche'] },
      { w: 'Panda', t: ['China', 'Bambú', 'Blanco y negro', 'Oso', 'Ojeras'] },
      { w: 'Rinoceronte', t: ['Cuerno', 'Gris', 'África', 'Carga', 'Piel dura'] },
      { w: 'Hipopótamo', t: ['Río', 'Gordo', 'África', 'Boca', 'Barro'] },
      { w: 'Cebra', t: ['Rayas', 'Sabana', 'Blanco y negro', 'Paso', 'Caballo'] },
      { w: 'Erizo', t: ['Púas', 'Bolita', 'Pequeño', 'Bosque', 'Pinchar'] },
      { w: 'Toro', t: ['Cuernos', 'Plaza', 'Rojo', 'Embestir', 'Bravo'] },
      { w: 'Ciervo', t: ['Cuernos', 'Bosque', 'Bambi', 'Correr', 'Berrea'] },
      { w: 'Árbol', t: ['Tronco', 'Hojas', 'Ramas', 'Sombra', 'Bosque'] },
      { w: 'Bosque', t: ['Árboles', 'Verde', 'Perderse', 'Setas', 'Senderos'] },
      { w: 'Montaña', t: ['Alta', 'Cima', 'Escalar', 'Nieve', 'Valle'] },
      { w: 'Río', t: ['Agua', 'Corriente', 'Puente', 'Cauce', 'Desembocar'] },
      { w: 'Volcán', t: ['Lava', 'Erupción', 'Cráter', 'Ceniza', 'Montaña'] },
      { w: 'Desierto', t: ['Arena', 'Calor', 'Sed', 'Dunas', 'Oasis'] },
      { w: 'Nieve', t: ['Blanca', 'Frío', 'Copos', 'Invierno', 'Muñeco'] },
      { w: 'Arcoíris', t: ['Colores', 'Lluvia', 'Cielo', 'Arco', 'Siete'] },
      { w: 'Tormenta', t: ['Rayos', 'Truenos', 'Lluvia', 'Nubes', 'Viento'] },
      { w: 'Niebla', t: ['No ver', 'Blanca', 'Carretera', 'Húmeda', 'Mañana'] },
      { w: 'Terremoto', t: ['Temblar', 'Tierra', 'Escala', 'Derrumbe', 'Placas'] },
      { w: 'Luna', t: ['Noche', 'Cielo', 'Llena', 'Astronauta', 'Cráteres'] },
      { w: 'Estrella', t: ['Cielo', 'Brillar', 'Noche', 'Deseo', 'Fugaz'] },
      { w: 'Cascada', t: ['Agua', 'Caer', 'Río', 'Salto', 'Ruido'] },
      { w: 'Cueva', t: ['Oscuro', 'Piedra', 'Murciélagos', 'Entrada', 'Eco'] }
    ]
  },
  deporte: {
    id: 'deporte',
    name: 'Deporte y ocio',
    emoji: '⚽',
    desc: 'Deportes, juegos y gimnasio.',
    cards: [
      { w: 'Fútbol', t: ['Balón', 'Gol', 'Once', 'Portería', 'Campo'] },
      { w: 'Baloncesto', t: ['Canasta', 'Bote', 'Altos', 'Triple', 'Aro'] },
      { w: 'Tenis', t: ['Raqueta', 'Red', 'Pelota', 'Set', 'Pista'] },
      { w: 'Golf', t: ['Palo', 'Hoyo', 'Bola', 'Campo', 'Carrito'] },
      { w: 'Natación', t: ['Piscina', 'Agua', 'Calle', 'Gorro', 'Estilos'] },
      { w: 'Ciclismo', t: ['Bicicleta', 'Pedales', 'Tour', 'Maillot', 'Etapa'] },
      { w: 'Boxeo', t: ['Guantes', 'Ring', 'Puñetazo', 'Asaltos', 'Nocaut'] },
      { w: 'Kárate', t: ['Cinturón', 'Japón', 'Patada', 'Kimono', 'Artes marciales'] },
      { w: 'Yoga', t: ['Esterilla', 'Posturas', 'Respirar', 'Relajarse', 'Namasté'] },
      { w: 'Maratón', t: ['Correr', 'Kilómetros', 'Meta', 'Dorsal', 'Resistencia'] },
      { w: 'Esquí', t: ['Nieve', 'Montaña', 'Tablas', 'Bastones', 'Pista'] },
      { w: 'Surf', t: ['Ola', 'Tabla', 'Mar', 'Playa', 'Equilibrio'] },
      { w: 'Buceo', t: ['Agua', 'Botella', 'Gafas', 'Fondo', 'Aletas'] },
      { w: 'Escalada', t: ['Pared', 'Cuerda', 'Roca', 'Presas', 'Arnés'] },
      { w: 'Patinaje', t: ['Ruedas', 'Hielo', 'Deslizar', 'Caerse', 'Pista'] },
      { w: 'Ajedrez', t: ['Tablero', 'Rey', 'Jaque', 'Piezas', 'Blancas'] },
      { w: 'Póker', t: ['Cartas', 'Apostar', 'Fichas', 'Farol', 'Casino'] },
      { w: 'Parchís', t: ['Fichas', 'Dado', 'Casillas', 'Comer', 'Colores'] },
      { w: 'Dominó', t: ['Fichas', 'Puntos', 'Bar', 'Cadena', 'Mesa'] },
      { w: 'Dardos', t: ['Diana', 'Tirar', 'Punta', 'Bar', 'Centro'] },
      { w: 'Bolos', t: ['Bola', 'Pleno', 'Pista', 'Tirar', 'Zapatos'] },
      { w: 'Billar', t: ['Taco', 'Bolas', 'Mesa', 'Tronera', 'Verde'] },
      { w: 'Petanca', t: ['Bolas', 'Boliche', 'Parque', 'Arena', 'Jubilados'] },
      { w: 'Pádel', t: ['Pala', 'Cristal', 'Pista', 'Parejas', 'Red'] },
      { w: 'Voleibol', t: ['Red', 'Balón', 'Playa', 'Saque', 'Remate'] },
      { w: 'Rugby', t: ['Ovalado', 'Placaje', 'Ensayo', 'Melé', 'Bruto'] },
      { w: 'Béisbol', t: ['Bate', 'Estados Unidos', 'Guante', 'Bases', 'Lanzador'] },
      { w: 'Balonmano', t: ['Portería', 'Mano', 'Balón', 'Pista', 'Siete'] },
      { w: 'Gimnasia', t: ['Cinta', 'Salto', 'Barra', 'Flexible', 'Rítmica'] },
      { w: 'Atletismo', t: ['Pista', 'Correr', 'Saltar', 'Vallas', 'Jabalina'] },
      { w: 'Portero', t: ['Guantes', 'Parar', 'Portería', 'Penalti', 'Equipo'] },
      { w: 'Árbitro', t: ['Silbato', 'Tarjeta', 'Pitar', 'Campo', 'Decisión'] },
      { w: 'Penalti', t: ['Portería', 'Once metros', 'Falta', 'Tirar', 'Área'] },
      { w: 'Gol', t: ['Red', 'Marcar', 'Celebrar', 'Portería', 'Fútbol'] },
      { w: 'Estadio', t: ['Campo', 'Gradas', 'Público', 'Partido', 'Césped'] },
      { w: 'Grada', t: ['Asientos', 'Público', 'Estadio', 'Animar', 'Bufanda'] },
      { w: 'Camiseta', t: ['Ropa', 'Número', 'Equipo', 'Manga', 'Escudo'] },
      { w: 'Medalla', t: ['Oro', 'Cuello', 'Premio', 'Podio', 'Colgar'] },
      { w: 'Podio', t: ['Tres', 'Escalones', 'Ganadores', 'Subir', 'Ceremonia'] },
      { w: 'Olimpiadas', t: ['Aros', 'Cuatro años', 'Antorcha', 'Países', 'Medallas'] },
      { w: 'Mundial', t: ['Selecciones', 'Copa', 'Cuatro años', 'Fútbol', 'Países'] },
      { w: 'Entrenador', t: ['Banquillo', 'Equipo', 'Táctica', 'Gritar', 'Pizarra'] },
      { w: 'Vestuario', t: ['Taquillas', 'Ducha', 'Equipo', 'Cambiarse', 'Banco'] },
      { w: 'Calentamiento', t: ['Antes', 'Estirar', 'Músculos', 'Trotar', 'Lesión'] },
      { w: 'Agujetas', t: ['Dolor', 'Músculos', 'Día siguiente', 'Ejercicio', 'Escaleras'] },
      { w: 'Gimnasio', t: ['Pesas', 'Cuota', 'Máquinas', 'Espejo', 'Sudor'] },
      { w: 'Mancuerna', t: ['Peso', 'Bíceps', 'Levantar', 'Hierro', 'Gimnasio'] },
      { w: 'Cinta de correr', t: ['Máquina', 'Gimnasio', 'Andar', 'Velocidad', 'Sudar'] },
      { w: 'Silbato', t: ['Pitar', 'Boca', 'Árbitro', 'Sonido', 'Colgado'] },
      { w: 'Trofeo', t: ['Copa', 'Ganar', 'Vitrina', 'Levantar', 'Dorado'] }
    ]
  },

  lugares: {
    id: 'lugares',
    name: 'Lugares y viajes',
    emoji: '🌍',
    desc: 'Ciudades, monumentos y cosas de viajar.',
    cards: [
      { w: 'París', t: ['Francia', 'Torre', 'Amor', 'Sena', 'Capital'] },
      { w: 'Torre Eiffel', t: ['París', 'Hierro', 'Alta', 'Francia', 'Monumento'] },
      { w: 'Roma', t: ['Italia', 'Papa', 'Coliseo', 'Capital', 'Imperio'] },
      { w: 'Coliseo', t: ['Roma', 'Gladiadores', 'Anfiteatro', 'Ruinas', 'Italia'] },
      { w: 'Venecia', t: ['Canales', 'Góndola', 'Italia', 'Agua', 'Máscaras'] },
      { w: 'Londres', t: ['Inglaterra', 'Reina', 'Autobús rojo', 'Támesis', 'Capital'] },
      { w: 'Big Ben', t: ['Londres', 'Reloj', 'Torre', 'Campana', 'Inglaterra'] },
      { w: 'Nueva York', t: ['Rascacielos', 'Manzana', 'Estados Unidos', 'Times Square', 'Taxis'] },
      { w: 'Estatua de la Libertad', t: ['Nueva York', 'Antorcha', 'Corona', 'Verde', 'Isla'] },
      { w: 'Egipto', t: ['Pirámides', 'Nilo', 'Faraón', 'Desierto', 'Momias'] },
      { w: 'Pirámides', t: ['Egipto', 'Triángulo', 'Faraón', 'Piedra', 'Desierto'] },
      { w: 'Muralla China', t: ['Larga', 'Piedra', 'Asia', 'Defensa', 'Espacio'] },
      { w: 'Machu Picchu', t: ['Perú', 'Incas', 'Montaña', 'Ruinas', 'Andes'] },
      { w: 'Taj Mahal', t: ['India', 'Blanco', 'Mármol', 'Amor', 'Cúpula'] },
      { w: 'Amazonas', t: ['Selva', 'Río', 'Brasil', 'Pulmón', 'Tribus'] },
      { w: 'Sáhara', t: ['Desierto', 'Arena', 'África', 'Dunas', 'Calor'] },
      { w: 'Everest', t: ['Montaña', 'Alta', 'Nepal', 'Escalar', 'Oxígeno'] },
      { w: 'Polo Norte', t: ['Hielo', 'Frío', 'Osos', 'Papá Noel', 'Brújula'] },
      { w: 'Hawái', t: ['Islas', 'Collar', 'Surf', 'Volcán', 'Pacífico'] },
      { w: 'Ibiza', t: ['Isla', 'Fiesta', 'Discotecas', 'Baleares', 'Playas'] },
      { w: 'Madrid', t: ['Capital', 'España', 'Sol', 'Oso', 'Centro'] },
      { w: 'Barcelona', t: ['Cataluña', 'Gaudí', 'Ramblas', 'Mar', 'Ciudad'] },
      { w: 'Sevilla', t: ['Andalucía', 'Feria', 'Giralda', 'Calor', 'Semana Santa'] },
      { w: 'Sagrada Familia', t: ['Barcelona', 'Gaudí', 'Obras', 'Torres', 'Iglesia'] },
      { w: 'Camino de Santiago', t: ['Peregrino', 'Concha', 'Andar', 'Galicia', 'Mochila'] },
      { w: 'Playa', t: ['Arena', 'Mar', 'Sombrilla', 'Verano', 'Toalla'] },
      { w: 'Hotel', t: ['Habitación', 'Recepción', 'Estrellas', 'Noche', 'Llave'] },
      { w: 'Camping', t: ['Tienda', 'Saco', 'Naturaleza', 'Parcela', 'Hoguera'] },
      { w: 'Aeropuerto', t: ['Aviones', 'Maletas', 'Puerta', 'Pista', 'Embarque'] },
      { w: 'Avión', t: ['Volar', 'Alas', 'Piloto', 'Nubes', 'Billete'] },
      { w: 'Maleta', t: ['Ruedas', 'Ropa', 'Viaje', 'Cerrar', 'Facturar'] },
      { w: 'Pasaporte', t: ['Viaje', 'Sellos', 'Foto', 'Frontera', 'Documento'] },
      { w: 'Crucero', t: ['Barco', 'Camarote', 'Puertos', 'Buffet', 'Mar'] },
      { w: 'Tren', t: ['Vías', 'Estación', 'Vagones', 'Andén', 'Billete'] },
      { w: 'Mapa', t: ['Papel', 'Orientarse', 'Doblar', 'Carreteras', 'Norte'] },
      { w: 'Brújula', t: ['Norte', 'Aguja', 'Orientarse', 'Bosque', 'Imán'] },
      { w: 'Souvenir', t: ['Recuerdo', 'Viaje', 'Tienda', 'Imán', 'Regalo'] },
      { w: 'Guía turístico', t: ['Grupo', 'Paraguas', 'Explicar', 'Monumento', 'Idiomas'] },
      { w: 'Mochila', t: ['Espalda', 'Tirantes', 'Cargar', 'Colegio', 'Cremallera'] },
      { w: 'Autocaravana', t: ['Viajar', 'Dormir', 'Ruedas', 'Cocina', 'Carretera'] },
      { w: 'Faro', t: ['Luz', 'Costa', 'Barcos', 'Torre', 'Girar'] },
      { w: 'Puente', t: ['Río', 'Cruzar', 'Orillas', 'Arco', 'Colgante'] },
      { w: 'Castillo', t: ['Torres', 'Rey', 'Foso', 'Piedra', 'Murallas'] },
      { w: 'Museo', t: ['Cuadros', 'Entrada', 'Silencio', 'Salas', 'Guía'] },
      { w: 'Mercadillo', t: ['Puestos', 'Regatear', 'Domingo', 'Calle', 'Segunda mano'] }
    ]
  },

  tecno: {
    id: 'tecno',
    name: 'Tecnología',
    emoji: '💻',
    desc: 'Cacharros, apps e internet.',
    cards: [
      { w: 'Móvil', t: ['Llamar', 'Pantalla', 'Bolsillo', 'Apps', 'Batería'] },
      { w: 'Wifi', t: ['Internet', 'Router', 'Contraseña', 'Sin cables', 'Cobertura'] },
      { w: 'Batería', t: ['Cargar', 'Porcentaje', 'Agotar', 'Pila', 'Móvil'] },
      { w: 'Cargador', t: ['Enchufe', 'Cable', 'Móvil', 'Olvidar', 'Rápido'] },
      { w: 'Ordenador', t: ['Pantalla', 'Teclado', 'Trabajar', 'Encender', 'Escritorio'] },
      { w: 'Portátil', t: ['Ordenador', 'Tapa', 'Llevar', 'Batería', 'Bolso'] },
      { w: 'Teclado', t: ['Teclas', 'Escribir', 'Letras', 'Ordenador', 'Espacio'] },
      { w: 'Cursor', t: ['Flecha', 'Pantalla', 'Ratón', 'Mover', 'Parpadear'] },
      { w: 'Pantalla', t: ['Ver', 'Píxeles', 'Brillo', 'Táctil', 'Televisión'] },
      { w: 'Impresora', t: ['Papel', 'Tinta', 'Folios', 'Atascar', 'Copiar'] },
      { w: 'Internet', t: ['Red', 'Navegar', 'Conexión', 'Páginas', 'Mundial'] },
      { w: 'Correo electrónico', t: ['Enviar', 'Arroba', 'Bandeja', 'Adjunto', 'Spam'] },
      { w: 'Emoji', t: ['Carita', 'Mensaje', 'Amarillo', 'Móvil', 'Dibujo'] },
      { w: 'Videollamada', t: ['Cámara', 'Hablar', 'Pantalla', 'Distancia', 'Micrófono'] },
      { w: 'Auriculares', t: ['Oídos', 'Música', 'Cable', 'Escuchar', 'Ruido'] },
      { w: 'Altavoz', t: ['Sonido', 'Música', 'Volumen', 'Alto', 'Bluetooth'] },
      { w: 'Cámara', t: ['Fotos', 'Objetivo', 'Disparar', 'Flash', 'Retratar'] },
      { w: 'Dron', t: ['Volar', 'Hélices', 'Mando', 'Grabar', 'Aire'] },
      { w: 'Inteligencia artificial', t: ['Ordenador', 'Aprender', 'Chat', 'Robot', 'Datos'] },
      { w: 'Buscador', t: ['Google', 'Internet', 'Preguntar', 'Resultados', 'Web'] },
      { w: 'Aplicación', t: ['Móvil', 'Instalar', 'Icono', 'Tienda', 'Descargar'] },
      { w: 'Descarga', t: ['Bajar', 'Archivo', 'Internet', 'Barra', 'Esperar'] },
      { w: 'Actualización', t: ['Versión', 'Nueva', 'Instalar', 'Reiniciar', 'Software'] },
      { w: 'Virus informático', t: ['Infectar', 'Antivirus', 'Archivo', 'Ordenador', 'Peligro'] },
      { w: 'Copia de seguridad', t: ['Guardar', 'Perder', 'Archivos', 'Disco', 'Restaurar'] },
      { w: 'Nube', t: ['Guardar', 'Internet', 'Archivos', 'Servidor', 'Sincronizar'] },
      { w: 'Bluetooth', t: ['Conectar', 'Sin cables', 'Auriculares', 'Emparejar', 'Cerca'] },
      { w: 'GPS', t: ['Ubicación', 'Satélite', 'Ruta', 'Coche', 'Voz'] },
      { w: 'Código QR', t: ['Cuadrado', 'Escanear', 'Móvil', 'Cámara', 'Enlace'] },
      { w: 'Mando a distancia', t: ['Televisión', 'Botones', 'Canales', 'Pilas', 'Sofá'] },
      { w: 'Consola', t: ['Videojuegos', 'Mando', 'Televisión', 'Nintendo', 'Jugar'] },
      { w: 'Televisión', t: ['Canales', 'Salón', 'Ver', 'Pantalla', 'Series'] },
      { w: 'Radio', t: ['Escuchar', 'Emisora', 'Locutor', 'Dial', 'Coche'] },
      { w: 'Microchip', t: ['Pequeño', 'Silicio', 'Circuito', 'Ordenador', 'Placa'] },
      { w: 'Cable', t: ['Conectar', 'Enredar', 'Enchufe', 'Largo', 'Cobre'] },
      { w: 'USB', t: ['Puerto', 'Memoria', 'Conectar', 'Pincho', 'Archivos'] },
      { w: 'Reloj inteligente', t: ['Muñeca', 'Pasos', 'Pulsaciones', 'Notificaciones', 'Cargar'] },
      { w: 'Patinete eléctrico', t: ['Ruedas', 'Ciudad', 'Manillar', 'Batería', 'Acera'] },
      { w: 'Coche eléctrico', t: ['Enchufe', 'Batería', 'Silencioso', 'Cargar', 'Contaminar'] },
      { w: 'Robot', t: ['Metal', 'Programar', 'Humanoide', 'Fábrica', 'Órdenes'] }
    ]
  },

  dificiles: {
    id: 'dificiles',
    name: 'Difíciles',
    emoji: '🧠',
    desc: 'Palabras abstractas. Aquí se sufre.',
    cards: [
      { w: 'Amor', t: ['Corazón', 'Pareja', 'Querer', 'Sentimiento', 'San Valentín'] },
      { w: 'Envidia', t: ['Verde', 'Otro', 'Querer', 'Pecado', 'Sentimiento'] },
      { w: 'Miedo', t: ['Susto', 'Terror', 'Oscuridad', 'Temblar', 'Fantasma'] },
      { w: 'Vergüenza', t: ['Rojo', 'Cara', 'Ridículo', 'Público', 'Ajena'] },
      { w: 'Nostalgia', t: ['Pasado', 'Recuerdos', 'Echar de menos', 'Infancia', 'Tristeza'] },
      { w: 'Paciencia', t: ['Esperar', 'Calma', 'Santo', 'Perder', 'Aguantar'] },
      { w: 'Suerte', t: ['Azar', 'Lotería', 'Trébol', 'Mala', 'Fortuna'] },
      { w: 'Destino', t: ['Futuro', 'Escrito', 'Casualidad', 'Vida', 'Creer'] },
      { w: 'Libertad', t: ['Cárcel', 'Preso', 'Elegir', 'Derechos', 'Estatua'] },
      { w: 'Justicia', t: ['Juez', 'Balanza', 'Ley', 'Venda', 'Tribunal'] },
      { w: 'Mentira', t: ['Verdad', 'Engañar', 'Nariz', 'Pinocho', 'Piadosa'] },
      { w: 'Secreto', t: ['Contar', 'Callar', 'Nadie', 'Confianza', 'Oído'] },
      { w: 'Silencio', t: ['Ruido', 'Callar', 'Biblioteca', 'Shhh', 'Nada'] },
      { w: 'Tiempo', t: ['Reloj', 'Horas', 'Pasar', 'Perder', 'Futuro'] },
      { w: 'Memoria', t: ['Recordar', 'Olvidar', 'Cabeza', 'Elefante', 'Pasado'] },
      { w: 'Costumbre', t: ['Repetir', 'Siempre', 'Hábito', 'Rutina', 'Cambiar'] },
      { w: 'Rutina', t: ['Todos los días', 'Aburrido', 'Igual', 'Horario', 'Romper'] },
      { w: 'Casualidad', t: ['Azar', 'Sin querer', 'Coincidencia', 'Encontrarse', 'Suerte'] },
      { w: 'Confianza', t: ['Fiarse', 'Amigo', 'Secreto', 'Traicionar', 'Seguridad'] },
      { w: 'Traición', t: ['Puñalada', 'Amigo', 'Engaño', 'Espalda', 'Judas'] },
      { w: 'Perdón', t: ['Disculpa', 'Error', 'Pedir', 'Olvidar', 'Culpa'] },
      { w: 'Orgullo', t: ['Bandera', 'Pecado', 'Presumir', 'Herido', 'Padres'] },
      { w: 'Curiosidad', t: ['Gato', 'Preguntar', 'Saber', 'Mirar', 'Interés'] },
      { w: 'Aburrimiento', t: ['Nada', 'Domingo', 'Bostezo', 'Clase', 'Rollo'] },
      { w: 'Duda', t: ['Pregunta', 'No saber', 'Beneficio', 'Elegir', 'Inseguridad'] },
      { w: 'Esperanza', t: ['Última', 'Futuro', 'Perder', 'Ilusión', 'Fe'] },
      { w: 'Sorpresa', t: ['Fiesta', 'Regalo', 'Inesperado', 'Cara', 'Susto'] },
      { w: 'Educación', t: ['Colegio', 'Modales', 'Enseñar', 'Padres', 'Buenos días'] },
      { w: 'Democracia', t: ['Votar', 'Urnas', 'Pueblo', 'Elecciones', 'Grecia'] },
      { w: 'Economía', t: ['Dinero', 'Crisis', 'Mercado', 'País', 'Bolsa'] },
      { w: 'Inflación', t: ['Precios', 'Subir', 'Dinero', 'Cesta', 'Crisis'] },
      { w: 'Cultura', t: ['Museo', 'Libros', 'Pueblo', 'Costumbres', 'Arte'] },
      { w: 'Tradición', t: ['Siempre', 'Abuelos', 'Fiesta', 'Pueblo', 'Costumbre'] },
      { w: 'Religión', t: ['Dios', 'Iglesia', 'Rezar', 'Fe', 'Creer'] },
      { w: 'Filosofía', t: ['Pensar', 'Grecia', 'Preguntas', 'Sócrates', 'Existir'] },
      { w: 'Ciencia', t: ['Experimento', 'Laboratorio', 'Método', 'Investigar', 'Bata'] },
      { w: 'Gravedad', t: ['Caer', 'Newton', 'Manzana', 'Peso', 'Suelo'] },
      { w: 'Evolución', t: ['Darwin', 'Monos', 'Especies', 'Cambiar', 'Millones'] },
      { w: 'Infinito', t: ['Nunca acaba', 'Ocho', 'Números', 'Universo', 'Límite'] },
      { w: 'Karma', t: ['Devolver', 'Bueno', 'Malo', 'Vida', 'Merecer'] },
      { w: 'Déjà vu', t: ['Ya visto', 'Antes', 'Sensación', 'Repetido', 'Memoria'] },
      { w: 'Ironía', t: ['Contrario', 'Burla', 'Decir', 'Tono', 'Sarcasmo'] },
      { w: 'Rumor', t: ['Corre', 'Cotilleo', 'Boca', 'Falso', 'Gente'] },
      { w: 'Prejuicio', t: ['Juzgar', 'Antes', 'Idea', 'Conocer', 'Tópico'] },
      { w: 'Rencor', t: ['Guardar', 'Perdonar', 'Enfado', 'Años', 'Odio'] }
    ]
  }
};

/* Todas las cartas de todos los packs, para contar y para el modo "todo". */
const ALL_CARDS = Object.values(PACKS).reduce((n, p) => n + p.cards.length, 0);

