/**
 * Banco de cartas del Tabú.
 * Cada carta: { w: "palabra a adivinar", t: ["cinco", "palabras", "prohibidas"] }
 *
 * Reglas del banco:
 *  - Siempre 5 palabras prohibidas: las cinco que todo el mundo diría primero.
 *  - Las prohibidas nunca repiten la palabra de la carta (sus derivados ya
 *    están prohibidos por las reglas del juego, no hace falta listarlos).
 *  - Cosas conocidas por cualquiera. Si hace falta ser experto, no entra.
 */
const PACKS = {
  cotidiano: {
    id: 'cotidiano',
    name: 'Día a día',
    emoji: '🏠',
    desc: 'Casa, trabajo y cosas de todos los días.',
    cards: [
      { w: 'Despertador', t: ['Reloj', 'Sonar', 'Mañana', 'Levantarse', 'Alarma'] },
      { w: 'Ducha', t: ['Agua', 'Jabón', 'Baño', 'Mojarse', 'Gel'] },
      { w: 'Cepillo de dientes', t: ['Boca', 'Pasta', 'Lavar', 'Higiene', 'Muelas'] },
      { w: 'Café', t: ['Bebida', 'Taza', 'Máquina', 'Desayuno', 'Negro'] },
      { w: 'Desayuno', t: ['Mañana', 'Tostada', 'Café', 'Primera', 'Comida'] },
      { w: 'Ascensor', t: ['Subir', 'Botón', 'Planta', 'Edificio', 'Escaleras'] },
      { w: 'Paraguas', t: ['Lluvia', 'Abrir', 'Mojarse', 'Mango', 'Viento'] },
      { w: 'Llaves', t: ['Puerta', 'Abrir', 'Cerradura', 'Bolsillo', 'Perder'] },
      { w: 'Cartera', t: ['Dinero', 'Bolsillo', 'Tarjetas', 'Cuero', 'Perder'] },
      { w: 'Sofá', t: ['Sentarse', 'Salón', 'Cómodo', 'Tele', 'Cojines'] },
      { w: 'Almohada', t: ['Cama', 'Dormir', 'Cabeza', 'Blanda', 'Funda'] },
      { w: 'Nevera', t: ['Frío', 'Cocina', 'Comida', 'Puerta', 'Conservar'] },
      { w: 'Lavadora', t: ['Ropa', 'Lavar', 'Agua', 'Centrifugado', 'Detergente'] },
      { w: 'Microondas', t: ['Calentar', 'Cocina', 'Minutos', 'Comida', 'Pitido'] },
      { w: 'Aspiradora', t: ['Limpiar', 'Polvo', 'Suelo', 'Ruido', 'Enchufe'] },
      { w: 'Escoba', t: ['Barrer', 'Suelo', 'Palo', 'Cerdas', 'Bruja'] },
      { w: 'Basura', t: ['Bolsa', 'Tirar', 'Cubo', 'Olor', 'Contenedor'] },
      { w: 'Vecino', t: ['Puerta', 'Al lado', 'Piso', 'Ruido', 'Comunidad'] },
      { w: 'Suegra', t: ['Madre', 'Pareja', 'Familia', 'Política', 'Chiste'] },
      { w: 'Cumpleaños', t: ['Tarta', 'Velas', 'Regalo', 'Años', 'Felicidades'] },
      { w: 'Boda', t: ['Novios', 'Iglesia', 'Vestido', 'Anillo', 'Banquete'] },
      { w: 'Divorcio', t: ['Separación', 'Abogado', 'Matrimonio', 'Papeles', 'Ruptura'] },
      { w: 'Siesta', t: ['Dormir', 'Tarde', 'Sofá', 'Corta', 'Descansar'] },
      { w: 'Resaca', t: ['Alcohol', 'Cabeza', 'Dolor', 'Fiesta', 'Mañana'] },
      { w: 'Atasco', t: ['Coche', 'Tráfico', 'Parado', 'Hora punta', 'Claxon'] },
      { w: 'Semáforo', t: ['Rojo', 'Verde', 'Calle', 'Parar', 'Coches'] },
      { w: 'Autobús', t: ['Parada', 'Público', 'Conductor', 'Billete', 'Transporte'] },
      { w: 'Metro', t: ['Subterráneo', 'Andén', 'Vagón', 'Ciudad', 'Billete'] },
      { w: 'Gasolinera', t: ['Coche', 'Repostar', 'Surtidor', 'Combustible', 'Litros'] },
      { w: 'Supermercado', t: ['Compra', 'Carro', 'Caja', 'Productos', 'Pasillos'] },
      { w: 'Cola', t: ['Fila', 'Esperar', 'Gente', 'Turno', 'Caja'] },
      { w: 'Farmacia', t: ['Medicinas', 'Receta', 'Cruz', 'Verde', 'Botica'] },
      { w: 'Peluquería', t: ['Pelo', 'Cortar', 'Tijeras', 'Espejo', 'Cita'] },
      { w: 'Dentista', t: ['Dientes', 'Muela', 'Consulta', 'Torno', 'Miedo'] },
      { w: 'Médico', t: ['Consulta', 'Bata', 'Enfermo', 'Receta', 'Hospital'] },
      { w: 'Hospital', t: ['Enfermo', 'Urgencias', 'Camas', 'Médicos', 'Ingresar'] },
      { w: 'Vacuna', t: ['Pinchazo', 'Brazo', 'Jeringuilla', 'Inmunidad', 'Enfermedad'] },
      { w: 'Fiebre', t: ['Temperatura', 'Termómetro', 'Enfermo', 'Grados', 'Frente'] },
      { w: 'Estornudo', t: ['Nariz', 'Achús', 'Alergia', 'Salud', 'Sonido'] },
      { w: 'Ronquido', t: ['Dormir', 'Ruido', 'Nariz', 'Noche', 'Pareja'] },
      { w: 'Pesadilla', t: ['Sueño', 'Dormir', 'Miedo', 'Noche', 'Despertar'] },
      { w: 'Lunes', t: ['Semana', 'Día', 'Trabajo', 'Empezar', 'Domingo'] },
      { w: 'Vacaciones', t: ['Verano', 'Trabajo', 'Descanso', 'Viaje', 'Días libres'] },
      { w: 'Sueldo', t: ['Dinero', 'Trabajo', 'Mes', 'Nómina', 'Cobrar'] },
      { w: 'Jefe', t: ['Trabajo', 'Mandar', 'Oficina', 'Empleados', 'Despedir'] },
      { w: 'Reunión', t: ['Trabajo', 'Sala', 'Hablar', 'Oficina', 'Aburrida'] },
      { w: 'Currículum', t: ['Trabajo', 'Papel', 'Experiencia', 'Entrevista', 'Enviar'] },
      { w: 'Entrevista', t: ['Preguntas', 'Trabajo', 'Nervios', 'Candidato', 'Cita'] },
      { w: 'Oficina', t: ['Trabajo', 'Mesa', 'Ordenador', 'Jefe', 'Despacho'] },
      { w: 'Impuestos', t: ['Hacienda', 'Pagar', 'Estado', 'Declaración', 'Dinero'] },
      { w: 'Multa', t: ['Pagar', 'Policía', 'Infracción', 'Papel', 'Coche'] },
      { w: 'Hipoteca', t: ['Banco', 'Casa', 'Préstamo', 'Años', 'Pagar'] },
      { w: 'Alquiler', t: ['Piso', 'Mensual', 'Casero', 'Pagar', 'Contrato'] },
      { w: 'Mudanza', t: ['Cajas', 'Casa', 'Camión', 'Cambiar', 'Muebles'] },
      { w: 'Escalera', t: ['Subir', 'Peldaños', 'Bajar', 'Piso', 'Barandilla'] },
      { w: 'Espejo', t: ['Reflejo', 'Verse', 'Baño', 'Cristal', 'Imagen'] },
      { w: 'Toalla', t: ['Secarse', 'Baño', 'Playa', 'Tela', 'Mojado'] },
      { w: 'Cortina', t: ['Ventana', 'Tela', 'Correr', 'Luz', 'Colgar'] },
      { w: 'Alfombra', t: ['Suelo', 'Pisar', 'Salón', 'Tela', 'Polvo'] },
      { w: 'Bombilla', t: ['Luz', 'Enchufar', 'Fundida', 'Techo', 'Encender'] },
      { w: 'Enchufe', t: ['Corriente', 'Pared', 'Cable', 'Electricidad', 'Conectar'] },
      { w: 'Manta', t: ['Cama', 'Calor', 'Taparse', 'Sofá', 'Invierno'] },
      { w: 'Pijama', t: ['Dormir', 'Ropa', 'Cama', 'Noche', 'Cómodo'] },
      { w: 'Calcetines', t: ['Pies', 'Zapatos', 'Par', 'Ropa', 'Agujero'] },
      { w: 'Gafas', t: ['Ver', 'Ojos', 'Cristales', 'Montura', 'Vista'] },
      { w: 'Reloj', t: ['Hora', 'Muñeca', 'Tiempo', 'Agujas', 'Pulsera'] },
      { w: 'Bufanda', t: ['Cuello', 'Frío', 'Invierno', 'Lana', 'Abrigar'] },
      { w: 'Chándal', t: ['Ropa', 'Deporte', 'Cómodo', 'Chaqueta', 'Pantalón'] },
      { w: 'Bañador', t: ['Playa', 'Piscina', 'Verano', 'Ropa', 'Nadar'] },
      { w: 'Maquillaje', t: ['Cara', 'Pintar', 'Base', 'Espejo', 'Belleza'] },
      { w: 'Perfume', t: ['Oler', 'Frasco', 'Aroma', 'Echarse', 'Colonia'] },
      { w: 'Barba', t: ['Cara', 'Pelo', 'Afeitar', 'Hombre', 'Mentón'] },
      { w: 'Tatuaje', t: ['Piel', 'Tinta', 'Aguja', 'Dibujo', 'Permanente'] },
      { w: 'Cicatriz', t: ['Piel', 'Herida', 'Marca', 'Curar', 'Señal'] },
      { w: 'Cosquillas', t: ['Reír', 'Tocar', 'Pies', 'Aguantar', 'Sensación'] },
      { w: 'Bostezo', t: ['Sueño', 'Boca', 'Abrir', 'Cansancio', 'Contagio'] },
      { w: 'Hipo', t: ['Sonido', 'Susto', 'Beber', 'Diafragma', 'Parar'] },
      { w: 'Propina', t: ['Camarero', 'Dinero', 'Dejar', 'Mesa', 'Servicio'] },
      { w: 'Recibo', t: ['Papel', 'Compra', 'Ticket', 'Pagar', 'Guardar'] },
      { w: 'Contraseña', t: ['Secreta', 'Olvidar', 'Cuenta', 'Letras', 'Entrar'] }
    ]
  },

  comida: {
    id: 'comida',
    name: 'Comida y bebida',
    emoji: '🍔',
    desc: 'Platos, ingredientes y cosas de beber.',
    cards: [
      { w: 'Paella', t: ['Arroz', 'Valencia', 'Domingo', 'Azafrán', 'Sartén'] },
      { w: 'Tortilla de patatas', t: ['Huevo', 'Cebolla', 'Sartén', 'Vuelta', 'Pincho'] },
      { w: 'Gazpacho', t: ['Tomate', 'Frío', 'Verano', 'Beber', 'Sopa'] },
      { w: 'Jamón', t: ['Cerdo', 'Pata', 'Cortar', 'Ibérico', 'Loncha'] },
      { w: 'Chorizo', t: ['Embutido', 'Cerdo', 'Rojo', 'Pimentón', 'Bocadillo'] },
      { w: 'Queso', t: ['Leche', 'Curado', 'Ratón', 'Amarillo', 'Loncha'] },
      { w: 'Aceite de oliva', t: ['Verde', 'Botella', 'Freír', 'Ensalada', 'Aceituna'] },
      { w: 'Pan', t: ['Barra', 'Harina', 'Horno', 'Miga', 'Duro'] },
      { w: 'Bocadillo', t: ['Pan', 'Relleno', 'Merienda', 'Jamón', 'Morder'] },
      { w: 'Churros', t: ['Chocolate', 'Freír', 'Desayuno', 'Azúcar', 'Feria'] },
      { w: 'Croqueta', t: ['Bechamel', 'Freír', 'Rebozada', 'Tapa', 'Abuela'] },
      { w: 'Empanada', t: ['Masa', 'Relleno', 'Gallega', 'Atún', 'Horno'] },
      { w: 'Sushi', t: ['Japón', 'Arroz', 'Pescado', 'Crudo', 'Palillos'] },
      { w: 'Pizza', t: ['Italia', 'Queso', 'Redonda', 'Porción', 'Horno'] },
      { w: 'Hamburguesa', t: ['Carne', 'Pan', 'Queso', 'Rápida', 'Kétchup'] },
      { w: 'Kebab', t: ['Carne', 'Turco', 'Pan', 'Salsa', 'Madrugada'] },
      { w: 'Espagueti', t: ['Pasta', 'Largo', 'Tomate', 'Italia', 'Tenedor'] },
      { w: 'Lasaña', t: ['Pasta', 'Capas', 'Horno', 'Bechamel', 'Italia'] },
      { w: 'Arroz', t: ['Blanco', 'Grano', 'Paella', 'China', 'Hervir'] },
      { w: 'Sopa', t: ['Caliente', 'Cuchara', 'Plato', 'Caldo', 'Fideos'] },
      { w: 'Ensalada', t: ['Lechuga', 'Tomate', 'Verde', 'Dieta', 'Aliñar'] },
      { w: 'Lentejas', t: ['Legumbre', 'Cuchara', 'Puchero', 'Hierro', 'Abuela'] },
      { w: 'Garbanzos', t: ['Legumbre', 'Cocido', 'Hummus', 'Redondos', 'Puchero'] },
      { w: 'Huevo frito', t: ['Yema', 'Sartén', 'Aceite', 'Puntilla', 'Patatas'] },
      { w: 'Bacon', t: ['Cerdo', 'Tiras', 'Desayuno', 'Crujiente', 'Sartén'] },
      { w: 'Pollo asado', t: ['Horno', 'Ave', 'Domingo', 'Muslo', 'Piel'] },
      { w: 'Chuletón', t: ['Carne', 'Vaca', 'Parrilla', 'Hueso', 'Punto'] },
      { w: 'Pescado', t: ['Mar', 'Espinas', 'Escamas', 'Freír', 'Lonja'] },
      { w: 'Salmón', t: ['Rosa', 'Pescado', 'Ahumado', 'Noruega', 'Río'] },
      { w: 'Marisco', t: ['Mar', 'Navidad', 'Caro', 'Gambas', 'Concha'] },
      { w: 'Gambas', t: ['Ajillo', 'Pelar', 'Rosa', 'Mar', 'Cola'] },
      { w: 'Pulpo', t: ['Gallega', 'Tentáculos', 'Ventosas', 'Pimentón', 'Mar'] },
      { w: 'Calamares', t: ['Rabas', 'Anillas', 'Bocadillo', 'Freír', 'Tinta'] },
      { w: 'Anchoa', t: ['Salada', 'Lata', 'Pequeña', 'Pescado', 'Aperitivo'] },
      { w: 'Aceituna', t: ['Verde', 'Hueso', 'Aperitivo', 'Rellena', 'Olivo'] },
      { w: 'Patatas fritas', t: ['Bolsa', 'Bastones', 'Aceite', 'Sal', 'Crujiente'] },
      { w: 'Palomitas', t: ['Cine', 'Maíz', 'Explotar', 'Cubo', 'Sal'] },
      { w: 'Chicle', t: ['Masticar', 'Boca', 'Globo', 'Menta', 'Pegajoso'] },
      { w: 'Chocolate', t: ['Cacao', 'Tableta', 'Dulce', 'Negro', 'Onza'] },
      { w: 'Helado', t: ['Frío', 'Verano', 'Cucurucho', 'Bolas', 'Derretir'] },
      { w: 'Tarta', t: ['Cumpleaños', 'Velas', 'Porción', 'Nata', 'Horno'] },
      { w: 'Flan', t: ['Caramelo', 'Huevo', 'Postre', 'Temblar', 'Molde'] },
      { w: 'Natillas', t: ['Postre', 'Galleta', 'Canela', 'Cuchara', 'Vainilla'] },
      { w: 'Yogur', t: ['Leche', 'Postre', 'Tarrina', 'Fresa', 'Caducidad'] },
      { w: 'Miel', t: ['Abeja', 'Dulce', 'Pegajosa', 'Tarro', 'Oso'] },
      { w: 'Mermelada', t: ['Fruta', 'Tostada', 'Tarro', 'Dulce', 'Untar'] },
      { w: 'Mantequilla', t: ['Leche', 'Tostada', 'Untar', 'Pastilla', 'Grasa'] },
      { w: 'Sal', t: ['Blanca', 'Sabor', 'Mar', 'Grano', 'Soso'] },
      { w: 'Azúcar', t: ['Dulce', 'Blanco', 'Café', 'Cucharada', 'Terrón'] },
      { w: 'Pimienta', t: ['Negra', 'Molinillo', 'Picante', 'Sal', 'Especia'] },
      { w: 'Kétchup', t: ['Tomate', 'Rojo', 'Salsa', 'Bote', 'Patatas'] },
      { w: 'Mayonesa', t: ['Blanca', 'Salsa', 'Huevo', 'Aceite', 'Ensaladilla'] },
      { w: 'Café con leche', t: ['Bar', 'Taza', 'Desayuno', 'Cafeína', 'Caliente'] },
      { w: 'Zumo de naranja', t: ['Exprimir', 'Fruta', 'Vitamina', 'Desayuno', 'Vaso'] },
      { w: 'Cerveza', t: ['Caña', 'Bar', 'Espuma', 'Rubia', 'Fría'] },
      { w: 'Vino tinto', t: ['Uva', 'Copa', 'Botella', 'Rioja', 'Alcohol'] },
      { w: 'Sangría', t: ['Vino', 'Fruta', 'Jarra', 'Verano', 'Turistas'] },
      { w: 'Champán', t: ['Burbujas', 'Brindis', 'Corcho', 'Nochevieja', 'Copa'] },
      { w: 'Batido', t: ['Leche', 'Fresa', 'Vaso', 'Pajita', 'Espeso'] },
      { w: 'Agua con gas', t: ['Burbujas', 'Botella', 'Beber', 'Sed', 'Sin sabor'] }
    ]
  },
  pop: {
    id: 'pop',
    name: 'Cine, música y famosos',
    emoji: '🎬',
    desc: 'Pelis, series, canciones y caras conocidas.',
    cards: [
      { w: 'Titanic', t: ['Barco', 'Iceberg', 'Rose', 'Hundir', 'DiCaprio'] },
      { w: 'Star Wars', t: ['Galaxia', 'Espada láser', 'Vader', 'Fuerza', 'Jedi'] },
      { w: 'Harry Potter', t: ['Magia', 'Hogwarts', 'Gafas', 'Varita', 'Cicatriz'] },
      { w: 'El Señor de los Anillos', t: ['Anillo', 'Hobbit', 'Frodo', 'Tolkien', 'Mordor'] },
      { w: 'Jurassic Park', t: ['Dinosaurios', 'Parque', 'Isla', 'ADN', 'Spielberg'] },
      { w: 'El Rey León', t: ['Simba', 'Disney', 'Sabana', 'Melena', 'Hakuna matata'] },
      { w: 'Frozen', t: ['Elsa', 'Hielo', 'Disney', 'Hermanas', 'Muñeco'] },
      { w: 'Toy Story', t: ['Juguetes', 'Woody', 'Buzz', 'Pixar', 'Vaquero'] },
      { w: 'Shrek', t: ['Ogro', 'Verde', 'Burro', 'Pantano', 'Fiona'] },
      { w: 'Los Simpson', t: ['Amarillos', 'Homer', 'Springfield', 'Dibujos', 'Bart'] },
      { w: 'Friends', t: ['Serie', 'Sofá', 'Cafetería', 'Seis', 'Nueva York'] },
      { w: 'Juego de Tronos', t: ['Trono', 'Dragones', 'Invierno', 'Poniente', 'Serie'] },
      { w: 'Stranger Things', t: ['Netflix', 'Ochenta', 'Niños', 'Monstruo', 'Bicicletas'] },
      { w: 'La Casa de Papel', t: ['Atraco', 'Máscara', 'Rojo', 'Profesor', 'Ciudades'] },
      { w: 'Breaking Bad', t: ['Profesor', 'Química', 'Droga', 'Caravana', 'Calvo'] },
      { w: 'Netflix', t: ['Series', 'Plataforma', 'Suscripción', 'Rojo', 'Ver'] },
      { w: 'Óscar', t: ['Premio', 'Estatuilla', 'Cine', 'Hollywood', 'Gala'] },
      { w: 'Alfombra roja', t: ['Famosos', 'Premios', 'Fotos', 'Vestidos', 'Desfilar'] },
      { w: 'Paparazzi', t: ['Fotos', 'Famosos', 'Perseguir', 'Revista', 'Cámara'] },
      { w: 'Selfie', t: ['Foto', 'Móvil', 'Uno mismo', 'Palo', 'Instagram'] },
      { w: 'Instagram', t: ['Fotos', 'Red social', 'Filtros', 'Seguidores', 'Stories'] },
      { w: 'TikTok', t: ['Vídeos', 'Bailes', 'App', 'Cortos', 'Jóvenes'] },
      { w: 'Reguetón', t: ['Música', 'Perreo', 'Latino', 'Discoteca', 'Ritmo'] },
      { w: 'Flamenco', t: ['Baile', 'Guitarra', 'Andalucía', 'Palmas', 'Bata de cola'] },
      { w: 'Rock', t: ['Guitarra', 'Música', 'Batería', 'Concierto', 'Melena'] },
      { w: 'Rap', t: ['Rima', 'Música', 'Hablar', 'Calle', 'Batalla'] },
      { w: 'Karaoke', t: ['Cantar', 'Micrófono', 'Letra', 'Pantalla', 'Desafinar'] },
      { w: 'Concierto', t: ['Música', 'Directo', 'Escenario', 'Entradas', 'Público'] },
      { w: 'Festival', t: ['Verano', 'Música', 'Pulsera', 'Camping', 'Escenarios'] },
      { w: 'Eurovisión', t: ['Canción', 'Países', 'Puntos', 'Mayo', 'Televisión'] },
      { w: 'Beyoncé', t: ['Cantante', 'Estados Unidos', 'Destiny', 'Jay-Z', 'Diva'] },
      { w: 'Michael Jackson', t: ['Pop', 'Guante', 'Moonwalk', 'Thriller', 'Rey'] },
      { w: 'Elvis', t: ['Rock', 'Tupé', 'Memphis', 'Cadera', 'Presley'] },
      { w: 'Los Beatles', t: ['Liverpool', 'Cuatro', 'Lennon', 'Paso de cebra', 'Banda'] },
      { w: 'Freddie Mercury', t: ['Queen', 'Bigote', 'Cantante', 'Bohemian', 'Wembley'] },
      { w: 'Rosalía', t: ['Cantante', 'Catalana', 'Flamenco', 'Motomami', 'Uñas'] },
      { w: 'Bad Bunny', t: ['Reguetón', 'Puerto Rico', 'Conejo', 'Gafas', 'Cantante'] },
      { w: 'Shakira', t: ['Colombia', 'Caderas', 'Cantante', 'Rubia', 'Loba'] },
      { w: 'Madonna', t: ['Cantante', 'Pop', 'Rubia', 'Ochenta', 'Reina'] },
      { w: 'Lady Gaga', t: ['Cantante', 'Extravagante', 'Poker Face', 'Carne', 'Pop'] },
      { w: 'Messi', t: ['Fútbol', 'Argentina', 'Barcelona', 'Pulga', 'Balón de Oro'] },
      { w: 'Cristiano Ronaldo', t: ['Fútbol', 'Portugal', 'Madrid', 'Siuu', 'Abdominales'] },
      { w: 'Rafa Nadal', t: ['Tenis', 'Mallorca', 'Roland Garros', 'Zurdo', 'Raqueta'] },
      { w: 'Superman', t: ['Capa', 'Volar', 'Kriptonita', 'Azul', 'Cabina'] },
      { w: 'Batman', t: ['Murciélago', 'Gotham', 'Negro', 'Millonario', 'Cueva'] },
      { w: 'Spiderman', t: ['Araña', 'Telaraña', 'Trepar', 'Máscara', 'Rojo'] },
      { w: 'Iron Man', t: ['Armadura', 'Stark', 'Hierro', 'Marvel', 'Millonario'] },
      { w: 'Godzilla', t: ['Monstruo', 'Japón', 'Gigante', 'Ciudad', 'Lagarto'] },
      { w: 'King Kong', t: ['Gorila', 'Gigante', 'Rascacielos', 'Isla', 'Trepar'] },
      { w: 'Drácula', t: ['Vampiro', 'Sangre', 'Colmillos', 'Capa', 'Transilvania'] },
      { w: 'Frankenstein', t: ['Monstruo', 'Tornillos', 'Doctor', 'Rayo', 'Verde'] },
      { w: 'Zombi', t: ['Muerto', 'Andar', 'Cerebro', 'Apocalipsis', 'Contagio'] },
      { w: 'Extraterrestre', t: ['Espacio', 'Ovni', 'Verde', 'Marte', 'Antenas'] },
      { w: 'Pirata', t: ['Barco', 'Parche', 'Tesoro', 'Loro', 'Garfio'] },
      { w: 'Vaquero', t: ['Sombrero', 'Caballo', 'Oeste', 'Revólver', 'Lazo'] },
      { w: 'Superhéroe', t: ['Capa', 'Poderes', 'Salvar', 'Cómic', 'Máscara'] },
      { w: 'Videojuego', t: ['Consola', 'Mando', 'Pantalla', 'Niveles', 'Jugar'] },
      { w: 'Mario Bros', t: ['Fontanero', 'Bigote', 'Nintendo', 'Setas', 'Rojo'] },
      { w: 'Payaso', t: ['Circo', 'Nariz', 'Reír', 'Maquillaje', 'Zapatos'] },
      { w: 'Mago', t: ['Truco', 'Chistera', 'Conejo', 'Varita', 'Cartas'] }
    ]
  },

  natura: {
    id: 'natura',
    name: 'Animales y naturaleza',
    emoji: '🐾',
    desc: 'Bichos, plantas y paisajes.',
    cards: [
      { w: 'Perro', t: ['Ladrar', 'Mascota', 'Hueso', 'Correa', 'Fiel'] },
      { w: 'Gato', t: ['Maullar', 'Mascota', 'Ratón', 'Bigotes', 'Arañar'] },
      { w: 'Elefante', t: ['Trompa', 'Grande', 'Orejas', 'Colmillos', 'África'] },
      { w: 'Jirafa', t: ['Cuello', 'Alta', 'Manchas', 'Sabana', 'Hojas'] },
      { w: 'León', t: ['Melena', 'Rey', 'Rugido', 'Selva', 'Sabana'] },
      { w: 'Tigre', t: ['Rayas', 'Naranja', 'Felino', 'Asia', 'Cazador'] },
      { w: 'Oso', t: ['Miel', 'Invierno', 'Bosque', 'Peludo', 'Hibernar'] },
      { w: 'Lobo', t: ['Aullar', 'Manada', 'Luna', 'Caperucita', 'Bosque'] },
      { w: 'Zorro', t: ['Astuto', 'Rojo', 'Cola', 'Bosque', 'Gallinero'] },
      { w: 'Conejo', t: ['Orejas', 'Zanahoria', 'Saltar', 'Madriguera', 'Pascua'] },
      { w: 'Ratón', t: ['Queso', 'Pequeño', 'Cola', 'Trampa', 'Gato'] },
      { w: 'Ardilla', t: ['Nueces', 'Árbol', 'Cola', 'Saltar', 'Parque'] },
      { w: 'Caballo', t: ['Montar', 'Galope', 'Silla', 'Herradura', 'Relinchar'] },
      { w: 'Vaca', t: ['Leche', 'Muu', 'Establo', 'Manchas', 'Hierba'] },
      { w: 'Cerdo', t: ['Barro', 'Rosa', 'Granja', 'Jamón', 'Gruñir'] },
      { w: 'Oveja', t: ['Lana', 'Rebaño', 'Pastor', 'Contar', 'Balar'] },
      { w: 'Cabra', t: ['Montaña', 'Cuernos', 'Queso', 'Barba', 'Trepar'] },
      { w: 'Gallina', t: ['Huevos', 'Corral', 'Plumas', 'Cacarear', 'Pollo'] },
      { w: 'Pato', t: ['Estanque', 'Cuac', 'Nadar', 'Pico', 'Plumas'] },
      { w: 'Pingüino', t: ['Frío', 'Hielo', 'Blanco y negro', 'Nadar', 'Antártida'] },
      { w: 'Águila', t: ['Volar', 'Rapaz', 'Garras', 'Vista', 'Montaña'] },
      { w: 'Búho', t: ['Noche', 'Ojos', 'Árbol', 'Sabio', 'Ulular'] },
      { w: 'Loro', t: ['Hablar', 'Colores', 'Jaula', 'Pirata', 'Repetir'] },
      { w: 'Cigüeña', t: ['Nido', 'Campanario', 'Bebés', 'Pico', 'Patas'] },
      { w: 'Murciélago', t: ['Noche', 'Cueva', 'Volar', 'Cabeza abajo', 'Batman'] },
      { w: 'Serpiente', t: ['Reptar', 'Veneno', 'Lengua', 'Cascabel', 'Escamas'] },
      { w: 'Cocodrilo', t: ['Río', 'Dientes', 'Reptil', 'Lágrimas', 'Mandíbula'] },
      { w: 'Tortuga', t: ['Caparazón', 'Lenta', 'Liebre', 'Reptil', 'Playa'] },
      { w: 'Rana', t: ['Croar', 'Charca', 'Verde', 'Saltar', 'Príncipe'] },
      { w: 'Camaleón', t: ['Color', 'Cambiar', 'Lengua', 'Ojos', 'Rama'] },
      { w: 'Tiburón', t: ['Dientes', 'Mar', 'Aleta', 'Miedo', 'Sangre'] },
      { w: 'Ballena', t: ['Mar', 'Grande', 'Chorro', 'Azul', 'Plancton'] },
      { w: 'Delfín', t: ['Mar', 'Listo', 'Saltar', 'Sonido', 'Acuario'] },
      { w: 'Medusa', t: ['Mar', 'Picar', 'Transparente', 'Tentáculos', 'Playa'] },
      { w: 'Cangrejo', t: ['Pinzas', 'Playa', 'Lado', 'Caparazón', 'Marisco'] },
      { w: 'Caracol', t: ['Lento', 'Concha', 'Baba', 'Lluvia', 'Antenas'] },
      { w: 'Abeja', t: ['Miel', 'Picar', 'Colmena', 'Zumbar', 'Flores'] },
      { w: 'Hormiga', t: ['Pequeña', 'Fila', 'Hormiguero', 'Trabajadora', 'Azúcar'] },
      { w: 'Mariposa', t: ['Alas', 'Oruga', 'Colores', 'Flores', 'Volar'] },
      { w: 'Araña', t: ['Telaraña', 'Ocho', 'Patas', 'Miedo', 'Rincón'] },
      { w: 'Mosquito', t: ['Picar', 'Zumbido', 'Verano', 'Sangre', 'Noche'] },
      { w: 'Mono', t: ['Plátano', 'Árbol', 'Cola', 'Imitar', 'Selva'] },
      { w: 'Camello', t: ['Joroba', 'Desierto', 'Agua', 'Caravana', 'Arena'] },
      { w: 'Canguro', t: ['Australia', 'Bolsa', 'Saltar', 'Cría', 'Cola'] },
      { w: 'Koala', t: ['Australia', 'Eucalipto', 'Dormir', 'Árbol', 'Peluche'] },
      { w: 'Panda', t: ['China', 'Bambú', 'Blanco y negro', 'Oso', 'Ojeras'] },
      { w: 'Rinoceronte', t: ['Cuerno', 'Gris', 'África', 'Carga', 'Piel dura'] },
      { w: 'Hipopótamo', t: ['Río', 'Gordo', 'África', 'Boca', 'Barro'] },
      { w: 'Cebra', t: ['Rayas', 'Sabana', 'Blanco y negro', 'Paso', 'Caballo'] },
      { w: 'Erizo', t: ['Púas', 'Bolita', 'Pequeño', 'Bosque', 'Pinchar'] },
      { w: 'Toro', t: ['Cuernos', 'Plaza', 'Rojo', 'Embestir', 'Bravo'] },
      { w: 'Ciervo', t: ['Cuernos', 'Bosque', 'Bambi', 'Correr', 'Berrea'] },
      { w: 'Árbol', t: ['Tronco', 'Hojas', 'Ramas', 'Sombra', 'Bosque'] },
      { w: 'Bosque', t: ['Árboles', 'Verde', 'Perderse', 'Setas', 'Senderos'] },
      { w: 'Montaña', t: ['Alta', 'Cima', 'Escalar', 'Nieve', 'Valle'] },
      { w: 'Río', t: ['Agua', 'Corriente', 'Puente', 'Cauce', 'Desembocar'] },
      { w: 'Volcán', t: ['Lava', 'Erupción', 'Cráter', 'Ceniza', 'Montaña'] },
      { w: 'Desierto', t: ['Arena', 'Calor', 'Sed', 'Dunas', 'Oasis'] },
      { w: 'Nieve', t: ['Blanca', 'Frío', 'Copos', 'Invierno', 'Muñeco'] },
      { w: 'Arcoíris', t: ['Colores', 'Lluvia', 'Cielo', 'Arco', 'Siete'] },
      { w: 'Tormenta', t: ['Rayos', 'Truenos', 'Lluvia', 'Nubes', 'Viento'] },
      { w: 'Niebla', t: ['No ver', 'Blanca', 'Carretera', 'Húmeda', 'Mañana'] },
      { w: 'Terremoto', t: ['Temblar', 'Tierra', 'Escala', 'Derrumbe', 'Placas'] },
      { w: 'Luna', t: ['Noche', 'Cielo', 'Llena', 'Astronauta', 'Cráteres'] },
      { w: 'Estrella', t: ['Cielo', 'Brillar', 'Noche', 'Deseo', 'Fugaz'] },
      { w: 'Cascada', t: ['Agua', 'Caer', 'Río', 'Salto', 'Ruido'] },
      { w: 'Cueva', t: ['Oscuro', 'Piedra', 'Murciélagos', 'Entrada', 'Eco'] }
    ]
  },
  deporte: {
    id: 'deporte',
    name: 'Deporte y ocio',
    emoji: '⚽',
    desc: 'Deportes, juegos y gimnasio.',
    cards: [
      { w: 'Fútbol', t: ['Balón', 'Gol', 'Once', 'Portería', 'Campo'] },
      { w: 'Baloncesto', t: ['Canasta', 'Bote', 'Altos', 'Triple', 'Aro'] },
      { w: 'Tenis', t: ['Raqueta', 'Red', 'Pelota', 'Set', 'Pista'] },
      { w: 'Golf', t: ['Palo', 'Hoyo', 'Bola', 'Campo', 'Carrito'] },
      { w: 'Natación', t: ['Piscina', 'Agua', 'Calle', 'Gorro', 'Estilos'] },
      { w: 'Ciclismo', t: ['Bicicleta', 'Pedales', 'Tour', 'Maillot', 'Etapa'] },
      { w: 'Boxeo', t: ['Guantes', 'Ring', 'Puñetazo', 'Asaltos', 'Nocaut'] },
      { w: 'Kárate', t: ['Cinturón', 'Japón', 'Patada', 'Kimono', 'Artes marciales'] },
      { w: 'Yoga', t: ['Esterilla', 'Posturas', 'Respirar', 'Relajarse', 'Namasté'] },
      { w: 'Maratón', t: ['Correr', 'Kilómetros', 'Meta', 'Dorsal', 'Resistencia'] },
      { w: 'Esquí', t: ['Nieve', 'Montaña', 'Tablas', 'Bastones', 'Pista'] },
      { w: 'Surf', t: ['Ola', 'Tabla', 'Mar', 'Playa', 'Equilibrio'] },
      { w: 'Buceo', t: ['Agua', 'Botella', 'Gafas', 'Fondo', 'Aletas'] },
      { w: 'Escalada', t: ['Pared', 'Cuerda', 'Roca', 'Presas', 'Arnés'] },
      { w: 'Patinaje', t: ['Ruedas', 'Hielo', 'Deslizar', 'Caerse', 'Pista'] },
      { w: 'Ajedrez', t: ['Tablero', 'Rey', 'Jaque', 'Piezas', 'Blancas'] },
      { w: 'Póker', t: ['Cartas', 'Apostar', 'Fichas', 'Farol', 'Casino'] },
      { w: 'Parchís', t: ['Fichas', 'Dado', 'Casillas', 'Comer', 'Colores'] },
      { w: 'Dominó', t: ['Fichas', 'Puntos', 'Bar', 'Cadena', 'Mesa'] },
      { w: 'Dardos', t: ['Diana', 'Tirar', 'Punta', 'Bar', 'Centro'] },
      { w: 'Bolos', t: ['Bola', 'Pleno', 'Pista', 'Tirar', 'Zapatos'] },
      { w: 'Billar', t: ['Taco', 'Bolas', 'Mesa', 'Tronera', 'Verde'] },
      { w: 'Petanca', t: ['Bolas', 'Boliche', 'Parque', 'Arena', 'Jubilados'] },
      { w: 'Pádel', t: ['Pala', 'Cristal', 'Pista', 'Parejas', 'Red'] },
      { w: 'Voleibol', t: ['Red', 'Balón', 'Playa', 'Saque', 'Remate'] },
      { w: 'Rugby', t: ['Ovalado', 'Placaje', 'Ensayo', 'Melé', 'Bruto'] },
      { w: 'Béisbol', t: ['Bate', 'Estados Unidos', 'Guante', 'Bases', 'Lanzador'] },
      { w: 'Balonmano', t: ['Portería', 'Mano', 'Balón', 'Pista', 'Siete'] },
      { w: 'Gimnasia', t: ['Cinta', 'Salto', 'Barra', 'Flexible', 'Rítmica'] },
      { w: 'Atletismo', t: ['Pista', 'Correr', 'Saltar', 'Vallas', 'Jabalina'] },
      { w: 'Portero', t: ['Guantes', 'Parar', 'Portería', 'Penalti', 'Equipo'] },
      { w: 'Árbitro', t: ['Silbato', 'Tarjeta', 'Pitar', 'Campo', 'Decisión'] },
      { w: 'Penalti', t: ['Portería', 'Once metros', 'Falta', 'Tirar', 'Área'] },
      { w: 'Gol', t: ['Red', 'Marcar', 'Celebrar', 'Portería', 'Fútbol'] },
      { w: 'Estadio', t: ['Campo', 'Gradas', 'Público', 'Partido', 'Césped'] },
      { w: 'Grada', t: ['Asientos', 'Público', 'Estadio', 'Animar', 'Bufanda'] },
      { w: 'Camiseta', t: ['Ropa', 'Número', 'Equipo', 'Manga', 'Escudo'] },
      { w: 'Medalla', t: ['Oro', 'Cuello', 'Premio', 'Podio', 'Colgar'] },
      { w: 'Podio', t: ['Tres', 'Escalones', 'Ganadores', 'Subir', 'Ceremonia'] },
      { w: 'Olimpiadas', t: ['Aros', 'Cuatro años', 'Antorcha', 'Países', 'Medallas'] },
      { w: 'Mundial', t: ['Selecciones', 'Copa', 'Cuatro años', 'Fútbol', 'Países'] },
      { w: 'Entrenador', t: ['Banquillo', 'Equipo', 'Táctica', 'Gritar', 'Pizarra'] },
      { w: 'Vestuario', t: ['Taquillas', 'Ducha', 'Equipo', 'Cambiarse', 'Banco'] },
      { w: 'Calentamiento', t: ['Antes', 'Estirar', 'Músculos', 'Trotar', 'Lesión'] },
      { w: 'Agujetas', t: ['Dolor', 'Músculos', 'Día siguiente', 'Ejercicio', 'Escaleras'] },
      { w: 'Gimnasio', t: ['Pesas', 'Cuota', 'Máquinas', 'Espejo', 'Sudor'] },
      { w: 'Mancuerna', t: ['Peso', 'Bíceps', 'Levantar', 'Hierro', 'Gimnasio'] },
      { w: 'Cinta de correr', t: ['Máquina', 'Gimnasio', 'Andar', 'Velocidad', 'Sudar'] },
      { w: 'Silbato', t: ['Pitar', 'Boca', 'Árbitro', 'Sonido', 'Colgado'] },
      { w: 'Trofeo', t: ['Copa', 'Ganar', 'Vitrina', 'Levantar', 'Dorado'] }
    ]
  },

  lugares: {
    id: 'lugares',
    name: 'Lugares y viajes',
    emoji: '🌍',
    desc: 'Ciudades, monumentos y cosas de viajar.',
    cards: [
      { w: 'París', t: ['Francia', 'Torre', 'Amor', 'Sena', 'Capital'] },
      { w: 'Torre Eiffel', t: ['París', 'Hierro', 'Alta', 'Francia', 'Monumento'] },
      { w: 'Roma', t: ['Italia', 'Papa', 'Coliseo', 'Capital', 'Imperio'] },
      { w: 'Coliseo', t: ['Roma', 'Gladiadores', 'Anfiteatro', 'Ruinas', 'Italia'] },
      { w: 'Venecia', t: ['Canales', 'Góndola', 'Italia', 'Agua', 'Máscaras'] },
      { w: 'Londres', t: ['Inglaterra', 'Reina', 'Autobús rojo', 'Támesis', 'Capital'] },
      { w: 'Big Ben', t: ['Londres', 'Reloj', 'Torre', 'Campana', 'Inglaterra'] },
      { w: 'Nueva York', t: ['Rascacielos', 'Manzana', 'Estados Unidos', 'Times Square', 'Taxis'] },
      { w: 'Estatua de la Libertad', t: ['Nueva York', 'Antorcha', 'Corona', 'Verde', 'Isla'] },
      { w: 'Egipto', t: ['Pirámides', 'Nilo', 'Faraón', 'Desierto', 'Momias'] },
      { w: 'Pirámides', t: ['Egipto', 'Triángulo', 'Faraón', 'Piedra', 'Desierto'] },
      { w: 'Muralla China', t: ['Larga', 'Piedra', 'Asia', 'Defensa', 'Espacio'] },
      { w: 'Machu Picchu', t: ['Perú', 'Incas', 'Montaña', 'Ruinas', 'Andes'] },
      { w: 'Taj Mahal', t: ['India', 'Blanco', 'Mármol', 'Amor', 'Cúpula'] },
      { w: 'Amazonas', t: ['Selva', 'Río', 'Brasil', 'Pulmón', 'Tribus'] },
      { w: 'Sáhara', t: ['Desierto', 'Arena', 'África', 'Dunas', 'Calor'] },
      { w: 'Everest', t: ['Montaña', 'Alta', 'Nepal', 'Escalar', 'Oxígeno'] },
      { w: 'Polo Norte', t: ['Hielo', 'Frío', 'Osos', 'Papá Noel', 'Brújula'] },
      { w: 'Hawái', t: ['Islas', 'Collar', 'Surf', 'Volcán', 'Pacífico'] },
      { w: 'Ibiza', t: ['Isla', 'Fiesta', 'Discotecas', 'Baleares', 'Playas'] },
      { w: 'Madrid', t: ['Capital', 'España', 'Sol', 'Oso', 'Centro'] },
      { w: 'Barcelona', t: ['Cataluña', 'Gaudí', 'Ramblas', 'Mar', 'Ciudad'] },
      { w: 'Sevilla', t: ['Andalucía', 'Feria', 'Giralda', 'Calor', 'Semana Santa'] },
      { w: 'Sagrada Familia', t: ['Barcelona', 'Gaudí', 'Obras', 'Torres', 'Iglesia'] },
      { w: 'Camino de Santiago', t: ['Peregrino', 'Concha', 'Andar', 'Galicia', 'Mochila'] },
      { w: 'Playa', t: ['Arena', 'Mar', 'Sombrilla', 'Verano', 'Toalla'] },
      { w: 'Hotel', t: ['Habitación', 'Recepción', 'Estrellas', 'Noche', 'Llave'] },
      { w: 'Camping', t: ['Tienda', 'Saco', 'Naturaleza', 'Parcela', 'Hoguera'] },
      { w: 'Aeropuerto', t: ['Aviones', 'Maletas', 'Puerta', 'Pista', 'Embarque'] },
      { w: 'Avión', t: ['Volar', 'Alas', 'Piloto', 'Nubes', 'Billete'] },
      { w: 'Maleta', t: ['Ruedas', 'Ropa', 'Viaje', 'Cerrar', 'Facturar'] },
      { w: 'Pasaporte', t: ['Viaje', 'Sellos', 'Foto', 'Frontera', 'Documento'] },
      { w: 'Crucero', t: ['Barco', 'Camarote', 'Puertos', 'Buffet', 'Mar'] },
      { w: 'Tren', t: ['Vías', 'Estación', 'Vagones', 'Andén', 'Billete'] },
      { w: 'Mapa', t: ['Papel', 'Orientarse', 'Doblar', 'Carreteras', 'Norte'] },
      { w: 'Brújula', t: ['Norte', 'Aguja', 'Orientarse', 'Bosque', 'Imán'] },
      { w: 'Souvenir', t: ['Recuerdo', 'Viaje', 'Tienda', 'Imán', 'Regalo'] },
      { w: 'Guía turístico', t: ['Grupo', 'Paraguas', 'Explicar', 'Monumento', 'Idiomas'] },
      { w: 'Mochila', t: ['Espalda', 'Tirantes', 'Cargar', 'Colegio', 'Cremallera'] },
      { w: 'Autocaravana', t: ['Viajar', 'Dormir', 'Ruedas', 'Cocina', 'Carretera'] },
      { w: 'Faro', t: ['Luz', 'Costa', 'Barcos', 'Torre', 'Girar'] },
      { w: 'Puente', t: ['Río', 'Cruzar', 'Orillas', 'Arco', 'Colgante'] },
      { w: 'Castillo', t: ['Torres', 'Rey', 'Foso', 'Piedra', 'Murallas'] },
      { w: 'Museo', t: ['Cuadros', 'Entrada', 'Silencio', 'Salas', 'Guía'] },
      { w: 'Mercadillo', t: ['Puestos', 'Regatear', 'Domingo', 'Calle', 'Segunda mano'] }
    ]
  },

  tecno: {
    id: 'tecno',
    name: 'Tecnología',
    emoji: '💻',
    desc: 'Cacharros, apps e internet.',
    cards: [
      { w: 'Móvil', t: ['Llamar', 'Pantalla', 'Bolsillo', 'Apps', 'Batería'] },
      { w: 'Wifi', t: ['Internet', 'Router', 'Contraseña', 'Sin cables', 'Cobertura'] },
      { w: 'Batería', t: ['Cargar', 'Porcentaje', 'Agotar', 'Pila', 'Móvil'] },
      { w: 'Cargador', t: ['Enchufe', 'Cable', 'Móvil', 'Olvidar', 'Rápido'] },
      { w: 'Ordenador', t: ['Pantalla', 'Teclado', 'Trabajar', 'Encender', 'Escritorio'] },
      { w: 'Portátil', t: ['Ordenador', 'Tapa', 'Llevar', 'Batería', 'Bolso'] },
      { w: 'Teclado', t: ['Teclas', 'Escribir', 'Letras', 'Ordenador', 'Espacio'] },
      { w: 'Cursor', t: ['Flecha', 'Pantalla', 'Ratón', 'Mover', 'Parpadear'] },
      { w: 'Pantalla', t: ['Ver', 'Píxeles', 'Brillo', 'Táctil', 'Televisión'] },
      { w: 'Impresora', t: ['Papel', 'Tinta', 'Folios', 'Atascar', 'Copiar'] },
      { w: 'Internet', t: ['Red', 'Navegar', 'Conexión', 'Páginas', 'Mundial'] },
      { w: 'Correo electrónico', t: ['Enviar', 'Arroba', 'Bandeja', 'Adjunto', 'Spam'] },
      { w: 'Emoji', t: ['Carita', 'Mensaje', 'Amarillo', 'Móvil', 'Dibujo'] },
      { w: 'Videollamada', t: ['Cámara', 'Hablar', 'Pantalla', 'Distancia', 'Micrófono'] },
      { w: 'Auriculares', t: ['Oídos', 'Música', 'Cable', 'Escuchar', 'Ruido'] },
      { w: 'Altavoz', t: ['Sonido', 'Música', 'Volumen', 'Alto', 'Bluetooth'] },
      { w: 'Cámara', t: ['Fotos', 'Objetivo', 'Disparar', 'Flash', 'Retratar'] },
      { w: 'Dron', t: ['Volar', 'Hélices', 'Mando', 'Grabar', 'Aire'] },
      { w: 'Inteligencia artificial', t: ['Ordenador', 'Aprender', 'Chat', 'Robot', 'Datos'] },
      { w: 'Buscador', t: ['Google', 'Internet', 'Preguntar', 'Resultados', 'Web'] },
      { w: 'Aplicación', t: ['Móvil', 'Instalar', 'Icono', 'Tienda', 'Descargar'] },
      { w: 'Descarga', t: ['Bajar', 'Archivo', 'Internet', 'Barra', 'Esperar'] },
      { w: 'Actualización', t: ['Versión', 'Nueva', 'Instalar', 'Reiniciar', 'Software'] },
      { w: 'Virus informático', t: ['Infectar', 'Antivirus', 'Archivo', 'Ordenador', 'Peligro'] },
      { w: 'Copia de seguridad', t: ['Guardar', 'Perder', 'Archivos', 'Disco', 'Restaurar'] },
      { w: 'Nube', t: ['Guardar', 'Internet', 'Archivos', 'Servidor', 'Sincronizar'] },
      { w: 'Bluetooth', t: ['Conectar', 'Sin cables', 'Auriculares', 'Emparejar', 'Cerca'] },
      { w: 'GPS', t: ['Ubicación', 'Satélite', 'Ruta', 'Coche', 'Voz'] },
      { w: 'Código QR', t: ['Cuadrado', 'Escanear', 'Móvil', 'Cámara', 'Enlace'] },
      { w: 'Mando a distancia', t: ['Televisión', 'Botones', 'Canales', 'Pilas', 'Sofá'] },
      { w: 'Consola', t: ['Videojuegos', 'Mando', 'Televisión', 'Nintendo', 'Jugar'] },
      { w: 'Televisión', t: ['Canales', 'Salón', 'Ver', 'Pantalla', 'Series'] },
      { w: 'Radio', t: ['Escuchar', 'Emisora', 'Locutor', 'Dial', 'Coche'] },
      { w: 'Microchip', t: ['Pequeño', 'Silicio', 'Circuito', 'Ordenador', 'Placa'] },
      { w: 'Cable', t: ['Conectar', 'Enredar', 'Enchufe', 'Largo', 'Cobre'] },
      { w: 'USB', t: ['Puerto', 'Memoria', 'Conectar', 'Pincho', 'Archivos'] },
      { w: 'Reloj inteligente', t: ['Muñeca', 'Pasos', 'Pulsaciones', 'Notificaciones', 'Cargar'] },
      { w: 'Patinete eléctrico', t: ['Ruedas', 'Ciudad', 'Manillar', 'Batería', 'Acera'] },
      { w: 'Coche eléctrico', t: ['Enchufe', 'Batería', 'Silencioso', 'Cargar', 'Contaminar'] },
      { w: 'Robot', t: ['Metal', 'Programar', 'Humanoide', 'Fábrica', 'Órdenes'] }
    ]
  },

  dificiles: {
    id: 'dificiles',
    name: 'Difíciles',
    emoji: '🧠',
    desc: 'Palabras abstractas. Aquí se sufre.',
    cards: [
      { w: 'Amor', t: ['Corazón', 'Pareja', 'Querer', 'Sentimiento', 'San Valentín'] },
      { w: 'Envidia', t: ['Verde', 'Otro', 'Querer', 'Pecado', 'Sentimiento'] },
      { w: 'Miedo', t: ['Susto', 'Terror', 'Oscuridad', 'Temblar', 'Fantasma'] },
      { w: 'Vergüenza', t: ['Rojo', 'Cara', 'Ridículo', 'Público', 'Ajena'] },
      { w: 'Nostalgia', t: ['Pasado', 'Recuerdos', 'Echar de menos', 'Infancia', 'Tristeza'] },
      { w: 'Paciencia', t: ['Esperar', 'Calma', 'Santo', 'Perder', 'Aguantar'] },
      { w: 'Suerte', t: ['Azar', 'Lotería', 'Trébol', 'Mala', 'Fortuna'] },
      { w: 'Destino', t: ['Futuro', 'Escrito', 'Casualidad', 'Vida', 'Creer'] },
      { w: 'Libertad', t: ['Cárcel', 'Preso', 'Elegir', 'Derechos', 'Estatua'] },
      { w: 'Justicia', t: ['Juez', 'Balanza', 'Ley', 'Venda', 'Tribunal'] },
      { w: 'Mentira', t: ['Verdad', 'Engañar', 'Nariz', 'Pinocho', 'Piadosa'] },
      { w: 'Secreto', t: ['Contar', 'Callar', 'Nadie', 'Confianza', 'Oído'] },
      { w: 'Silencio', t: ['Ruido', 'Callar', 'Biblioteca', 'Shhh', 'Nada'] },
      { w: 'Tiempo', t: ['Reloj', 'Horas', 'Pasar', 'Perder', 'Futuro'] },
      { w: 'Memoria', t: ['Recordar', 'Olvidar', 'Cabeza', 'Elefante', 'Pasado'] },
      { w: 'Costumbre', t: ['Repetir', 'Siempre', 'Hábito', 'Rutina', 'Cambiar'] },
      { w: 'Rutina', t: ['Todos los días', 'Aburrido', 'Igual', 'Horario', 'Romper'] },
      { w: 'Casualidad', t: ['Azar', 'Sin querer', 'Coincidencia', 'Encontrarse', 'Suerte'] },
      { w: 'Confianza', t: ['Fiarse', 'Amigo', 'Secreto', 'Traicionar', 'Seguridad'] },
      { w: 'Traición', t: ['Puñalada', 'Amigo', 'Engaño', 'Espalda', 'Judas'] },
      { w: 'Perdón', t: ['Disculpa', 'Error', 'Pedir', 'Olvidar', 'Culpa'] },
      { w: 'Orgullo', t: ['Bandera', 'Pecado', 'Presumir', 'Herido', 'Padres'] },
      { w: 'Curiosidad', t: ['Gato', 'Preguntar', 'Saber', 'Mirar', 'Interés'] },
      { w: 'Aburrimiento', t: ['Nada', 'Domingo', 'Bostezo', 'Clase', 'Rollo'] },
      { w: 'Duda', t: ['Pregunta', 'No saber', 'Beneficio', 'Elegir', 'Inseguridad'] },
      { w: 'Esperanza', t: ['Última', 'Futuro', 'Perder', 'Ilusión', 'Fe'] },
      { w: 'Sorpresa', t: ['Fiesta', 'Regalo', 'Inesperado', 'Cara', 'Susto'] },
      { w: 'Educación', t: ['Colegio', 'Modales', 'Enseñar', 'Padres', 'Buenos días'] },
      { w: 'Democracia', t: ['Votar', 'Urnas', 'Pueblo', 'Elecciones', 'Grecia'] },
      { w: 'Economía', t: ['Dinero', 'Crisis', 'Mercado', 'País', 'Bolsa'] },
      { w: 'Inflación', t: ['Precios', 'Subir', 'Dinero', 'Cesta', 'Crisis'] },
      { w: 'Cultura', t: ['Museo', 'Libros', 'Pueblo', 'Costumbres', 'Arte'] },
      { w: 'Tradición', t: ['Siempre', 'Abuelos', 'Fiesta', 'Pueblo', 'Costumbre'] },
      { w: 'Religión', t: ['Dios', 'Iglesia', 'Rezar', 'Fe', 'Creer'] },
      { w: 'Filosofía', t: ['Pensar', 'Grecia', 'Preguntas', 'Sócrates', 'Existir'] },
      { w: 'Ciencia', t: ['Experimento', 'Laboratorio', 'Método', 'Investigar', 'Bata'] },
      { w: 'Gravedad', t: ['Caer', 'Newton', 'Manzana', 'Peso', 'Suelo'] },
      { w: 'Evolución', t: ['Darwin', 'Monos', 'Especies', 'Cambiar', 'Millones'] },
      { w: 'Infinito', t: ['Nunca acaba', 'Ocho', 'Números', 'Universo', 'Límite'] },
      { w: 'Karma', t: ['Devolver', 'Bueno', 'Malo', 'Vida', 'Merecer'] },
      { w: 'Déjà vu', t: ['Ya visto', 'Antes', 'Sensación', 'Repetido', 'Memoria'] },
      { w: 'Ironía', t: ['Contrario', 'Burla', 'Decir', 'Tono', 'Sarcasmo'] },
      { w: 'Rumor', t: ['Corre', 'Cotilleo', 'Boca', 'Falso', 'Gente'] },
      { w: 'Prejuicio', t: ['Juzgar', 'Antes', 'Idea', 'Conocer', 'Tópico'] },
      { w: 'Rencor', t: ['Guardar', 'Perdonar', 'Enfado', 'Años', 'Odio'] }
    ]
  },

  oficios: {
    id: 'oficios',
    name: 'Profesiones y oficios',
    emoji: '👷',
    desc: 'A qué se dedica la gente.',
    cards: [
      { w: 'Bombero', t: ['Fuego', 'Manguera', 'Camión', 'Rescate', 'Casco'] },
      { w: 'Policía', t: ['Uniforme', 'Ladrón', 'Detener', 'Placa', 'Comisaría'] },
      { w: 'Profesor', t: ['Clase', 'Alumnos', 'Pizarra', 'Explicar', 'Colegio'] },
      { w: 'Cocinero', t: ['Fogones', 'Restaurante', 'Gorro', 'Platos', 'Recetas'] },
      { w: 'Panadero', t: ['Bollos', 'Horno', 'Harina', 'Madrugar', 'Barra'] },
      { w: 'Carnicero', t: ['Carne', 'Cuchillo', 'Filetes', 'Mostrador', 'Mercado'] },
      { w: 'Pescadero', t: ['Pescado', 'Hielo', 'Mercado', 'Escamas', 'Lonja'] },
      { w: 'Camarero', t: ['Bandeja', 'Mesas', 'Bar', 'Pedido', 'Propina'] },
      { w: 'Fontanero', t: ['Tuberías', 'Agua', 'Fuga', 'Grifo', 'Avería'] },
      { w: 'Electricista', t: ['Cables', 'Luz', 'Enchufe', 'Cuadro', 'Corriente'] },
      { w: 'Albañil', t: ['Ladrillos', 'Obra', 'Cemento', 'Casco', 'Andamio'] },
      { w: 'Carpintero', t: ['Madera', 'Muebles', 'Sierra', 'Serrín', 'Taller'] },
      { w: 'Pintor', t: ['Brocha', 'Pared', 'Rodillo', 'Cuadro', 'Escalera'] },
      { w: 'Mecánico', t: ['Coche', 'Taller', 'Motor', 'Grasa', 'Avería'] },
      { w: 'Taxista', t: ['Coche', 'Cliente', 'Carrera', 'Ciudad', 'Amarillo'] },
      { w: 'Piloto', t: ['Avión', 'Cabina', 'Volar', 'Uniforme', 'Despegar'] },
      { w: 'Azafata', t: ['Avión', 'Pasajeros', 'Uniforme', 'Bandeja', 'Seguridad'] },
      { w: 'Marinero', t: ['Barco', 'Mar', 'Cubierta', 'Puerto', 'Nudos'] },
      { w: 'Pescador', t: ['Caña', 'Río', 'Anzuelo', 'Barca', 'Paciencia'] },
      { w: 'Agricultor', t: ['Campo', 'Cosecha', 'Tractor', 'Tierra', 'Semillas'] },
      { w: 'Ganadero', t: ['Vacas', 'Establo', 'Campo', 'Leche', 'Rebaño'] },
      { w: 'Pastor', t: ['Ovejas', 'Monte', 'Rebaño', 'Perro', 'Cayado'] },
      { w: 'Veterinario', t: ['Animales', 'Consulta', 'Mascota', 'Vacuna', 'Clínica'] },
      { w: 'Enfermera', t: ['Hospital', 'Cuidar', 'Turno', 'Inyección', 'Bata'] },
      { w: 'Cirujano', t: ['Quirófano', 'Operar', 'Bisturí', 'Guantes', 'Hospital'] },
      { w: 'Farmacéutico', t: ['Medicinas', 'Mostrador', 'Receta', 'Bata', 'Botica'] },
      { w: 'Psicólogo', t: ['Consulta', 'Hablar', 'Diván', 'Mente', 'Terapia'] },
      { w: 'Abogado', t: ['Juicio', 'Cliente', 'Ley', 'Defender', 'Toga'] },
      { w: 'Juez', t: ['Juicio', 'Martillo', 'Sentencia', 'Toga', 'Tribunal'] },
      { w: 'Contable', t: ['Números', 'Cuentas', 'Facturas', 'Empresa', 'Hacienda'] },
      { w: 'Banquero', t: ['Banco', 'Dinero', 'Préstamo', 'Traje', 'Intereses'] },
      { w: 'Recepcionista', t: ['Mostrador', 'Llamadas', 'Hotel', 'Sonrisa', 'Visitas'] },
      { w: 'Cajero', t: ['Caja', 'Cobrar', 'Supermercado', 'Cola', 'Ticket'] },
      { w: 'Dependiente', t: ['Tienda', 'Clientes', 'Vender', 'Mostrador', 'Talla'] },
      { w: 'Repartidor', t: ['Paquetes', 'Moto', 'Puerta', 'Timbre', 'Pedido'] },
      { w: 'Cartero', t: ['Cartas', 'Buzón', 'Sellos', 'Reparto', 'Bicicleta'] },
      { w: 'Barrendero', t: ['Calle', 'Escoba', 'Basura', 'Madrugada', 'Chaleco'] },
      { w: 'Jardinero', t: ['Plantas', 'Podar', 'Riego', 'Césped', 'Tijeras'] },
      { w: 'Conserje', t: ['Portal', 'Llaves', 'Edificio', 'Vecinos', 'Garita'] },
      { w: 'Vigilante', t: ['Seguridad', 'Noche', 'Cámaras', 'Ronda', 'Uniforme'] },
      { w: 'Militar', t: ['Ejército', 'Uniforme', 'Órdenes', 'Cuartel', 'Desfile'] },
      { w: 'Soldado', t: ['Guerra', 'Fusil', 'Uniforme', 'Trinchera', 'Órdenes'] },
      { w: 'Socorrista', t: ['Piscina', 'Silla', 'Silbato', 'Ahogarse', 'Playa'] },
      { w: 'Periodista', t: ['Noticias', 'Micrófono', 'Preguntas', 'Periódico', 'Reportaje'] },
      { w: 'Fotógrafo', t: ['Fotos', 'Objetivo', 'Boda', 'Flash', 'Estudio'] },
      { w: 'Locutor', t: ['Radio', 'Voz', 'Micrófono', 'Emisora', 'Hablar'] },
      { w: 'Presentador', t: ['Programa', 'Televisión', 'Público', 'Micrófono', 'Plató'] },
      { w: 'Actor', t: ['Película', 'Papel', 'Guion', 'Escenario', 'Fama'] },
      { w: 'Director de cine', t: ['Rodaje', 'Acción', 'Silla', 'Película', 'Cortar'] },
      { w: 'Guionista', t: ['Historia', 'Escribir', 'Película', 'Diálogos', 'Ideas'] },
      { w: 'Escritor', t: ['Libros', 'Novela', 'Escribir', 'Editorial', 'Ideas'] },
      { w: 'Poeta', t: ['Versos', 'Rima', 'Poema', 'Musa', 'Escribir'] },
      { w: 'Traductor', t: ['Idiomas', 'Texto', 'Diccionario', 'Cambiar', 'Palabras'] },
      { w: 'Bibliotecario', t: ['Libros', 'Silencio', 'Estanterías', 'Préstamo', 'Fichas'] },
      { w: 'Arquitecto', t: ['Planos', 'Edificios', 'Diseñar', 'Obra', 'Maqueta'] },
      { w: 'Ingeniero', t: ['Cálculos', 'Obras', 'Carrera', 'Proyectos', 'Técnico'] },
      { w: 'Programador', t: ['Código', 'Ordenador', 'Errores', 'Pantalla', 'Café'] },
      { w: 'Diseñador', t: ['Dibujar', 'Ideas', 'Logotipo', 'Colores', 'Cliente'] },
      { w: 'Científico', t: ['Laboratorio', 'Bata', 'Experimentos', 'Investigar', 'Descubrir'] },
      { w: 'Arqueólogo', t: ['Excavar', 'Ruinas', 'Huesos', 'Pincel', 'Antigüedades'] },
      { w: 'Minero', t: ['Mina', 'Casco', 'Carbón', 'Túnel', 'Linterna'] },
      { w: 'Leñador', t: ['Hacha', 'Árboles', 'Bosque', 'Troncos', 'Cuadros'] },
      { w: 'Herrero', t: ['Hierro', 'Fragua', 'Martillo', 'Yunque', 'Herradura'] },
      { w: 'Zapatero', t: ['Zapatos', 'Suela', 'Arreglar', 'Cuero', 'Cordones'] },
      { w: 'Sastre', t: ['Traje', 'Medidas', 'Aguja', 'Tela', 'Arreglos'] },
      { w: 'Relojero', t: ['Relojes', 'Lupa', 'Piezas', 'Arreglar', 'Precisión'] },
      { w: 'Joyero', t: ['Oro', 'Anillos', 'Escaparate', 'Piedras', 'Tienda'] },
      { w: 'Óptico', t: ['Gafas', 'Vista', 'Graduar', 'Cristales', 'Tienda'] },
      { w: 'Fisioterapeuta', t: ['Masaje', 'Espalda', 'Camilla', 'Lesión', 'Recuperar'] },
      { w: 'Camionero', t: ['Volante', 'Carretera', 'Ruta', 'Carga', 'Área de servicio'] },
      { w: 'Monje', t: ['Monasterio', 'Hábito', 'Silencio', 'Rezar', 'Cerveza'] },
      { w: 'Cura', t: ['Iglesia', 'Misa', 'Sotana', 'Confesión', 'Domingo'] },
      { w: 'Monja', t: ['Convento', 'Hábito', 'Rezar', 'Colegio', 'Silencio'] },
      { w: 'Torero', t: ['Toro', 'Plaza', 'Traje de luces', 'Capote', 'Faena'] },
      { w: 'Malabarista', t: ['Bolas', 'Circo', 'Aire', 'Equilibrio', 'Espectáculo'] },
      { w: 'Cantante', t: ['Voz', 'Escenario', 'Micrófono', 'Disco', 'Público'] },
      { w: 'Bailarín', t: ['Baile', 'Escenario', 'Ritmo', 'Cuerpo', 'Ensayo'] },
      { w: 'DJ', t: ['Música', 'Discoteca', 'Mezclar', 'Cabina', 'Pinchar'] },
      { w: 'Modelo', t: ['Pasarela', 'Desfile', 'Fotos', 'Ropa', 'Altura'] },
      { w: 'Influencer', t: ['Redes', 'Seguidores', 'Móvil', 'Publicidad', 'Fotos'] }
    ]
  },
  ciencia: {
    id: 'ciencia',
    name: 'Ciencia y cuerpo',
    emoji: '🔬',
    desc: 'El cuerpo, el laboratorio y el espacio.',
    cards: [
      { w: 'Corazón', t: ['Latir', 'Pecho', 'Sangre', 'Amor', 'Rojo'] },
      { w: 'Cerebro', t: ['Cabeza', 'Pensar', 'Neuronas', 'Inteligencia', 'Arrugas'] },
      { w: 'Pulmones', t: ['Respirar', 'Aire', 'Pecho', 'Tabaco', 'Dos'] },
      { w: 'Estómago', t: ['Comida', 'Digerir', 'Tripa', 'Ácido', 'Ruido'] },
      { w: 'Hígado', t: ['Alcohol', 'Órgano', 'Filtrar', 'Cirrosis', 'Paté'] },
      { w: 'Riñón', t: ['Orina', 'Órgano', 'Piedra', 'Filtrar', 'Dos'] },
      { w: 'Esqueleto', t: ['Huesos', 'Calavera', 'Cuerpo', 'Halloween', 'Radiografía'] },
      { w: 'Hueso', t: ['Roto', 'Perro', 'Esqueleto', 'Duro', 'Calcio'] },
      { w: 'Músculo', t: ['Fuerza', 'Bíceps', 'Gimnasio', 'Contraer', 'Fibra'] },
      { w: 'Sangre', t: ['Rojo', 'Venas', 'Donar', 'Herida', 'Grupo'] },
      { w: 'Vena', t: ['Sangre', 'Brazo', 'Azul', 'Aguja', 'Marcar'] },
      { w: 'Piel', t: ['Cuerpo', 'Tocar', 'Sol', 'Órgano', 'Suave'] },
      { w: 'Uña', t: ['Dedo', 'Cortar', 'Morder', 'Pintar', 'Crecer'] },
      { w: 'Lengua', t: ['Boca', 'Sabor', 'Hablar', 'Sacar', 'Húmeda'] },
      { w: 'Ojo', t: ['Ver', 'Pupila', 'Parpadear', 'Color', 'Cara'] },
      { w: 'Oreja', t: ['Oír', 'Cabeza', 'Pendiente', 'Lóbulo', 'Sordo'] },
      { w: 'Nariz', t: ['Oler', 'Cara', 'Moco', 'Agujeros', 'Pinocho'] },
      { w: 'Boca', t: ['Hablar', 'Comer', 'Labios', 'Cara', 'Abrir'] },
      { w: 'Rodilla', t: ['Pierna', 'Doblar', 'Articulación', 'Caerse', 'Menisco'] },
      { w: 'Codo', t: ['Brazo', 'Doblar', 'Articulación', 'Golpe', 'Apoyar'] },
      { w: 'Hombro', t: ['Brazo', 'Cuerpo', 'Cargar', 'Llorar', 'Encoger'] },
      { w: 'Espalda', t: ['Dolor', 'Detrás', 'Columna', 'Masaje', 'Cargar'] },
      { w: 'Ombligo', t: ['Barriga', 'Centro', 'Cordón', 'Agujero', 'Nacer'] },
      { w: 'Cejas', t: ['Ojos', 'Pelo', 'Depilar', 'Cara', 'Levantar'] },
      { w: 'Pestañas', t: ['Ojos', 'Rímel', 'Pelo', 'Parpadear', 'Postizas'] },
      { w: 'Tobillo', t: ['Pie', 'Torcerse', 'Articulación', 'Hinchado', 'Pierna'] },
      { w: 'Garganta', t: ['Cuello', 'Tragar', 'Dolor', 'Voz', 'Anginas'] },
      { w: 'Pulso', t: ['Latidos', 'Muñeca', 'Contar', 'Firme', 'Corazón'] },
      { w: 'Respiración', t: ['Aire', 'Pulmones', 'Boca', 'Profunda', 'Contener'] },
      { w: 'Digestión', t: ['Comida', 'Estómago', 'Corte', 'Lenta', 'Siesta'] },
      { w: 'Alergia', t: ['Polen', 'Estornudo', 'Picor', 'Primavera', 'Antihistamínico'] },
      { w: 'Gripe', t: ['Fiebre', 'Cama', 'Virus', 'Invierno', 'Manta'] },
      { w: 'Tos', t: ['Garganta', 'Sonido', 'Jarabe', 'Molesta', 'Seca'] },
      { w: 'Herida', t: ['Sangre', 'Corte', 'Curar', 'Tirita', 'Doler'] },
      { w: 'Venda', t: ['Herida', 'Rollo', 'Enrollar', 'Momia', 'Blanca'] },
      { w: 'Escayola', t: ['Roto', 'Brazo', 'Blanca', 'Firmar', 'Picor'] },
      { w: 'Radiografía', t: ['Huesos', 'Placa', 'Hospital', 'Rayos', 'Negro'] },
      { w: 'Microscopio', t: ['Ver', 'Pequeño', 'Laboratorio', 'Lente', 'Muestra'] },
      { w: 'Telescopio', t: ['Estrellas', 'Ver', 'Lejos', 'Noche', 'Observatorio'] },
      { w: 'Átomo', t: ['Pequeño', 'Materia', 'Núcleo', 'Electrones', 'Bomba'] },
      { w: 'Molécula', t: ['Átomos', 'Química', 'Unión', 'Agua', 'Pequeña'] },
      { w: 'Célula', t: ['Cuerpo', 'Microscopio', 'Dividirse', 'Núcleo', 'Pequeña'] },
      { w: 'ADN', t: ['Genes', 'Herencia', 'Doble hélice', 'Prueba', 'Padres'] },
      { w: 'Bacteria', t: ['Microbio', 'Infección', 'Antibiótico', 'Pequeña', 'Higiene'] },
      { w: 'Experimento', t: ['Laboratorio', 'Probar', 'Resultado', 'Científico', 'Hipótesis'] },
      { w: 'Laboratorio', t: ['Bata', 'Probetas', 'Científicos', 'Análisis', 'Sala'] },
      { w: 'Probeta', t: ['Cristal', 'Líquido', 'Laboratorio', 'Tubo', 'Medir'] },
      { w: 'Imán', t: ['Atraer', 'Nevera', 'Metal', 'Polos', 'Pegar'] },
      { w: 'Electricidad', t: ['Enchufe', 'Corriente', 'Rayo', 'Cables', 'Calambre'] },
      { w: 'Energía', t: ['Fuerza', 'Renovable', 'Consumo', 'Solar', 'Pilas'] },
      { w: 'Velocidad', t: ['Rápido', 'Kilómetros', 'Radar', 'Correr', 'Límite'] },
      { w: 'Peso', t: ['Kilos', 'Báscula', 'Pesado', 'Gravedad', 'Medir'] },
      { w: 'Temperatura', t: ['Grados', 'Calor', 'Frío', 'Medir', 'Ambiente'] },
      { w: 'Termómetro', t: ['Grados', 'Fiebre', 'Medir', 'Mercurio', 'Axila'] },
      { w: 'Báscula', t: ['Kilos', 'Subirse', 'Baño', 'Pesar', 'Dieta'] },
      { w: 'Planeta', t: ['Órbita', 'Espacio', 'Tierra', 'Redondo', 'Sistema solar'] },
      { w: 'Sol', t: ['Calor', 'Amarillo', 'Día', 'Quemar', 'Centro'] },
      { w: 'Marte', t: ['Rojo', 'Planeta', 'Espacio', 'Marcianos', 'Cuarto'] },
      { w: 'Cometa', t: ['Cola', 'Espacio', 'Halley', 'Hielo', 'Pasar'] },
      { w: 'Eclipse', t: ['Sol', 'Luna', 'Tapar', 'Sombra', 'Gafas'] },
      { w: 'Satélite', t: ['Órbita', 'Espacio', 'Señal', 'Antena', 'Girar'] },
      { w: 'Cohete', t: ['Espacio', 'Despegar', 'Fuego', 'NASA', 'Cuenta atrás'] },
      { w: 'Astronauta', t: ['Espacio', 'Traje', 'Casco', 'Ingravidez', 'Luna'] },
      { w: 'Oxígeno', t: ['Aire', 'Respirar', 'Gas', 'Bombona', 'Vida'] },
      { w: 'Hielo', t: ['Frío', 'Agua', 'Cubito', 'Derretir', 'Resbalar'] },
      { w: 'Vapor', t: ['Agua', 'Caliente', 'Olla', 'Nube', 'Plancha'] },
      { w: 'Fuego', t: ['Llamas', 'Quemar', 'Calor', 'Humo', 'Cerilla'] },
      { w: 'Humo', t: ['Fuego', 'Gris', 'Chimenea', 'Toser', 'Subir'] },
      { w: 'Óxido', t: ['Hierro', 'Naranja', 'Húmedo', 'Viejo', 'Corroer'] },
      { w: 'Fósil', t: ['Piedra', 'Millones', 'Huella', 'Museo', 'Excavar'] },
      { w: 'Dinosaurio', t: ['Extinto', 'Gigante', 'Meteorito', 'Museo', 'Rugido'] },
      { w: 'Clima', t: ['Tiempo', 'Cambio', 'Lluvia', 'Temperatura', 'Zona'] },
      { w: 'Reciclaje', t: ['Contenedor', 'Colores', 'Basura', 'Separar', 'Papel'] },
      { w: 'Contaminación', t: ['Humo', 'Ciudad', 'Aire', 'Fábricas', 'Sucio'] },
      { w: 'Sombra', t: ['Sol', 'Oscuro', 'Seguir', 'Silueta', 'Fresco'] },
      { w: 'Eco', t: ['Montaña', 'Repetir', 'Gritar', 'Cueva', 'Sonido'] },
      { w: 'Palanca', t: ['Levantar', 'Fuerza', 'Barra', 'Apoyo', 'Máquina'] },
      { w: 'Espejismo', t: ['Desierto', 'Agua', 'Ver', 'Falso', 'Sed'] },
      { w: 'Gemelos', t: ['Iguales', 'Hermanos', 'Dos', 'Confundir', 'Nacer'] },
      { w: 'Huella dactilar', t: ['Dedo', 'Única', 'Policía', 'Móvil', 'Marca'] }
    ]
  },
  cultura: {
    id: 'cultura',
    name: 'Historia y cultura',
    emoji: '🏛️',
    desc: 'Personajes, arte, música clásica y letras.',
    cards: [
      { w: 'Napoleón', t: ['Francia', 'Bajito', 'Emperador', 'Waterloo', 'Mano'] },
      { w: 'Cleopatra', t: ['Egipto', 'Reina', 'Nilo', 'Serpiente', 'Flequillo'] },
      { w: 'Julio César', t: ['Roma', 'Emperador', 'Bruto', 'Ensalada', 'Puñaladas'] },
      { w: 'Cristóbal Colón', t: ['América', 'Carabelas', 'Descubrir', '1492', 'Huevo'] },
      { w: 'Cervantes', t: ['Quijote', 'Escritor', 'Manco', 'Español', 'Libro'] },
      { w: 'Don Quijote', t: ['Molinos', 'Sancho', 'Mancha', 'Lanza', 'Rocinante'] },
      { w: 'Shakespeare', t: ['Inglés', 'Teatro', 'Romeo', 'Hamlet', 'Escritor'] },
      { w: 'Picasso', t: ['Cubismo', 'Málaga', 'Guernica', 'Pintor', 'Cuadros'] },
      { w: 'Van Gogh', t: ['Oreja', 'Girasoles', 'Pintor', 'Holandés', 'Estrellada'] },
      { w: 'Dalí', t: ['Bigote', 'Relojes', 'Surrealismo', 'Figueres', 'Pintor'] },
      { w: 'Frida Kahlo', t: ['México', 'Cejas', 'Autorretratos', 'Pintora', 'Flores'] },
      { w: 'La Gioconda', t: ['Sonrisa', 'Louvre', 'Leonardo', 'Cuadro', 'Misterio'] },
      { w: 'Miguel Ángel', t: ['Capilla Sixtina', 'David', 'Escultor', 'Techo', 'Italia'] },
      { w: 'Leonardo da Vinci', t: ['Inventor', 'Gioconda', 'Renacimiento', 'Cuadernos', 'Italia'] },
      { w: 'Beethoven', t: ['Sordo', 'Sinfonía', 'Piano', 'Alemán', 'Compositor'] },
      { w: 'Mozart', t: ['Niño prodigio', 'Peluca', 'Compositor', 'Austria', 'Réquiem'] },
      { w: 'Einstein', t: ['Relatividad', 'Pelo', 'Físico', 'Lengua', 'Genio'] },
      { w: 'Newton', t: ['Manzana', 'Gravedad', 'Físico', 'Árbol', 'Leyes'] },
      { w: 'Marie Curie', t: ['Radiactividad', 'Nobel', 'Científica', 'Polonia', 'Radio'] },
      { w: 'Darwin', t: ['Evolución', 'Especies', 'Galápagos', 'Barba', 'Monos'] },
      { w: 'Gandhi', t: ['India', 'Paz', 'Gafas', 'Ayuno', 'Independencia'] },
      { w: 'Nelson Mandela', t: ['Sudáfrica', 'Cárcel', 'Apartheid', 'Presidente', 'Nobel'] },
      { w: 'Martin Luther King', t: ['Sueño', 'Discurso', 'Derechos', 'Estados Unidos', 'Igualdad'] },
      { w: 'Juana de Arco', t: ['Francia', 'Hoguera', 'Doncella', 'Voces', 'Guerra'] },
      { w: 'Vikingos', t: ['Barcos', 'Cascos', 'Noruega', 'Saqueo', 'Barbas'] },
      { w: 'Gladiador', t: ['Coliseo', 'Espada', 'Roma', 'Arena', 'Pulgar'] },
      { w: 'Caballero', t: ['Armadura', 'Caballo', 'Edad Media', 'Lanza', 'Honor'] },
      { w: 'Rey Arturo', t: ['Espada', 'Piedra', 'Mesa redonda', 'Merlín', 'Camelot'] },
      { w: 'Robin Hood', t: ['Arco', 'Bosque', 'Ricos', 'Pobres', 'Sherwood'] },
      { w: 'Guillotina', t: ['Cuchilla', 'Cabeza', 'Francia', 'Revolución', 'Caer'] },
      { w: 'Imprenta', t: ['Libros', 'Gutenberg', 'Tinta', 'Copias', 'Letras'] },
      { w: 'Máquina de vapor', t: ['Industrial', 'Carbón', 'Tren', 'Revolución', 'Pistón'] },
      { w: 'Carabela', t: ['Colón', 'Velas', 'Madera', 'América', 'Barco'] },
      { w: 'Faraón', t: ['Egipto', 'Pirámide', 'Rey', 'Tumba', 'Máscara'] },
      { w: 'Momia', t: ['Vendas', 'Egipto', 'Tumba', 'Museo', 'Maldición'] },
      { w: 'Esfinge', t: ['Egipto', 'León', 'Enigma', 'Piedra', 'Cara'] },
      { w: 'Catedral', t: ['Iglesia', 'Gótico', 'Torres', 'Vidrieras', 'Grande'] },
      { w: 'Monasterio', t: ['Monjes', 'Silencio', 'Claustro', 'Montaña', 'Rezar'] },
      { w: 'Manuscrito', t: ['A mano', 'Antiguo', 'Monjes', 'Papel', 'Copiar'] },
      { w: 'Pergamino', t: ['Rollo', 'Antiguo', 'Piel', 'Escribir', 'Sello'] },
      { w: 'Jeroglífico', t: ['Egipto', 'Dibujos', 'Escritura', 'Piedra', 'Descifrar'] },
      { w: 'Alfabeto', t: ['Letras', 'Orden', 'Aprender', 'Idioma', 'Veintisiete'] },
      { w: 'Escultura', t: ['Piedra', 'Museo', 'Cincel', 'Estatua', 'Mármol'] },
      { w: 'Retrato', t: ['Cara', 'Cuadro', 'Posar', 'Pintar', 'Parecido'] },
      { w: 'Acuarela', t: ['Agua', 'Pintura', 'Papel', 'Suave', 'Pincel'] },
      { w: 'Pincel', t: ['Pintar', 'Pelos', 'Mango', 'Cuadro', 'Mojar'] },
      { w: 'Lienzo', t: ['Tela', 'Pintar', 'Bastidor', 'Blanco', 'Cuadro'] },
      { w: 'Grafiti', t: ['Pared', 'Espray', 'Calle', 'Firma', 'Ilegal'] },
      { w: 'Ópera', t: ['Cantar', 'Teatro', 'Italiana', 'Aguda', 'Palco'] },
      { w: 'Ballet', t: ['Puntillas', 'Tutú', 'Bailar', 'Cisne', 'Clásico'] },
      { w: 'Orquesta', t: ['Director', 'Instrumentos', 'Batuta', 'Sinfónica', 'Concierto'] },
      { w: 'Violín', t: ['Cuerdas', 'Arco', 'Barbilla', 'Clásico', 'Agudo'] },
      { w: 'Piano', t: ['Teclas', 'Blancas', 'Negras', 'Cola', 'Dedos'] },
      { w: 'Guitarra', t: ['Cuerdas', 'Rasgueo', 'Española', 'Mástil', 'Púa'] },
      { w: 'Trompeta', t: ['Soplar', 'Metal', 'Pistones', 'Banda', 'Dorada'] },
      { w: 'Tambor', t: ['Golpear', 'Baquetas', 'Ritmo', 'Piel', 'Banda'] },
      { w: 'Flauta', t: ['Soplar', 'Agujeros', 'Colegio', 'Dulce', 'Dedos'] },
      { w: 'Acordeón', t: ['Fuelle', 'Estirar', 'Teclas', 'Calle', 'Verbena'] },
      { w: 'Poesía', t: ['Versos', 'Rima', 'Poeta', 'Sentimientos', 'Estrofa'] },
      { w: 'Novela', t: ['Libro', 'Capítulos', 'Escritor', 'Personajes', 'Larga'] },
      { w: 'Cuento', t: ['Niños', 'Corto', 'Érase una vez', 'Dormir', 'Hadas'] },
      { w: 'Fábula', t: ['Animales', 'Moraleja', 'Corta', 'Enseñanza', 'Esopo'] },
      { w: 'Refrán', t: ['Dicho', 'Sabiduría', 'Abuela', 'Corto', 'Popular'] },
      { w: 'Diccionario', t: ['Palabras', 'Significado', 'Buscar', 'Gordo', 'Orden'] },
      { w: 'Ortografía', t: ['Faltas', 'Escribir', 'Tildes', 'Reglas', 'Corregir'] },
      { w: 'Caligrafía', t: ['Letra', 'Bonita', 'Mano', 'Pluma', 'Trazo'] },
      { w: 'Teatro', t: ['Escenario', 'Telón', 'Obra', 'Butacas', 'Actores'] },
      { w: 'Marioneta', t: ['Hilos', 'Muñeco', 'Mover', 'Títere', 'Espectáculo'] },
      { w: 'Circo', t: ['Carpa', 'Payasos', 'Trapecio', 'Pista', 'Función'] },
      { w: 'Trono', t: ['Rey', 'Silla', 'Palacio', 'Corona', 'Sentarse'] },
      { w: 'Corona', t: ['Rey', 'Cabeza', 'Oro', 'Joyas', 'Reinar'] },
      { w: 'Espada', t: ['Filo', 'Caballero', 'Vaina', 'Duelo', 'Empuñadura'] },
      { w: 'Escudo', t: ['Proteger', 'Brazo', 'Caballero', 'Golpes', 'Emblema'] },
      { w: 'Armadura', t: ['Metal', 'Caballero', 'Proteger', 'Pesada', 'Visera'] },
      { w: 'Torre', t: ['Alta', 'Castillo', 'Subir', 'Vigilar', 'Escaleras'] },
      { w: 'Antorcha', t: ['Fuego', 'Palo', 'Llevar', 'Cueva', 'Olímpica'] },
      { w: 'Mapamundi', t: ['Países', 'Pared', 'Continentes', 'Colgar', 'Mundo'] },
      { w: 'Tesoro', t: ['Cofre', 'Oro', 'Enterrado', 'Mapa', 'Piratas'] },
      { w: 'Leyenda', t: ['Historia', 'Antigua', 'Contar', 'Pueblo', 'Real'] },
      { w: 'Bandera', t: ['Colores', 'País', 'Mástil', 'Ondear', 'Símbolo'] }
    ]
  },
  taller: {
    id: 'taller',
    name: 'Motor y taller',
    emoji: '🔧',
    desc: 'Vehículos, máquinas y herramientas.',
    cards: [
      { w: 'Coche', t: ['Ruedas', 'Conducir', 'Volante', 'Motor', 'Garaje'] },
      { w: 'Moto', t: ['Dos ruedas', 'Casco', 'Manillar', 'Ruido', 'Conducir'] },
      { w: 'Bicicleta', t: ['Pedales', 'Cadena', 'Manillar', 'Ruedas', 'Timbre'] },
      { w: 'Camión', t: ['Carga', 'Grande', 'Carretera', 'Remolque', 'Conductor'] },
      { w: 'Furgoneta', t: ['Reparto', 'Carga', 'Puertas', 'Blanca', 'Obreros'] },
      { w: 'Ambulancia', t: ['Sirena', 'Hospital', 'Urgencia', 'Camilla', 'Blanca'] },
      { w: 'Tractor', t: ['Campo', 'Ruedas grandes', 'Agricultor', 'Lento', 'Arar'] },
      { w: 'Excavadora', t: ['Obra', 'Pala', 'Cavar', 'Tierra', 'Oruga'] },
      { w: 'Grúa', t: ['Levantar', 'Obra', 'Brazo', 'Alta', 'Cable'] },
      { w: 'Hormigonera', t: ['Girar', 'Cemento', 'Obra', 'Mezclar', 'Bombo'] },
      { w: 'Barco', t: ['Mar', 'Flotar', 'Puerto', 'Cubierta', 'Ancla'] },
      { w: 'Velero', t: ['Viento', 'Velas', 'Mar', 'Mástil', 'Regata'] },
      { w: 'Canoa', t: ['Remo', 'Río', 'Estrecha', 'Volcar', 'Dos'] },
      { w: 'Submarino', t: ['Bajo el agua', 'Periscopio', 'Amarillo', 'Sumergir', 'Torpedo'] },
      { w: 'Ferry', t: ['Coches', 'Isla', 'Travesía', 'Puerto', 'Cubierta'] },
      { w: 'Yate', t: ['Lujo', 'Rico', 'Puerto', 'Blanco', 'Fiesta'] },
      { w: 'Helicóptero', t: ['Hélices', 'Volar', 'Rescate', 'Ruido', 'Aterrizar'] },
      { w: 'Globo aerostático', t: ['Cesta', 'Aire caliente', 'Volar', 'Colores', 'Subir'] },
      { w: 'Paracaídas', t: ['Saltar', 'Avión', 'Abrir', 'Caer', 'Cuerdas'] },
      { w: 'Tranvía', t: ['Raíles', 'Ciudad', 'Cable', 'Parada', 'Vagón'] },
      { w: 'Teleférico', t: ['Cable', 'Montaña', 'Cabina', 'Subir', 'Vistas'] },
      { w: 'Monopatín', t: ['Tabla', 'Ruedas', 'Trucos', 'Rampa', 'Empujar'] },
      { w: 'Trineo', t: ['Nieve', 'Bajar', 'Renos', 'Cuesta', 'Deslizar'] },
      { w: 'Remolque', t: ['Enganchar', 'Arrastrar', 'Coche', 'Carga', 'Detrás'] },
      { w: 'Volante', t: ['Girar', 'Manos', 'Conducir', 'Redondo', 'Coche'] },
      { w: 'Freno', t: ['Parar', 'Pedal', 'Pastillas', 'Chirrido', 'Mano'] },
      { w: 'Acelerador', t: ['Pedal', 'Velocidad', 'Pisar', 'Derecha', 'Motor'] },
      { w: 'Marcha atrás', t: ['Retroceder', 'Pitido', 'Aparcar', 'Espejo', 'Cuello'] },
      { w: 'Retrovisor', t: ['Espejo', 'Mirar', 'Detrás', 'Coche', 'Plegar'] },
      { w: 'Cinturón de seguridad', t: ['Abrochar', 'Coche', 'Pitido', 'Multa', 'Pecho'] },
      { w: 'Airbag', t: ['Bolsa', 'Golpe', 'Hinchar', 'Volante', 'Proteger'] },
      { w: 'Neumático', t: ['Goma', 'Rueda', 'Dibujo', 'Aire', 'Cambiar'] },
      { w: 'Pinchazo', t: ['Rueda', 'Aire', 'Clavo', 'Parche', 'Parado'] },
      { w: 'Motor', t: ['Arrancar', 'Pistones', 'Capó', 'Ruido', 'Caballos'] },
      { w: 'Radiador', t: ['Agua', 'Enfriar', 'Coche', 'Calor', 'Rejilla'] },
      { w: 'Tubo de escape', t: ['Humo', 'Detrás', 'Ruido', 'Gases', 'Coche'] },
      { w: 'Claxon', t: ['Pitar', 'Volante', 'Ruido', 'Atasco', 'Aviso'] },
      { w: 'Intermitente', t: ['Girar', 'Parpadear', 'Naranja', 'Palanca', 'Aviso'] },
      { w: 'Faros', t: ['Luz', 'Delante', 'Noche', 'Encender', 'Largas'] },
      { w: 'Matrícula', t: ['Letras', 'Números', 'Placa', 'Coche', 'Identificar'] },
      { w: 'Carné de conducir', t: ['Examen', 'Puntos', 'Coche', 'Tarjeta', 'Autoescuela'] },
      { w: 'Autoescuela', t: ['Prácticas', 'Profesor', 'Examen', 'Coche', 'Teórico'] },
      { w: 'Aparcamiento', t: ['Plazas', 'Coche', 'Dejar', 'Sótano', 'Buscar'] },
      { w: 'Parquímetro', t: ['Monedas', 'Ticket', 'Zona azul', 'Tiempo', 'Calle'] },
      { w: 'Peaje', t: ['Pagar', 'Autopista', 'Barrera', 'Cabina', 'Ticket'] },
      { w: 'Autopista', t: ['Carriles', 'Rápido', 'Salidas', 'Coches', 'Kilómetros'] },
      { w: 'Rotonda', t: ['Girar', 'Redonda', 'Salida', 'Ceder', 'Coches'] },
      { w: 'Túnel', t: ['Montaña', 'Oscuro', 'Pasar', 'Luces', 'Largo'] },
      { w: 'Paso de cebra', t: ['Rayas', 'Cruzar', 'Peatones', 'Blanco', 'Calle'] },
      { w: 'Acera', t: ['Andar', 'Calle', 'Bordillo', 'Peatones', 'Baldosas'] },
      { w: 'Carril bici', t: ['Bicicletas', 'Ciudad', 'Pintado', 'Separado', 'Circular'] },
      { w: 'Taller', t: ['Coches', 'Mecánico', 'Reparar', 'Herramientas', 'Elevador'] },
      { w: 'Chatarra', t: ['Metal', 'Viejo', 'Desguace', 'Amontonar', 'Vender'] },
      { w: 'Llave inglesa', t: ['Tuerca', 'Apretar', 'Ajustable', 'Metal', 'Herramienta'] },
      { w: 'Destornillador', t: ['Tornillo', 'Girar', 'Punta', 'Estrella', 'Mango'] },
      { w: 'Martillo', t: ['Clavo', 'Golpear', 'Mango', 'Dedo', 'Herramienta'] },
      { w: 'Taladro', t: ['Agujero', 'Pared', 'Ruido', 'Broca', 'Vecinos'] },
      { w: 'Sierra', t: ['Cortar', 'Madera', 'Dientes', 'Serrín', 'Vaivén'] },
      { w: 'Tornillo', t: ['Destornillador', 'Girar', 'Rosca', 'Apretar', 'Metal'] },
      { w: 'Clavo', t: ['Martillo', 'Golpear', 'Punta', 'Pared', 'Colgar'] },
      { w: 'Tuerca', t: ['Tornillo', 'Apretar', 'Rosca', 'Hexagonal', 'Llave'] },
      { w: 'Cinta métrica', t: ['Medir', 'Centímetros', 'Enrollar', 'Metal', 'Obra'] },
      { w: 'Nivel', t: ['Burbuja', 'Recto', 'Medir', 'Cuadro', 'Horizontal'] },
      { w: 'Alicates', t: ['Apretar', 'Cortar', 'Cable', 'Mango', 'Punta'] },
      { w: 'Lija', t: ['Papel', 'Frotar', 'Madera', 'Suave', 'Áspera'] },
      { w: 'Soldador', t: ['Calor', 'Metal', 'Unir', 'Chispas', 'Careta'] },
      { w: 'Andamio', t: ['Obra', 'Subir', 'Tubos', 'Altura', 'Fachada'] },
      { w: 'Carretilla', t: ['Rueda', 'Empujar', 'Obra', 'Cargar', 'Mangos'] },
      { w: 'Pala', t: ['Cavar', 'Tierra', 'Mango', 'Montón', 'Obra'] },
      { w: 'Pico', t: ['Cavar', 'Piedra', 'Golpear', 'Punta', 'Minero'] },
      { w: 'Cadena', t: ['Eslabones', 'Metal', 'Atar', 'Bicicleta', 'Romper'] },
      { w: 'Muelle', t: ['Espiral', 'Saltar', 'Estirar', 'Colchón', 'Metal'] },
      { w: 'Engranaje', t: ['Dientes', 'Girar', 'Ruedas', 'Máquina', 'Encajar'] },
      { w: 'Polea', t: ['Cuerda', 'Levantar', 'Girar', 'Peso', 'Pozo'] },
      { w: 'Manivela', t: ['Girar', 'Mano', 'Palanca', 'Dar vueltas', 'Antiguo'] },
      { w: 'Bomba de aire', t: ['Hinchar', 'Rueda', 'Presión', 'Bicicleta', 'Empujar'] },
      { w: 'Manguera', t: ['Agua', 'Larga', 'Enrollar', 'Regar', 'Goma'] },
      { w: 'Linterna', t: ['Luz', 'Pilas', 'Oscuridad', 'Mano', 'Enfocar'] },
      { w: 'Cinta aislante', t: ['Pegar', 'Cables', 'Negra', 'Rollo', 'Arreglo'] },
      { w: 'Caja de herramientas', t: ['Guardar', 'Metal', 'Asa', 'Taller', 'Abrir'] }
    ]
  },
  fiestas: {
    id: 'fiestas',
    name: 'Fiestas y costumbres',
    emoji: '🎉',
    desc: 'Celebraciones, manías y cosas de la calle.',
    cards: [
      { w: 'Navidad', t: ['Diciembre', 'Regalos', 'Familia', 'Belén', 'Turrón'] },
      { w: 'Papá Noel', t: ['Rojo', 'Barba', 'Trineo', 'Regalos', 'Chimenea'] },
      { w: 'Reyes Magos', t: ['Tres', 'Camellos', 'Regalos', 'Enero', 'Oriente'] },
      { w: 'Belén', t: ['Figuras', 'Musgo', 'Portal', 'Navidad', 'Montar'] },
      { w: 'Árbol de Navidad', t: ['Bolas', 'Luces', 'Verde', 'Regalos', 'Adornar'] },
      { w: 'Turrón', t: ['Almendra', 'Navidad', 'Duro', 'Blando', 'Tableta'] },
      { w: 'Roscón', t: ['Reyes', 'Sorpresa', 'Haba', 'Nata', 'Fruta'] },
      { w: 'Uvas', t: ['Doce', 'Campanadas', 'Nochevieja', 'Atragantarse', 'Racimo'] },
      { w: 'Campanadas', t: ['Doce', 'Reloj', 'Puerta del Sol', 'Año', 'Sonar'] },
      { w: 'Cotillón', t: ['Nochevieja', 'Gorros', 'Fiesta', 'Bolsa', 'Matasuegras'] },
      { w: 'Matasuegras', t: ['Soplar', 'Estirar', 'Fiesta', 'Papel', 'Ruido'] },
      { w: 'Carnaval', t: ['Disfraces', 'Febrero', 'Desfile', 'Máscaras', 'Cádiz'] },
      { w: 'Disfraz', t: ['Vestirse', 'Carnaval', 'Fingir', 'Halloween', 'Alquilar'] },
      { w: 'Confeti', t: ['Papelitos', 'Tirar', 'Colores', 'Fiesta', 'Suelo'] },
      { w: 'Serpentina', t: ['Rollo', 'Tirar', 'Papel', 'Colores', 'Fiesta'] },
      { w: 'Antifaz', t: ['Ojos', 'Máscara', 'Baile', 'Tapar', 'Misterio'] },
      { w: 'Halloween', t: ['Calabaza', 'Miedo', 'Octubre', 'Caramelos', 'Disfraces'] },
      { w: 'Calabaza', t: ['Naranja', 'Vaciar', 'Halloween', 'Huerto', 'Cara'] },
      { w: 'Semana Santa', t: ['Procesión', 'Abril', 'Torrijas', 'Vacaciones', 'Cofradía'] },
      { w: 'Procesión', t: ['Andar', 'Paso', 'Calle', 'Música', 'Lenta'] },
      { w: 'Feria', t: ['Atracciones', 'Casetas', 'Luces', 'Pueblo', 'Música'] },
      { w: 'Noria', t: ['Girar', 'Alta', 'Cabinas', 'Vistas', 'Feria'] },
      { w: 'Montaña rusa', t: ['Subir', 'Bajar', 'Gritar', 'Raíles', 'Vértigo'] },
      { w: 'Algodón de azúcar', t: ['Rosa', 'Dulce', 'Palo', 'Feria', 'Pegajoso'] },
      { w: 'Tómbola', t: ['Números', 'Premios', 'Papeletas', 'Feria', 'Suerte'] },
      { w: 'Verbena', t: ['Baile', 'Plaza', 'Orquesta', 'Noche', 'Pueblo'] },
      { w: 'Fuegos artificiales', t: ['Cielo', 'Colores', 'Explotar', 'Noche', 'Ruido'] },
      { w: 'Petardo', t: ['Ruido', 'Mecha', 'Explotar', 'Susto', 'Pólvora'] },
      { w: 'Hoguera', t: ['Fuego', 'Leña', 'Noche', 'Saltar', 'Playa'] },
      { w: 'San Juan', t: ['Playa', 'Hoguera', 'Junio', 'Noche', 'Deseos'] },
      { w: 'Tomatina', t: ['Tomates', 'Tirar', 'Buñol', 'Rojo', 'Guerra'] },
      { w: 'San Fermín', t: ['Pamplona', 'Rojo', 'Blanco', 'Toros', 'Julio'] },
      { w: 'Encierro', t: ['Correr', 'Toros', 'Calle', 'Vallas', 'Mañana'] },
      { w: 'Romería', t: ['Campo', 'Virgen', 'Andar', 'Comida', 'Pueblo'] },
      { w: 'Cabalgata', t: ['Carrozas', 'Caramelos', 'Reyes', 'Desfile', 'Calle'] },
      { w: 'Piñata', t: ['Palo', 'Golpear', 'Caramelos', 'Colgar', 'Cumpleaños'] },
      { w: 'Villancico', t: ['Cantar', 'Navidad', 'Pandereta', 'Niños', 'Coro'] },
      { w: 'Aniversario', t: ['Años', 'Pareja', 'Celebrar', 'Fecha', 'Recordar'] },
      { w: 'Bautizo', t: ['Agua', 'Bebé', 'Iglesia', 'Padrinos', 'Nombre'] },
      { w: 'Comunión', t: ['Niños', 'Traje', 'Iglesia', 'Banquete', 'Regalos'] },
      { w: 'Despedida de soltero', t: ['Boda', 'Amigos', 'Fiesta', 'Antes', 'Resaca'] },
      { w: 'Luna de miel', t: ['Boda', 'Viaje', 'Pareja', 'Después', 'Romántico'] },
      { w: 'Alianza', t: ['Anillo', 'Boda', 'Dedo', 'Oro', 'Pareja'] },
      { w: 'Ramo de novia', t: ['Flores', 'Tirar', 'Boda', 'Solteras', 'Coger'] },
      { w: 'Padrino', t: ['Boda', 'Bautizo', 'Acompañar', 'Regalo', 'Papel'] },
      { w: 'Invitación', t: ['Tarjeta', 'Boda', 'Confirmar', 'Enviar', 'Fecha'] },
      { w: 'Regalo', t: ['Papel', 'Lazo', 'Abrir', 'Sorpresa', 'Dar'] },
      { w: 'Amigo invisible', t: ['Sorteo', 'Regalo', 'Secreto', 'Navidad', 'Grupo'] },
      { w: 'Brindis', t: ['Copas', 'Chocar', 'Salud', 'Levantar', 'Celebrar'] },
      { w: 'Discurso', t: ['Hablar', 'Público', 'Nervios', 'Micrófono', 'Papel'] },
      { w: 'Vals', t: ['Bailar', 'Vueltas', 'Novios', 'Uno dos tres', 'Lento'] },
      { w: 'Pasodoble', t: ['Bailar', 'España', 'Pareja', 'Banda', 'Ritmo'] },
      { w: 'Picnic', t: ['Manta', 'Campo', 'Cesta', 'Comer', 'Hormigas'] },
      { w: 'Chiringuito', t: ['Playa', 'Bebidas', 'Verano', 'Arena', 'Terraza'] },
      { w: 'Terraza', t: ['Fuera', 'Mesas', 'Sol', 'Bar', 'Sombrilla'] },
      { w: 'Sobremesa', t: ['Después', 'Hablar', 'Café', 'Mesa', 'Larga'] },
      { w: 'Sorteo', t: ['Papeletas', 'Azar', 'Premio', 'Bombo', 'Ganar'] },
      { w: 'Lotería', t: ['Números', 'Décimo', 'Navidad', 'Premio', 'Niños'] },
      { w: 'Rifa', t: ['Papeletas', 'Premio', 'Vender', 'Número', 'Colegio'] },
      { w: 'Bingo', t: ['Cartón', 'Números', 'Cantar', 'Línea', 'Sala'] },
      { w: 'Horóscopo', t: ['Signos', 'Predicción', 'Revista', 'Estrellas', 'Creer'] },
      { w: 'Superstición', t: ['Mala suerte', 'Creer', 'Martes 13', 'Sal', 'Espejo'] },
      { w: 'Trébol', t: ['Cuatro hojas', 'Suerte', 'Verde', 'Buscar', 'Hierba'] },
      { w: 'Herradura', t: ['Caballo', 'Suerte', 'Colgar', 'Hierro', 'Puerta'] },
      { w: 'Amuleto', t: ['Suerte', 'Colgar', 'Llevar', 'Proteger', 'Creer'] },
      { w: 'Cotilleo', t: ['Hablar', 'Vecinas', 'Secreto', 'Revista', 'Contar'] },
      { w: 'Chiste', t: ['Reír', 'Contar', 'Gracia', 'Final', 'Malo'] },
      { w: 'Broma', t: ['Gastar', 'Reír', 'Susto', 'Pesada', 'Amigos'] },
      { w: 'Inocentada', t: ['Diciembre', 'Broma', 'Monigote', 'Espalda', 'Engañar'] },
      { w: 'Apodo', t: ['Mote', 'Llamar', 'Nombre', 'Pueblo', 'Gracioso'] },
      { w: 'Piropo', t: ['Decir', 'Guapa', 'Calle', 'Halago', 'Antiguo'] },
      { w: 'Abrazo', t: ['Brazos', 'Apretar', 'Cariño', 'Saludo', 'Fuerte'] },
      { w: 'Beso', t: ['Labios', 'Mejilla', 'Saludo', 'Sonido', 'Dos'] },
      { w: 'Apretón de manos', t: ['Saludo', 'Derecha', 'Trato', 'Firme', 'Presentarse'] },
      { w: 'Sonrisa', t: ['Boca', 'Dientes', 'Alegría', 'Foto', 'Cara'] },
      { w: 'Guiño', t: ['Ojo', 'Cerrar', 'Complicidad', 'Rápido', 'Señal'] },
      { w: 'Aplauso', t: ['Manos', 'Ruido', 'Final', 'Público', 'Felicitar'] },
      { w: 'Silbido', t: ['Boca', 'Sonido', 'Llamar', 'Agudo', 'Dedos'] },
      { w: 'Postal', t: ['Foto', 'Escribir', 'Sello', 'Viaje', 'Enviar'] },
      { w: 'Nochevieja', t: ['31', 'Diciembre', 'Fin de año', 'Fiesta', 'Cena'] }
    ]
  }
};

/* Todas las cartas de todos los packs, para contar y para el modo "todo". */
const ALL_CARDS = Object.values(PACKS).reduce((n, p) => n + p.cards.length, 0);

