/**
 * Bancos de palabras — EDICIÓN PEQUES.
 * Cada entrada: { w: "palabra secreta", p: "pista para el intruso" }
 *
 * Reglas del banco:
 *  - Todo lo que un niño de 10 años conoce sin dudar.
 *  - Una o dos palabras como máximo. Nada de frases.
 *  - Nada de contenido adulto: se juega en familia.
 */
const PACKS = {
  animales: {
    id: 'animales',
    name: 'Animales',
    emoji: '🐾',
    desc: 'De la granja, la selva y el mar.',
    words: [
      { w: 'Perro', p: 'Mascota' },
      { w: 'Gato', p: 'Mascota' },
      { w: 'Hámster', p: 'Mascota' },
      { w: 'León', p: 'Selva' },
      { w: 'Tigre', p: 'Selva' },
      { w: 'Leopardo', p: 'Selva' },
      { w: 'Guepardo', p: 'Rápido' },
      { w: 'Pantera', p: 'Selva' },
      { w: 'Elefante', p: 'Grande' },
      { w: 'Jirafa', p: 'Alto' },
      { w: 'Cebra', p: 'Rayas' },
      { w: 'Rinoceronte', p: 'Grande' },
      { w: 'Hipopótamo', p: 'Grande' },
      { w: 'Mono', p: 'Trepa' },
      { w: 'Gorila', p: 'Fuerte' },
      { w: 'Oso', p: 'Bosque' },
      { w: 'Panda', p: 'Oso' },
      { w: 'Koala', p: 'Árbol' },
      { w: 'Canguro', p: 'Salta' },
      { w: 'Perezoso', p: 'Lento' },
      { w: 'Suricata', p: 'Vigila' },
      { w: 'Mapache', p: 'Antifaz' },
      { w: 'Mofeta', p: 'Olor' },
      { w: 'Lobo', p: 'Bosque' },
      { w: 'Zorro', p: 'Astuto' },
      { w: 'Conejo', p: 'Orejas' },
      { w: 'Ardilla', p: 'Árbol' },
      { w: 'Erizo', p: 'Pinchos' },
      { w: 'Ratón', p: 'Pequeño' },
      { w: 'Topo', p: 'Bajo tierra' },
      { w: 'Murciélago', p: 'Noche' },
      { w: 'Castor', p: 'Río' },
      { w: 'Nutria', p: 'Río' },
      { w: 'Caballo', p: 'Granja' },
      { w: 'Burro', p: 'Granja' },
      { w: 'Vaca', p: 'Granja' },
      { w: 'Toro', p: 'Granja' },
      { w: 'Cerdo', p: 'Granja' },
      { w: 'Oveja', p: 'Granja' },
      { w: 'Cabra', p: 'Granja' },
      { w: 'Gallina', p: 'Granja' },
      { w: 'Gallo', p: 'Granja' },
      { w: 'Pato', p: 'Agua' },
      { w: 'Ganso', p: 'Granja' },
      { w: 'Pavo', p: 'Granja' },
      { w: 'Llama', p: 'Montaña' },
      { w: 'Camello', p: 'Desierto' },
      { w: 'Ciervo', p: 'Bosque' },
      { w: 'Reno', p: 'Frío' },
      { w: 'Jabalí', p: 'Bosque' },
      { w: 'Bisonte', p: 'Manada' },
      { w: 'Loro', p: 'Ave' },
      { w: 'Búho', p: 'Noche' },
      { w: 'Águila', p: 'Ave' },
      { w: 'Halcón', p: 'Ave' },
      { w: 'Cuervo', p: 'Negro' },
      { w: 'Pingüino', p: 'Frío' },
      { w: 'Flamenco', p: 'Rosa' },
      { w: 'Avestruz', p: 'Corre' },
      { w: 'Tucán', p: 'Pico' },
      { w: 'Pelícano', p: 'Pico' },
      { w: 'Cigüeña', p: 'Nido' },
      { w: 'Colibrí', p: 'Diminuto' },
      { w: 'Golondrina', p: 'Ave' },
      { w: 'Paloma', p: 'Ciudad' },
      { w: 'Tiburón', p: 'Mar' },
      { w: 'Ballena', p: 'Mar' },
      { w: 'Delfín', p: 'Mar' },
      { w: 'Orca', p: 'Mar' },
      { w: 'Foca', p: 'Mar' },
      { w: 'Morsa', p: 'Frío' },
      { w: 'Pulpo', p: 'Mar' },
      { w: 'Calamar', p: 'Mar' },
      { w: 'Medusa', p: 'Mar' },
      { w: 'Cangrejo', p: 'Playa' },
      { w: 'Caballito', p: 'Mar' },
      { w: 'Tortuga', p: 'Caparazón' },
      { w: 'Cocodrilo', p: 'Río' },
      { w: 'Serpiente', p: 'Repta' },
      { w: 'Lagarto', p: 'Repta' },
      { w: 'Camaleón', p: 'Cambia' },
      { w: 'Iguana', p: 'Repta' },
      { w: 'Rana', p: 'Charca' },
      { w: 'Sapo', p: 'Charca' },
      { w: 'Dinosaurio', p: 'Antiguo' },
      { w: 'Mamut', p: 'Antiguo' },
      { w: 'Araña', p: 'Telaraña' },
      { w: 'Hormiga', p: 'Insecto' },
      { w: 'Abeja', p: 'Insecto' },
      { w: 'Avispa', p: 'Insecto' },
      { w: 'Mariposa', p: 'Alas' },
      { w: 'Oruga', p: 'Insecto' },
      { w: 'Escarabajo', p: 'Insecto' },
      { w: 'Libélula', p: 'Insecto' },
      { w: 'Saltamontes', p: 'Salta' },
      { w: 'Mariquita', p: 'Puntos' },
      { w: 'Caracol', p: 'Lento' },
      { w: 'Ciempiés', p: 'Patas' },
      { w: 'Unicornio', p: 'Fantasía' },
      { w: 'Dragón', p: 'Fantasía' }
    ]
  },

  comida: {
    id: 'comida',
    name: 'Comida',
    emoji: '🍕',
    desc: 'Lo rico, lo sano y lo dulce.',
    words: [
      { w: 'Pizza', p: 'Cena' },
      { w: 'Hamburguesa', p: 'Cena' },
      { w: 'Perrito', p: 'Cena' },
      { w: 'Sándwich', p: 'Merienda' },
      { w: 'Bocadillo', p: 'Merienda' },
      { w: 'Tostada', p: 'Desayuno' },
      { w: 'Cereales', p: 'Desayuno' },
      { w: 'Tortitas', p: 'Desayuno' },
      { w: 'Gofre', p: 'Dulce' },
      { w: 'Croissant', p: 'Desayuno' },
      { w: 'Donut', p: 'Dulce' },
      { w: 'Magdalena', p: 'Dulce' },
      { w: 'Galleta', p: 'Dulce' },
      { w: 'Bizcocho', p: 'Dulce' },
      { w: 'Tarta', p: 'Cumpleaños' },
      { w: 'Helado', p: 'Frío' },
      { w: 'Batido', p: 'Bebida' },
      { w: 'Chocolate', p: 'Dulce' },
      { w: 'Caramelo', p: 'Chuche' },
      { w: 'Chicle', p: 'Chuche' },
      { w: 'Piruleta', p: 'Chuche' },
      { w: 'Gominolas', p: 'Chuche' },
      { w: 'Nubes', p: 'Chuche' },
      { w: 'Turrón', p: 'Navidad' },
      { w: 'Flan', p: 'Postre' },
      { w: 'Natillas', p: 'Postre' },
      { w: 'Yogur', p: 'Postre' },
      { w: 'Queso', p: 'Lácteo' },
      { w: 'Mantequilla', p: 'Untar' },
      { w: 'Mermelada', p: 'Untar' },
      { w: 'Miel', p: 'Dulce' },
      { w: 'Pan', p: 'Básico' },
      { w: 'Arroz', p: 'Básico' },
      { w: 'Macarrones', p: 'Pasta' },
      { w: 'Espaguetis', p: 'Pasta' },
      { w: 'Lasaña', p: 'Horno' },
      { w: 'Paella', p: 'Domingo' },
      { w: 'Tortilla', p: 'Sartén' },
      { w: 'Huevo', p: 'Básico' },
      { w: 'Jamón', p: 'Fiambre' },
      { w: 'Pollo', p: 'Carne' },
      { w: 'Filete', p: 'Carne' },
      { w: 'Albóndigas', p: 'Carne' },
      { w: 'Salchicha', p: 'Carne' },
      { w: 'Atún', p: 'Pescado' },
      { w: 'Salmón', p: 'Pescado' },
      { w: 'Gambas', p: 'Marisco' },
      { w: 'Sopa', p: 'Caliente' },
      { w: 'Puré', p: 'Caliente' },
      { w: 'Ensalada', p: 'Sano' },
      { w: 'Gazpacho', p: 'Frío' },
      { w: 'Lentejas', p: 'Legumbre' },
      { w: 'Garbanzos', p: 'Legumbre' },
      { w: 'Judías', p: 'Legumbre' },
      { w: 'Guisantes', p: 'Verde' },
      { w: 'Maíz', p: 'Amarillo' },
      { w: 'Patata', p: 'Verdura' },
      { w: 'Zanahoria', p: 'Verdura' },
      { w: 'Tomate', p: 'Rojo' },
      { w: 'Cebolla', p: 'Llorar' },
      { w: 'Lechuga', p: 'Verde' },
      { w: 'Pepino', p: 'Verdura' },
      { w: 'Pimiento', p: 'Verdura' },
      { w: 'Calabacín', p: 'Verdura' },
      { w: 'Berenjena', p: 'Morado' },
      { w: 'Brócoli', p: 'Verde' },
      { w: 'Coliflor', p: 'Verdura' },
      { w: 'Espinacas', p: 'Verde' },
      { w: 'Champiñón', p: 'Seta' },
      { w: 'Calabaza', p: 'Naranja' },
      { w: 'Aguacate', p: 'Verde' },
      { w: 'Manzana', p: 'Fruta' },
      { w: 'Pera', p: 'Fruta' },
      { w: 'Plátano', p: 'Fruta' },
      { w: 'Naranja', p: 'Fruta' },
      { w: 'Mandarina', p: 'Fruta' },
      { w: 'Limón', p: 'Ácido' },
      { w: 'Fresa', p: 'Fruta' },
      { w: 'Cereza', p: 'Fruta' },
      { w: 'Uva', p: 'Fruta' },
      { w: 'Melón', p: 'Verano' },
      { w: 'Sandía', p: 'Verano' },
      { w: 'Piña', p: 'Tropical' },
      { w: 'Kiwi', p: 'Fruta' },
      { w: 'Melocotón', p: 'Fruta' },
      { w: 'Mango', p: 'Tropical' },
      { w: 'Coco', p: 'Tropical' },
      { w: 'Frambuesa', p: 'Fruta' },
      { w: 'Almendra', p: 'Fruto seco' },
      { w: 'Cacahuete', p: 'Fruto seco' },
      { w: 'Nuez', p: 'Fruto seco' },
      { w: 'Aceituna', p: 'Aperitivo' },
      { w: 'Palomitas', p: 'Cine' },
      { w: 'Nachos', p: 'Aperitivo' },
      { w: 'Ketchup', p: 'Salsa' },
      { w: 'Mostaza', p: 'Salsa' },
      { w: 'Agua', p: 'Bebida' },
      { w: 'Zumo', p: 'Bebida' },
      { w: 'Limonada', p: 'Bebida' },
      { w: 'Sal', p: 'Cocina' }
    ]
  },

  dibus: {
    id: 'dibus',
    name: 'Dibus y juegos',
    emoji: '🎮',
    desc: 'Personajes, pelis y videojuegos.',
    words: [
      { w: 'Mario', p: 'Videojuego' },
      { w: 'Luigi', p: 'Videojuego' },
      { w: 'Peach', p: 'Videojuego' },
      { w: 'Bowser', p: 'Malo' },
      { w: 'Yoshi', p: 'Videojuego' },
      { w: 'Sonic', p: 'Rápido' },
      { w: 'Pikachu', p: 'Pokémon' },
      { w: 'Charmander', p: 'Pokémon' },
      { w: 'Squirtle', p: 'Pokémon' },
      { w: 'Eevee', p: 'Pokémon' },
      { w: 'Pokébola', p: 'Objeto' },
      { w: 'Kirby', p: 'Rosa' },
      { w: 'Zelda', p: 'Videojuego' },
      { w: 'Link', p: 'Videojuego' },
      { w: 'Minecraft', p: 'Bloques' },
      { w: 'Creeper', p: 'Explota' },
      { w: 'Enderman', p: 'Alto' },
      { w: 'Fortnite', p: 'Videojuego' },
      { w: 'Roblox', p: 'Videojuego' },
      { w: 'Among Us', p: 'Nave' },
      { w: 'Fall Guys', p: 'Carrera' },
      { w: 'Brawl Stars', p: 'Móvil' },
      { w: 'Angry Birds', p: 'Móvil' },
      { w: 'Tetris', p: 'Piezas' },
      { w: 'Pacman', p: 'Clásico' },
      { w: 'Just Dance', p: 'Bailar' },
      { w: 'Nintendo', p: 'Consola' },
      { w: 'PlayStation', p: 'Consola' },
      { w: 'Bob Esponja', p: 'Dibujos' },
      { w: 'Patricio', p: 'Dibujos' },
      { w: 'Calamardo', p: 'Dibujos' },
      { w: 'Los Simpson', p: 'Serie' },
      { w: 'Homer', p: 'Serie' },
      { w: 'Bart', p: 'Serie' },
      { w: 'Lisa', p: 'Serie' },
      { w: 'Peppa Pig', p: 'Peques' },
      { w: 'Pocoyó', p: 'Peques' },
      { w: 'Bluey', p: 'Peques' },
      { w: 'Doraemon', p: 'Dibujos' },
      { w: 'Shin Chan', p: 'Dibujos' },
      { w: 'Naruto', p: 'Anime' },
      { w: 'Goku', p: 'Anime' },
      { w: 'Vegeta', p: 'Anime' },
      { w: 'Ladybug', p: 'Dibujos' },
      { w: 'Scooby Doo', p: 'Misterio' },
      { w: 'Piolín', p: 'Clásico' },
      { w: 'Bugs Bunny', p: 'Clásico' },
      { w: 'Mickey Mouse', p: 'Disney' },
      { w: 'Minnie', p: 'Disney' },
      { w: 'Donald', p: 'Disney' },
      { w: 'Goofy', p: 'Disney' },
      { w: 'Pluto', p: 'Disney' },
      { w: 'Buzz Lightyear', p: 'Juguete' },
      { w: 'Woody', p: 'Juguete' },
      { w: 'Toy Story', p: 'Película' },
      { w: 'Nemo', p: 'Pez' },
      { w: 'Dory', p: 'Pez' },
      { w: 'Simba', p: 'Rey León' },
      { w: 'Timón', p: 'Rey León' },
      { w: 'Pumba', p: 'Rey León' },
      { w: 'Olaf', p: 'Frozen' },
      { w: 'Elsa', p: 'Frozen' },
      { w: 'Anna', p: 'Frozen' },
      { w: 'Moana', p: 'Disney' },
      { w: 'Rapunzel', p: 'Pelo' },
      { w: 'Ariel', p: 'Sirena' },
      { w: 'Cenicienta', p: 'Zapato' },
      { w: 'Blancanieves', p: 'Cuento' },
      { w: 'Aladdín', p: 'Lámpara' },
      { w: 'Genio', p: 'Deseos' },
      { w: 'Shrek', p: 'Verde' },
      { w: 'Fiona', p: 'Shrek' },
      { w: 'Gru', p: 'Villano' },
      { w: 'Minions', p: 'Amarillos' },
      { w: 'Stitch', p: 'Disney' },
      { w: 'Madagascar', p: 'Película' },
      { w: 'Ratatouille', p: 'Cocina' },
      { w: 'Wall-E', p: 'Robot' },
      { w: 'Bambi', p: 'Disney' },
      { w: 'Encanto', p: 'Película' },
      { w: 'Zootrópolis', p: 'Película' },
      { w: 'Rayo McQueen', p: 'Coche' },
      { w: 'Harry Potter', p: 'Magia' },
      { w: 'Hermione', p: 'Magia' },
      { w: 'Hagrid', p: 'Magia' },
      { w: 'Varita', p: 'Magia' },
      { w: 'Spiderman', p: 'Héroe' },
      { w: 'Batman', p: 'Héroe' },
      { w: 'Superman', p: 'Héroe' },
      { w: 'Hulk', p: 'Héroe' },
      { w: 'Iron Man', p: 'Héroe' },
      { w: 'Capitán América', p: 'Héroe' },
      { w: 'Thor', p: 'Martillo' },
      { w: 'Groot', p: 'Árbol' },
      { w: 'Yoda', p: 'Star Wars' },
      { w: 'Chewbacca', p: 'Star Wars' },
      { w: 'Darth Vader', p: 'Malo' },
      { w: 'R2-D2', p: 'Robot' },
      { w: 'Godzilla', p: 'Monstruo' },
      { w: 'King Kong', p: 'Monstruo' }
    ]
  },

  cosas: {
    id: 'cosas',
    name: 'Cosas y sitios',
    emoji: '🎒',
    desc: 'El cole, la casa y la calle.',
    words: [
      { w: 'Mochila', p: 'Cole' },
      { w: 'Estuche', p: 'Cole' },
      { w: 'Lápiz', p: 'Escribir' },
      { w: 'Goma', p: 'Borrar' },
      { w: 'Sacapuntas', p: 'Cole' },
      { w: 'Bolígrafo', p: 'Escribir' },
      { w: 'Rotulador', p: 'Colores' },
      { w: 'Pincel', p: 'Pintar' },
      { w: 'Tijeras', p: 'Cortar' },
      { w: 'Pegamento', p: 'Pegar' },
      { w: 'Cuaderno', p: 'Cole' },
      { w: 'Libro', p: 'Leer' },
      { w: 'Regla', p: 'Medir' },
      { w: 'Calculadora', p: 'Números' },
      { w: 'Pizarra', p: 'Clase' },
      { w: 'Tiza', p: 'Clase' },
      { w: 'Pupitre', p: 'Clase' },
      { w: 'Recreo', p: 'Cole' },
      { w: 'Patio', p: 'Cole' },
      { w: 'Timbre', p: 'Sonido' },
      { w: 'Deberes', p: 'Cole' },
      { w: 'Examen', p: 'Cole' },
      { w: 'Profesor', p: 'Cole' },
      { w: 'Comedor', p: 'Cole' },
      { w: 'Biblioteca', p: 'Libros' },
      { w: 'Cama', p: 'Dormir' },
      { w: 'Almohada', p: 'Dormir' },
      { w: 'Manta', p: 'Calor' },
      { w: 'Armario', p: 'Ropa' },
      { w: 'Espejo', p: 'Reflejo' },
      { w: 'Lámpara', p: 'Luz' },
      { w: 'Ventana', p: 'Casa' },
      { w: 'Puerta', p: 'Casa' },
      { w: 'Llave', p: 'Abrir' },
      { w: 'Escalera', p: 'Subir' },
      { w: 'Ascensor', p: 'Subir' },
      { w: 'Sofá', p: 'Salón' },
      { w: 'Televisión', p: 'Salón' },
      { w: 'Nevera', p: 'Cocina' },
      { w: 'Horno', p: 'Cocina' },
      { w: 'Microondas', p: 'Cocina' },
      { w: 'Lavadora', p: 'Ropa' },
      { w: 'Escoba', p: 'Limpiar' },
      { w: 'Fregona', p: 'Limpiar' },
      { w: 'Jabón', p: 'Lavar' },
      { w: 'Champú', p: 'Pelo' },
      { w: 'Toalla', p: 'Secar' },
      { w: 'Cepillo', p: 'Dientes' },
      { w: 'Peine', p: 'Pelo' },
      { w: 'Bañera', p: 'Baño' },
      { w: 'Ducha', p: 'Baño' },
      { w: 'Grifo', p: 'Agua' },
      { w: 'Reloj', p: 'Hora' },
      { w: 'Despertador', p: 'Mañana' },
      { w: 'Calendario', p: 'Días' },
      { w: 'Móvil', p: 'Pantalla' },
      { w: 'Ordenador', p: 'Pantalla' },
      { w: 'Tablet', p: 'Pantalla' },
      { w: 'Cargador', p: 'Batería' },
      { w: 'Auriculares', p: 'Música' },
      { w: 'Cámara', p: 'Fotos' },
      { w: 'Bicicleta', p: 'Ruedas' },
      { w: 'Patinete', p: 'Ruedas' },
      { w: 'Monopatín', p: 'Ruedas' },
      { w: 'Patines', p: 'Ruedas' },
      { w: 'Casco', p: 'Cabeza' },
      { w: 'Balón', p: 'Deporte' },
      { w: 'Portería', p: 'Fútbol' },
      { w: 'Canasta', p: 'Baloncesto' },
      { w: 'Raqueta', p: 'Deporte' },
      { w: 'Piscina', p: 'Agua' },
      { w: 'Flotador', p: 'Piscina' },
      { w: 'Columpio', p: 'Parque' },
      { w: 'Tobogán', p: 'Parque' },
      { w: 'Parque', p: 'Jugar' },
      { w: 'Playa', p: 'Verano' },
      { w: 'Montaña', p: 'Naturaleza' },
      { w: 'Bosque', p: 'Árboles' },
      { w: 'Río', p: 'Agua' },
      { w: 'Nieve', p: 'Frío' },
      { w: 'Lluvia', p: 'Mojarse' },
      { w: 'Paraguas', p: 'Lluvia' },
      { w: 'Arcoíris', p: 'Colores' },
      { w: 'Cometa', p: 'Viento' },
      { w: 'Globo', p: 'Fiesta' },
      { w: 'Piñata', p: 'Cumpleaños' },
      { w: 'Regalo', p: 'Cumpleaños' },
      { w: 'Disfraz', p: 'Fiesta' },
      { w: 'Linterna', p: 'Luz' },
      { w: 'Semáforo', p: 'Calle' },
      { w: 'Farola', p: 'Calle' },
      { w: 'Buzón', p: 'Cartas' },
      { w: 'Autobús', p: 'Transporte' },
      { w: 'Tren', p: 'Transporte' },
      { w: 'Avión', p: 'Volar' },
      { w: 'Barco', p: 'Mar' },
      { w: 'Cohete', p: 'Espacio' },
      { w: 'Coche', p: 'Carretera' },
      { w: 'Peluche', p: 'Juguete' },
      { w: 'Puzzle', p: 'Piezas' }
    ]
  }
};
